import BilinearComplexity.NormalizedBinaryCoverageData

set_option autoImplicit false
set_option maxRecDepth 10000
set_option maxHeartbeats 1000000

namespace BilinearComplexity.NormalizedBinaryCoverageTables.Shard000

open BilinearComplexity.NormalizedBinaryCarrier
open BilinearComplexity.NormalizedBinaryCoverageData
open BilinearComplexity.NormalizedBinaryFiniteAction

/-- Generated raw coverage actions 0 through 89 for profile 221.
Source: coverage_actions.json, SHA-256 bdb8a983a8cad61c375811e21a5cdb831dac77ceb70e4b9eb832d26df727f0bf. -/
def rawActions : List (RawCoverageAction profile221 (Fin 3)) := [
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨2, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩, ⟨2, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨2, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨2, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩]
      right := [⟨2, 3, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 2, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 1, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨2, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨1, 3, 1⟩, ⟨2, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨2, 3, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 1, 1⟩, ⟨2, 2, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨3, 2, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨2, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 2, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨1, 3, 1⟩, ⟨2, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨2, 3, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 2, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨2, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨3, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 0, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 3, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨3, 3, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 3, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![1, 1; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 1, 1⟩, ⟨3, 3, 1⟩]
      right := [⟨1, 2, 1⟩, ⟨2, 1, 1⟩, ⟨2, 3, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![1, 0; 0, 1]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩]
      right := [⟨2, 2, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨2, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨1, 3, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨2, 1, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨2, 1, 1⟩, ⟨2, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨3, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 0, 1]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![1, 0; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 2, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨0, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 1, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨3, 2, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![0, 1; 1, 0]
      second := !![0, 1; 1, 1]
      third := !![1]
      orientation := .bac }
    target := {
      left := [⟨2, 2, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨3, 1, 1⟩] } },
  { sourceRowIndex := ⟨1, by decide⟩
    profileAction := {
      first := !![1, 0; 1, 1]
      second := !![0, 1; 1, 0]
      third := !![1]
      orientation := .abc }
    target := {
      left := [⟨3, 1, 1⟩, ⟨3, 2, 1⟩]
      right := [⟨1, 3, 1⟩, ⟨2, 1, 1⟩, ⟨2, 2, 1⟩] } }
]

/-- Every generated action in this shard passes target decoding, raw matrix
validity, and the reflected endpoint equations, producing actual entries. -/
theorem allChecksSucceed :
    (RawCoverageAction.Entry.reflectedCheckAll selectedRowSources221 rawActions).isSome = true := by
  decide

/-- Actual checked entries corresponding to every raw action in this shard. -/
def entries : List (RawCoverageAction.Entry selectedRowSources221) :=
  (RawCoverageAction.Entry.reflectedCheckAll selectedRowSources221 rawActions).get allChecksSucceed

/-- Projecting checked entries recovers every serialized action exactly. -/
theorem entries_rawActions : entries.map RawCoverageAction.Entry.raw = rawActions :=
  RawCoverageAction.Entry.reflectedCheckAll_get_raws selectedRowSources221 rawActions allChecksSucceed

/-- The shard's literal target set, independent of checker/get reduction. -/
def literalTargetSet : Finset (RelationEndpoints profile221) :=
  RawCoverageAction.decodedTargetSet rawActions

#print axioms allChecksSucceed

end BilinearComplexity.NormalizedBinaryCoverageTables.Shard000
