import BilinearComplexity.BinaryFiveCircuitCompiler

/-!
# Context transport for normalized binary move paths

This module gives an executable inverse lookup for the finite coordinate box of an
`ExactSpanPresentation`. It splits an arbitrary ambient context into its local and
outside parts, proves the split exact and disjoint, and transports normalized paths
into ambient coordinates while keeping the outside part fixed. The resulting paths
have explicit vertices, unchanged length, additive altitude, reconstructed endpoints,
and a constant outside-box projection at every vertex.
-/

set_option autoImplicit false

namespace BilinearComplexity.BinaryAmbientContextTransport

open BinaryCircuit
open BinaryAmbientCarrier
open BinaryAmbientMoves
open BinaryAmbientMoveTransport
open BinaryAmbientNormalization
open BinaryFiveCircuitCompiler
open NormalizedBinaryCarrier

universe u v w

variable {U : Type u} {V : Type v} {W : Type w}
variable [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
variable [Module F2 U] [Module F2 V] [Module F2 W]
variable [DecidableEq U] [DecidableEq V] [DecidableEq W]

/-- Every normalized nonzero pure coordinate term in a profile. -/
def normalizedBox (p : Profile) : State p := Finset.univ

/-- The finite exact-span box embedded in the ambient carrier. -/
def localBox {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) : BinaryAmbientCarrier.State U V W :=
  mapState (exactSpanCoordinateEmbedding P) (normalizedBox P.profile)

/-- Executably recover all local coordinate terms present in an ambient context. -/
def normalizeLocalContext {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    State P.profile :=
  (normalizedBox P.profile).filter
    (fun t => mapTerm (exactSpanCoordinateEmbedding P) t ∈ C)

/-- The terms of an ambient context outside the endpoint-generated local box. -/
def outsideContext {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State U V W := C \ localBox P

/-- Membership in the normalized box is automatic. -/
@[simp] theorem mem_normalizedBox {p : Profile} (t : Carrier p) :
    t ∈ normalizedBox p := Finset.mem_univ t

/-- The local box is exactly the coordinate image of the normalized box. -/
theorem localBox_eq_mapState {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) :
    localBox P = mapState (exactSpanCoordinateEmbedding P) (normalizedBox P.profile) := rfl

/-- An ambient term lies in the local box exactly when all three factors lie in the
corresponding exact spans generated by the two endpoints. -/
theorem mem_localBox_iff {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (t : BinaryAmbientCarrier.Carrier U V W) :
    t ∈ localBox P ↔
      t.1.1 ∈ firstSpan (A ∪ B) ∧
      t.2.1.1 ∈ secondSpan (A ∪ B) ∧
      t.2.2.1 ∈ thirdSpan (A ∪ B) := by
  constructor
  · intro ht
    obtain ⟨s, hs, hst⟩ := Finset.mem_image.mp ht
    rw [← hst]
    exact ⟨(P.firstCoordinates s.1.1).property,
      (P.secondCoordinates s.2.1.1).property,
      (P.thirdCoordinates s.2.2.1).property⟩
  · rintro ⟨hfirst, hsecond, hthird⟩
    let x := P.firstCoordinates.symm ⟨t.1.1, hfirst⟩
    let y := P.secondCoordinates.symm ⟨t.2.1.1, hsecond⟩
    let z := P.thirdCoordinates.symm ⟨t.2.2.1, hthird⟩
    have hx : x ≠ 0 := by
      intro hxzero
      have hsub : (⟨t.1.1, hfirst⟩ : firstSpan (A ∪ B)) = 0 := by
        calc
          _ = P.firstCoordinates x := (P.firstCoordinates.apply_symm_apply _).symm
          _ = P.firstCoordinates 0 := congrArg P.firstCoordinates hxzero
          _ = 0 := P.firstCoordinates.map_zero
      exact t.1.2 (congrArg Subtype.val hsub)
    have hy : y ≠ 0 := by
      intro hyzero
      have hsub : (⟨t.2.1.1, hsecond⟩ : secondSpan (A ∪ B)) = 0 := by
        calc
          _ = P.secondCoordinates y := (P.secondCoordinates.apply_symm_apply _).symm
          _ = P.secondCoordinates 0 := congrArg P.secondCoordinates hyzero
          _ = 0 := P.secondCoordinates.map_zero
      exact t.2.1.2 (congrArg Subtype.val hsub)
    have hz : z ≠ 0 := by
      intro hzzero
      have hsub : (⟨t.2.2.1, hthird⟩ : thirdSpan (A ∪ B)) = 0 := by
        calc
          _ = P.thirdCoordinates z := (P.thirdCoordinates.apply_symm_apply _).symm
          _ = P.thirdCoordinates 0 := congrArg P.thirdCoordinates hzzero
          _ = 0 := P.thirdCoordinates.map_zero
      exact t.2.2.2 (congrArg Subtype.val hsub)
    let s : NormalizedBinaryCarrier.Carrier P.profile :=
      (⟨x, hx⟩, ⟨y, hy⟩, ⟨z, hz⟩)
    apply Finset.mem_image.mpr
    refine ⟨s, Finset.mem_univ _, ?_⟩
    apply Prod.ext
    · apply Subtype.ext
      change (P.firstCoordinates x).1 = t.1.1
      simp only [x, P.firstCoordinates.apply_symm_apply]
    · apply Prod.ext
      · apply Subtype.ext
        change (P.secondCoordinates y).1 = t.2.1.1
        simp only [y, P.secondCoordinates.apply_symm_apply]
      · apply Subtype.ext
        change (P.thirdCoordinates z).1 = t.2.2.1
        simp only [z, P.thirdCoordinates.apply_symm_apply]

/-- Mapping the executable local lookup gives precisely the context-box intersection. -/
@[simp] theorem mapState_normalizeLocalContext {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    mapState (exactSpanCoordinateEmbedding P) (normalizeLocalContext P C) =
      C ∩ localBox P := by
  ext t
  constructor
  · intro ht
    obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp ht
    simp only [normalizeLocalContext, normalizedBox, Finset.mem_filter,
      Finset.mem_univ, true_and] at hs
    exact Finset.mem_inter.mpr ⟨hs, Finset.mem_image.mpr ⟨s, Finset.mem_univ _, rfl⟩⟩
  · intro ht
    obtain ⟨htC, htL⟩ := Finset.mem_inter.mp ht
    obtain ⟨s, _hs, hst⟩ := Finset.mem_image.mp htL
    subst t
    exact Finset.mem_image.mpr ⟨s,
      by simp [normalizeLocalContext, normalizedBox, htC], rfl⟩

/-- The outside part together with the recovered local part reconstructs the context. -/
@[simp] theorem outsideContext_union_local {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    outsideContext P C ∪
      mapState (exactSpanCoordinateEmbedding P) (normalizeLocalContext P C) = C := by
  rw [mapState_normalizeLocalContext]
  exact Finset.sdiff_union_inter C (localBox P)

/-- The outside part is disjoint from the complete local coordinate box. -/
@[simp] theorem outsideContext_disjoint_localBox {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    Disjoint (outsideContext P C) (localBox P) := by
  exact Finset.sdiff_disjoint

/-- The outside part is disjoint from the image of every normalized state. -/
@[simp] theorem outsideContext_disjoint_mapped {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    (D : State P.profile) :
    Disjoint (outsideContext P C)
      (mapState (exactSpanCoordinateEmbedding P) D) := by
  apply Finset.disjoint_of_subset_right _ (outsideContext_disjoint_localBox P C)
  intro t ht
  obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp ht
  exact Finset.mem_image.mpr ⟨s, Finset.mem_univ _, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem generatedFirstSplit_union_left
    {source outputLeft outputRight : Carrier U V W}
    {D E O : BinaryAmbientCarrier.State U V W}
    (h : GeneratedFirstSplit source outputLeft outputRight D E)
    (hOD : Disjoint O D) (hOE : Disjoint O E) :
    GeneratedFirstSplit source outputLeft outputRight (O ∪ D) (O ∪ E) := by
  rcases h with ⟨hsource, houtputs, hfreshLeft, hfreshRight, hsum,
    hleftSecond, hrightSecond, hleftThird, hrightThird, rfl⟩
  have hsourceO : source ∉ O := fun hmem =>
    Finset.disjoint_left.mp hOD hmem hsource
  have hleftO : outputLeft ∉ O := by
    intro hmem
    apply Finset.disjoint_left.mp hOE hmem
    simp
  have hrightO : outputRight ∉ O := by
    intro hmem
    apply Finset.disjoint_left.mp hOE hmem
    simp
  refine ⟨Finset.mem_union_right O hsource, houtputs, ?_, ?_, hsum,
    hleftSecond, hrightSecond, hleftThird, hrightThird, ?_⟩
  · simpa [hsourceO, hleftO] using hfreshLeft
  · simpa [hsourceO, hrightO] using hfreshRight
  · ext t
    simp only [Finset.mem_insert, Finset.mem_erase, Finset.mem_union]
    by_cases htO : t ∈ O <;>
      by_cases htLeft : t = outputLeft <;>
      by_cases htRight : t = outputRight <;>
      by_cases htSource : t = source <;> simp_all

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem sourceThirdFlip_union_left
    {sourceLeft sourceRight targetLeft targetRight : Carrier U V W}
    {D E O : BinaryAmbientCarrier.State U V W}
    (h : SourceThirdFlip sourceLeft sourceRight targetLeft targetRight D E)
    (hOD : Disjoint O D) (hOE : Disjoint O E) :
    SourceThirdFlip sourceLeft sourceRight targetLeft targetRight (O ∪ D) (O ∪ E) := by
  rcases h with ⟨hleft, hright, hsources, hfreshLeft, hfreshRight, htargets,
    hthird, htargetLeftFirst, htargetLeftSecond, htargetLeftThird,
    htargetRightFirst, htargetRightSecond, htargetRightThird, rfl⟩
  have hleftO : sourceLeft ∉ O := fun hmem => Finset.disjoint_left.mp hOD hmem hleft
  have hrightO : sourceRight ∉ O := fun hmem => Finset.disjoint_left.mp hOD hmem hright
  have htargetLeftO : targetLeft ∉ O := by
    intro hmem
    apply Finset.disjoint_left.mp hOE hmem
    simp
  have htargetRightO : targetRight ∉ O := by
    intro hmem
    apply Finset.disjoint_left.mp hOE hmem
    simp
  refine ⟨Finset.mem_union_right O hleft, Finset.mem_union_right O hright,
    hsources, ?_, ?_, htargets, hthird, htargetLeftFirst, htargetLeftSecond,
    htargetLeftThird, htargetRightFirst, htargetRightSecond,
    htargetRightThird, ?_⟩
  · simpa [hleftO, hrightO, htargetLeftO] using hfreshLeft
  · simpa [hleftO, hrightO, htargetRightO] using hfreshRight
  · ext t
    simp only [Finset.mem_insert, Finset.mem_erase, Finset.mem_union]
    by_cases htO : t ∈ O <;>
      by_cases htTargetLeft : t = targetLeft <;>
      by_cases htTargetRight : t = targetRight <;>
      by_cases htSourceLeft : t = sourceLeft <;>
      by_cases htSourceRight : t = sourceRight <;> simp_all

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem directedNarrowPairReduction_union_left
    {sourceLeft sourceRight target : Carrier U V W}
    {D E O : BinaryAmbientCarrier.State U V W}
    (h : DirectedNarrowPairReduction sourceLeft sourceRight target D E)
    (hOD : Disjoint O D) (hOE : Disjoint O E) :
    DirectedNarrowPairReduction sourceLeft sourceRight target (O ∪ D) (O ∪ E) := by
  rcases h with ⟨hleft, hright, hsources, hfresh, hsecond, hthird,
    htargetFirst, htargetSecond, htargetThird, rfl⟩
  have hleftO : sourceLeft ∉ O := fun hmem => Finset.disjoint_left.mp hOD hmem hleft
  have hrightO : sourceRight ∉ O := fun hmem => Finset.disjoint_left.mp hOD hmem hright
  have htargetO : target ∉ O := by
    intro hmem
    apply Finset.disjoint_left.mp hOE hmem
    simp
  refine ⟨Finset.mem_union_right O hleft, Finset.mem_union_right O hright,
    hsources, ?_, hsecond, hthird, htargetFirst, htargetSecond, htargetThird, ?_⟩
  · simpa [hleftO, hrightO, htargetO] using hfresh
  · ext t
    simp only [Finset.mem_insert, Finset.mem_erase, Finset.mem_union]
    by_cases htO : t ∈ O <;>
      by_cases htTarget : t = target <;>
      by_cases htSourceLeft : t = sourceLeft <;>
      by_cases htSourceRight : t = sourceRight <;> simp_all

omit [Module F2 U] [Module F2 V] [Module F2 W] in
/-- Union with a background disjoint from both endpoints preserves an ordered intrinsic move. -/
theorem move_union_left {D E O : BinaryAmbientCarrier.State U V W}
    (h : Move D E) (hOD : Disjoint O D) (hOE : Disjoint O E) :
    Move (O ∪ D) (O ∪ E) := by
  cases h with
  | generatedFirstSplit hs => exact .generatedFirstSplit (generatedFirstSplit_union_left hs hOD hOE)
  | sourceThirdFlip hf => exact .sourceThirdFlip (sourceThirdFlip_union_left hf hOD hOE)
  | directedNarrowPairReduction hr => exact .directedNarrowPairReduction (directedNarrowPairReduction_union_left hr hOD hOE)

private def unpermuteBCAState (O : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State W U V :=
  O.image fun t => (t.2.2, t.1, t.2.1)

private def unpermuteCABState (O : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State V W U :=
  O.image fun t => (t.2.1, t.2.2, t.1)

private def unpermuteACBState (O : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State U W V :=
  O.image fun t => (t.1, t.2.2, t.2.1)

private def unpermuteCBAState (O : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State W V U :=
  O.image fun t => (t.2.2, t.2.1, t.1)

private def unpermuteBACState (O : BinaryAmbientCarrier.State U V W) :
    BinaryAmbientCarrier.State V U W :=
  O.image fun t => (t.2.1, t.1, t.2.2)

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem permuteBCAState_unpermuteBCAState
    (O : BinaryAmbientCarrier.State U V W) :
    permuteBCAState (unpermuteBCAState O) = O := by
  simp only [permuteBCAState, unpermuteBCAState, Finset.image_image]
  calc
    _ = O.image id := by
      apply Finset.image_congr
      intro t _ht
      rfl
    _ = O := Finset.image_id

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem permuteCABState_unpermuteCABState
    (O : BinaryAmbientCarrier.State U V W) :
    permuteCABState (unpermuteCABState O) = O := by
  simp only [permuteCABState, unpermuteCABState, Finset.image_image]
  calc
    _ = O.image id := by
      apply Finset.image_congr
      intro t _ht
      rfl
    _ = O := Finset.image_id

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem permuteACBState_unpermuteACBState
    (O : BinaryAmbientCarrier.State U V W) :
    permuteACBState (unpermuteACBState O) = O := by
  simp only [permuteACBState, unpermuteACBState, Finset.image_image]
  calc
    _ = O.image id := by
      apply Finset.image_congr
      intro t _ht
      rfl
    _ = O := Finset.image_id

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem permuteCBAState_unpermuteCBAState
    (O : BinaryAmbientCarrier.State U V W) :
    permuteCBAState (unpermuteCBAState O) = O := by
  simp only [permuteCBAState, unpermuteCBAState, Finset.image_image]
  calc
    _ = O.image id := by
      apply Finset.image_congr
      intro t _ht
      rfl
    _ = O := Finset.image_id

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem permuteBACState_unpermuteBACState
    (O : BinaryAmbientCarrier.State U V W) :
    permuteBACState (unpermuteBACState O) = O := by
  simp only [permuteBACState, unpermuteBACState, Finset.image_image]
  calc
    _ = O.image id := by
      apply Finset.image_congr
      intro t _ht
      rfl
    _ = O := Finset.image_id

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem unpermuteBCAState_disjoint
    {O : BinaryAmbientCarrier.State U V W}
    {D : BinaryAmbientCarrier.State W U V}
    (h : Disjoint O (permuteBCAState D)) :
    Disjoint (unpermuteBCAState O) D := by
  refine Finset.disjoint_left.mpr ?_
  intro t htO htD
  obtain ⟨⟨s₁, s₂, s₃⟩, hsO, rfl⟩ := Finset.mem_image.mp htO
  apply Finset.disjoint_left.mp h hsO
  exact Finset.mem_image.mpr ⟨_, htD, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem unpermuteCABState_disjoint
    {O : BinaryAmbientCarrier.State U V W}
    {D : BinaryAmbientCarrier.State V W U}
    (h : Disjoint O (permuteCABState D)) :
    Disjoint (unpermuteCABState O) D := by
  refine Finset.disjoint_left.mpr ?_
  intro t htO htD
  obtain ⟨⟨s₁, s₂, s₃⟩, hsO, rfl⟩ := Finset.mem_image.mp htO
  apply Finset.disjoint_left.mp h hsO
  exact Finset.mem_image.mpr ⟨_, htD, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem unpermuteACBState_disjoint
    {O : BinaryAmbientCarrier.State U V W}
    {D : BinaryAmbientCarrier.State U W V}
    (h : Disjoint O (permuteACBState D)) :
    Disjoint (unpermuteACBState O) D := by
  refine Finset.disjoint_left.mpr ?_
  intro t htO htD
  obtain ⟨⟨s₁, s₂, s₃⟩, hsO, rfl⟩ := Finset.mem_image.mp htO
  apply Finset.disjoint_left.mp h hsO
  exact Finset.mem_image.mpr ⟨_, htD, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem unpermuteCBAState_disjoint
    {O : BinaryAmbientCarrier.State U V W}
    {D : BinaryAmbientCarrier.State W V U}
    (h : Disjoint O (permuteCBAState D)) :
    Disjoint (unpermuteCBAState O) D := by
  refine Finset.disjoint_left.mpr ?_
  intro t htO htD
  obtain ⟨⟨s₁, s₂, s₃⟩, hsO, rfl⟩ := Finset.mem_image.mp htO
  apply Finset.disjoint_left.mp h hsO
  exact Finset.mem_image.mpr ⟨_, htD, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
private theorem unpermuteBACState_disjoint
    {O : BinaryAmbientCarrier.State U V W}
    {D : BinaryAmbientCarrier.State V U W}
    (h : Disjoint O (permuteBACState D)) :
    Disjoint (unpermuteBACState O) D := by
  refine Finset.disjoint_left.mpr ?_
  intro t htO htD
  obtain ⟨⟨s₁, s₂, s₃⟩, hsO, rfl⟩ := Finset.mem_image.mp htO
  apply Finset.disjoint_left.mp h hsO
  exact Finset.mem_image.mpr ⟨_, htD, rfl⟩

omit [Module F2 U] [Module F2 V] [Module F2 W] in
/-- Union with a background disjoint from both endpoints preserves an intrinsic all-mode move. -/
theorem allModeMove_union_left {D E O : BinaryAmbientCarrier.State U V W}
    (h : AllModeMove D E) (hOD : Disjoint O D) (hOE : Disjoint O E) :
    AllModeMove (O ∪ D) (O ∪ E) := by
  cases h with
  | abc hmove =>
      exact .abc (move_union_left hmove hOD hOE)
  | bca hmove hD hE =>
      refine .bca (move_union_left (O := unpermuteBCAState O) hmove ?_ ?_) ?_ ?_
      · exact unpermuteBCAState_disjoint (hD ▸ hOD)
      · exact unpermuteBCAState_disjoint (hE ▸ hOE)
      · calc
          O ∪ D = permuteBCAState (unpermuteBCAState O) ∪
              permuteBCAState _ :=
            congrArg₂ (· ∪ ·) (permuteBCAState_unpermuteBCAState O).symm hD
          _ = permuteBCAState (unpermuteBCAState O ∪ _) := by
            simpa only [permuteBCAState] using
              (Finset.image_union (f := permuteBCATerm)
                (unpermuteBCAState O) _).symm
      · calc
          O ∪ E = permuteBCAState (unpermuteBCAState O) ∪
              permuteBCAState _ :=
            congrArg₂ (· ∪ ·) (permuteBCAState_unpermuteBCAState O).symm hE
          _ = permuteBCAState (unpermuteBCAState O ∪ _) := by
            simpa only [permuteBCAState] using
              (Finset.image_union (f := permuteBCATerm)
                (unpermuteBCAState O) _).symm
  | cab hmove hD hE =>
      refine .cab (move_union_left (O := unpermuteCABState O) hmove ?_ ?_) ?_ ?_
      · exact unpermuteCABState_disjoint (hD ▸ hOD)
      · exact unpermuteCABState_disjoint (hE ▸ hOE)
      · calc
          O ∪ D = permuteCABState (unpermuteCABState O) ∪ permuteCABState _ :=
            congrArg₂ (· ∪ ·) (permuteCABState_unpermuteCABState O).symm hD
          _ = permuteCABState (unpermuteCABState O ∪ _) := by
            simpa only [permuteCABState] using
              (Finset.image_union (f := permuteCABTerm)
                (unpermuteCABState O) _).symm
      · calc
          O ∪ E = permuteCABState (unpermuteCABState O) ∪ permuteCABState _ :=
            congrArg₂ (· ∪ ·) (permuteCABState_unpermuteCABState O).symm hE
          _ = permuteCABState (unpermuteCABState O ∪ _) := by
            simpa only [permuteCABState] using
              (Finset.image_union (f := permuteCABTerm)
                (unpermuteCABState O) _).symm
  | acb hmove hD hE =>
      refine .acb (move_union_left (O := unpermuteACBState O) hmove ?_ ?_) ?_ ?_
      · exact unpermuteACBState_disjoint (hD ▸ hOD)
      · exact unpermuteACBState_disjoint (hE ▸ hOE)
      · calc
          O ∪ D = permuteACBState (unpermuteACBState O) ∪ permuteACBState _ :=
            congrArg₂ (· ∪ ·) (permuteACBState_unpermuteACBState O).symm hD
          _ = permuteACBState (unpermuteACBState O ∪ _) := by
            simpa only [permuteACBState] using
              (Finset.image_union (f := permuteACBTerm)
                (unpermuteACBState O) _).symm
      · calc
          O ∪ E = permuteACBState (unpermuteACBState O) ∪ permuteACBState _ :=
            congrArg₂ (· ∪ ·) (permuteACBState_unpermuteACBState O).symm hE
          _ = permuteACBState (unpermuteACBState O ∪ _) := by
            simpa only [permuteACBState] using
              (Finset.image_union (f := permuteACBTerm)
                (unpermuteACBState O) _).symm
  | cba hmove hD hE =>
      refine .cba (move_union_left (O := unpermuteCBAState O) hmove ?_ ?_) ?_ ?_
      · exact unpermuteCBAState_disjoint (hD ▸ hOD)
      · exact unpermuteCBAState_disjoint (hE ▸ hOE)
      · calc
          O ∪ D = permuteCBAState (unpermuteCBAState O) ∪ permuteCBAState _ :=
            congrArg₂ (· ∪ ·) (permuteCBAState_unpermuteCBAState O).symm hD
          _ = permuteCBAState (unpermuteCBAState O ∪ _) := by
            simpa only [permuteCBAState] using
              (Finset.image_union (f := permuteCBATerm)
                (unpermuteCBAState O) _).symm
      · calc
          O ∪ E = permuteCBAState (unpermuteCBAState O) ∪ permuteCBAState _ :=
            congrArg₂ (· ∪ ·) (permuteCBAState_unpermuteCBAState O).symm hE
          _ = permuteCBAState (unpermuteCBAState O ∪ _) := by
            simpa only [permuteCBAState] using
              (Finset.image_union (f := permuteCBATerm)
                (unpermuteCBAState O) _).symm
  | bac hmove hD hE =>
      refine .bac (move_union_left (O := unpermuteBACState O) hmove ?_ ?_) ?_ ?_
      · exact unpermuteBACState_disjoint (hD ▸ hOD)
      · exact unpermuteBACState_disjoint (hE ▸ hOE)
      · calc
          O ∪ D = permuteBACState (unpermuteBACState O) ∪ permuteBACState _ :=
            congrArg₂ (· ∪ ·) (permuteBACState_unpermuteBACState O).symm hD
          _ = permuteBACState (unpermuteBACState O ∪ _) := by
            simpa only [permuteBACState] using
              (Finset.image_union (f := permuteBACTerm)
                (unpermuteBACState O) _).symm
      · calc
          O ∪ E = permuteBACState (unpermuteBACState O) ∪ permuteBACState _ :=
            congrArg₂ (· ∪ ·) (permuteBACState_unpermuteBACState O).symm hE
          _ = permuteBACState (unpermuteBACState O ∪ _) := by
            simpa only [permuteBACState] using
              (Finset.image_union (f := permuteBACTerm)
                (unpermuteBACState O) _).symm

private theorem disjoint_mapState_of_disjoint_box {p : Profile}
    (f : CoordinateEmbedding p U V W)
    (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    (D : State p) : Disjoint O (mapState f D) := by
  apply Finset.disjoint_of_subset_right _ hO
  intro t ht
  obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp ht
  exact Finset.mem_image.mpr ⟨s, by simp [normalizedBox], rfl⟩

/-- Map a normalized path into ambient coordinates while adjoining one fixed disjoint background. -/
def mapPathWithBackground {p : Profile} (f : CoordinateEmbedding p U V W)
    (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p))) :
    {D E : State p} →
      MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E →
      MovePath (AllModeMove (U := U) (V := V) (W := W))
        (O ∪ mapState f D) (O ∪ mapState f E)
  | _, _, .singleton D => .singleton (O ∪ mapState f D)
  | _, _, .snoc path h =>
      .snoc (mapPathWithBackground f O hO path)
        (allModeMove_union_left (transportNormalizedAllModeMove f h)
          (disjoint_mapState_of_disjoint_box f O hO _)
          (disjoint_mapState_of_disjoint_box f O hO _))

/-- The background path has exactly the unioned images of the normalized vertices. -/
theorem mapPathWithBackground_vertices {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    {D E : State p}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E) :
    (mapPathWithBackground f O hO path).vertices =
      path.vertices.map (fun X => O ∪ mapState f X) := by
  induction path with
  | singleton =>
      simp only [mapPathWithBackground, MovePath.vertices, List.map_singleton]
  | snoc path h ih =>
      simp only [mapPathWithBackground, MovePath.vertices, ih,
        List.map_append, List.map_singleton]

/-- Characterize contextual vertices by their unique normalized source occurrence. -/
theorem mapPathWithBackground_pathVertex_iff {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    {D E : State p}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E)
    (Y : BinaryAmbientCarrier.State U V W) :
    PathVertex (mapPathWithBackground f O hO path) Y ↔
      ∃ X, PathVertex path X ∧ Y = O ∪ mapState f X := by
  rw [PathVertex, mapPathWithBackground_vertices]
  constructor
  · intro hY
    obtain ⟨X, hX, hXY⟩ := List.mem_map.mp hY
    exact ⟨X, hX, hXY.symm⟩
  · rintro ⟨X, hX, rfl⟩
    exact List.mem_map.mpr ⟨X, hX, rfl⟩

/-- Adjoining a fixed background preserves the exact edge count. -/
@[simp] theorem mapPathWithBackground_length {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    {D E : State p}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E) :
    (mapPathWithBackground f O hO path).length = path.length := by
  induction path with
  | singleton => simp only [mapPathWithBackground, MovePath.length]
  | snoc path h ih => simp only [mapPathWithBackground, MovePath.length, ih]

/-- The cardinality of a background-unioned coordinate image is additive. -/
theorem card_union_mapState {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p))) (D : State p) :
    (O ∪ mapState f D).card = O.card + D.card := by
  rw [Finset.card_union_of_disjoint
    (disjoint_mapState_of_disjoint_box f O hO D), mapState_card]

/-- The contextual ambient path altitude is exactly background size plus local altitude. -/
@[simp] theorem mapPathWithBackground_altitude {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    {D E : State p}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E) :
    (mapPathWithBackground f O hO path).altitude = O.card + path.altitude := by
  induction path with
  | singleton =>
      simp only [mapPathWithBackground, MovePath.altitude,
        card_union_mapState f O hO]
  | snoc path h ih =>
      simp only [mapPathWithBackground, MovePath.altitude, ih,
        card_union_mapState f O hO, max_add_add_left]

/-- Every vertex of a background-unioned mapped path has exactly that background outside the image box. -/
theorem mapPathWithBackground_outside {p : Profile}
    (f : CoordinateEmbedding p U V W) (O : BinaryAmbientCarrier.State U V W)
    (hO : Disjoint O (mapState f (normalizedBox p)))
    {D E : State p} {Y : BinaryAmbientCarrier.State U V W}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove p) D E)
    (hY : PathVertex (mapPathWithBackground f O hO path) Y) :
    Y \ mapState f (normalizedBox p) = O := by
  rw [PathVertex, mapPathWithBackground_vertices] at hY
  obtain ⟨X, hX, rfl⟩ := List.mem_map.mp hY
  ext t
  simp only [Finset.mem_sdiff, Finset.mem_union]
  have hOX : Disjoint O (mapState f X) :=
    disjoint_mapState_of_disjoint_box f O hO X
  have hXBox : mapState f X ⊆ mapState f (normalizedBox p) := by
    intro s hs
    obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hs
    exact Finset.mem_image.mpr ⟨x, by simp [normalizedBox], rfl⟩
  constructor
  · exact fun ht => ht.1.resolve_right
      (fun htX => ht.2 (hXBox htX))
  · intro htO
    exact ⟨Or.inl htO, fun htBox => Finset.disjoint_left.mp hO htO htBox⟩

/-- Specialize background path transport to the executable outside part of an arbitrary context. -/
def mapPathInContext {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    {D E : State P.profile} →
      MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E →
      MovePath (AllModeMove (U := U) (V := V) (W := W))
        (outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) D)
        (outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) E) :=
  mapPathWithBackground (exactSpanCoordinateEmbedding P) (outsideContext P C)
    (outsideContext_disjoint_localBox P C)

/-- A normalized left endpoint over the recovered local context reconstructs `C ∪ A`. -/
@[simp] theorem outsideContext_union_normalizedLeft
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P)
        (normalizeLocalContext P C ∪ normalizedLeft P) = C ∪ A := by
  rw [mapState_union, mapState_normalizedLeft]
  rw [← Finset.union_assoc, outsideContext_union_local]

/-- A normalized right endpoint over the recovered local context reconstructs `C ∪ B`. -/
@[simp] theorem outsideContext_union_normalizedRight
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W) :
    outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P)
        (normalizeLocalContext P C ∪ normalizedRight P) = C ∪ B := by
  rw [mapState_union, mapState_normalizedRight]
  rw [← Finset.union_assoc, outsideContext_union_local]

/-- Compile a local path over the recovered context into an ambient path with exact endpoints. -/
def mapPathInContextEndpoints {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedLeft P)
    (hE : E = normalizeLocalContext P C ∪ normalizedRight P) :
    MovePath (AllModeMove (U := U) (V := V) (W := W)) (C ∪ A) (C ∪ B) :=
  castMovePathEndpoints (mapPathInContext P C path)
    (by simp only [hD, outsideContext_union_normalizedLeft])
    (by simp only [hE, outsideContext_union_normalizedRight])

/-- Compile a reverse local path into an ambient path from `C ∪ B` to `C ∪ A`. -/
def mapPathInContextEndpointsReverse {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedRight P)
    (hE : E = normalizeLocalContext P C ∪ normalizedLeft P) :
    MovePath (AllModeMove (U := U) (V := V) (W := W)) (C ∪ B) (C ∪ A) :=
  castMovePathEndpoints (mapPathInContext P C path)
    (by simp only [hD, outsideContext_union_normalizedRight])
    (by simp only [hE, outsideContext_union_normalizedLeft])

/-- Context specialization preserves the exact list of mapped-and-unioned vertices. -/
theorem mapPathInContext_vertices {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E) :
    (mapPathInContext P C path).vertices = path.vertices.map
      (fun X => outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) X) :=
  mapPathWithBackground_vertices _ _ _ path

/-- Characterize exact-span contextual vertices by normalized source vertices. -/
theorem mapPathInContext_pathVertex_iff
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (Y : BinaryAmbientCarrier.State U V W) :
    PathVertex (mapPathInContext P C path) Y ↔
      ∃ X, PathVertex path X ∧
        Y = outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) X :=
  mapPathWithBackground_pathVertex_iff _ _ _ path Y

/-- Context specialization preserves path length exactly. -/
@[simp] theorem mapPathInContext_length {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E) :
    (mapPathInContext P C path).length = path.length :=
  mapPathWithBackground_length _ _ _ path

/-- Context specialization adds exactly the outside-context size to altitude. -/
@[simp] theorem mapPathInContext_altitude {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E) :
    (mapPathInContext P C path).altitude = (outsideContext P C).card + path.altitude :=
  mapPathWithBackground_altitude _ _ _ path

/-- Every contextual-path vertex has the prescribed outside part. -/
theorem mapPathInContext_outside {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile} {Y : BinaryAmbientCarrier.State U V W}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hY : PathVertex (mapPathInContext P C path) Y) :
    Y \ localBox P = outsideContext P C :=
  mapPathWithBackground_outside _ _ _ path hY

/-- Exact endpoint reindexing preserves the mapped vertex list of a forward contextual path. -/
theorem mapPathInContextEndpoints_vertices
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedLeft P)
    (hE : E = normalizeLocalContext P C ∪ normalizedRight P) :
    (mapPathInContextEndpoints P C path hD hE).vertices = path.vertices.map
      (fun X => outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) X) := by
  rw [mapPathInContextEndpoints, castMovePathEndpoints_vertices,
    mapPathInContext_vertices]

/-- The exact-endpoint forward contextual path preserves length. -/
@[simp] theorem mapPathInContextEndpoints_length
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedLeft P)
    (hE : E = normalizeLocalContext P C ∪ normalizedRight P) :
    (mapPathInContextEndpoints P C path hD hE).length = path.length := by
  rw [mapPathInContextEndpoints, castMovePathEndpoints_length,
    mapPathInContext_length]

/-- The exact-endpoint forward contextual path has exactly additive altitude. -/
@[simp] theorem mapPathInContextEndpoints_altitude
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedLeft P)
    (hE : E = normalizeLocalContext P C ∪ normalizedRight P) :
    (mapPathInContextEndpoints P C path hD hE).altitude =
      (outsideContext P C).card + path.altitude := by
  rw [mapPathInContextEndpoints, castMovePathEndpoints_altitude,
    mapPathInContext_altitude]

/-- Every forward exact-endpoint contextual vertex has the prescribed outside part. -/
theorem mapPathInContextEndpoints_outside
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile} {Y : BinaryAmbientCarrier.State U V W}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedLeft P)
    (hE : E = normalizeLocalContext P C ∪ normalizedRight P)
    (hY : PathVertex (mapPathInContextEndpoints P C path hD hE) Y) :
    Y \ localBox P = outsideContext P C := by
  apply mapPathInContext_outside P C path
  rw [PathVertex] at hY ⊢
  rw [mapPathInContextEndpoints_vertices P C path hD hE] at hY
  rw [mapPathInContext_vertices]
  exact hY

/-- Exact endpoint reindexing preserves the mapped vertex list of a reverse contextual path. -/
theorem mapPathInContextEndpointsReverse_vertices
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedRight P)
    (hE : E = normalizeLocalContext P C ∪ normalizedLeft P) :
    (mapPathInContextEndpointsReverse P C path hD hE).vertices = path.vertices.map
      (fun X => outsideContext P C ∪ mapState (exactSpanCoordinateEmbedding P) X) := by
  rw [mapPathInContextEndpointsReverse, castMovePathEndpoints_vertices,
    mapPathInContext_vertices]

/-- The exact-endpoint reverse contextual path preserves length. -/
@[simp] theorem mapPathInContextEndpointsReverse_length
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedRight P)
    (hE : E = normalizeLocalContext P C ∪ normalizedLeft P) :
    (mapPathInContextEndpointsReverse P C path hD hE).length = path.length := by
  rw [mapPathInContextEndpointsReverse, castMovePathEndpoints_length,
    mapPathInContext_length]

/-- The exact-endpoint reverse contextual path has exactly additive altitude. -/
@[simp] theorem mapPathInContextEndpointsReverse_altitude
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedRight P)
    (hE : E = normalizeLocalContext P C ∪ normalizedLeft P) :
    (mapPathInContextEndpointsReverse P C path hD hE).altitude =
      (outsideContext P C).card + path.altitude := by
  rw [mapPathInContextEndpointsReverse, castMovePathEndpoints_altitude,
    mapPathInContext_altitude]

/-- Every reverse exact-endpoint contextual vertex has the prescribed outside part. -/
theorem mapPathInContextEndpointsReverse_outside
    {A B : BinaryAmbientCarrier.State U V W}
    (P : ExactSpanPresentation A B) (C : BinaryAmbientCarrier.State U V W)
    {D E : State P.profile} {Y : BinaryAmbientCarrier.State U V W}
    (path : MovePath (@NormalizedBinaryAllModeMove.AllModeMove P.profile) D E)
    (hD : D = normalizeLocalContext P C ∪ normalizedRight P)
    (hE : E = normalizeLocalContext P C ∪ normalizedLeft P)
    (hY : PathVertex (mapPathInContextEndpointsReverse P C path hD hE) Y) :
    Y \ localBox P = outsideContext P C := by
  apply mapPathInContext_outside P C path
  rw [PathVertex] at hY ⊢
  rw [mapPathInContextEndpointsReverse_vertices P C path hD hE] at hY
  rw [mapPathInContext_vertices]
  exact hY

end BilinearComplexity.BinaryAmbientContextTransport
