import BilinearComplexity.BinaryAmbientTensorCoordinates
import BilinearComplexity.NormalizedBinaryRelationEnumeration
import BilinearComplexity.NormalizedBinaryFiveCircuitRows

set_option autoImplicit false

/-!
# Exact-span normalization of ambient binary endpoints

An `ExactSpanPresentation` is the executable boundary of ambient
normalization: its coordinate equivalences are supplied data, never selected
by a basis choice.  Endpoint terms are first restricted to the exact factor
spans generated by their union and are then normalized through that supplied
presentation.  Choice-based existence of presentations is confined to the
final proof-side construction.
-/

namespace BilinearComplexity.BinaryAmbientNormalization

open scoped TensorProduct BigOperators
open NormalizedBinaryCarrier (F2)

universe u v w

/-- The ambient term carrier: an ordered triple of nonzero vectors in the
three supplied factor spaces. -/
abbrev AmbientCarrier
    (U : Type u) (V : Type v) (W : Type w)
    [Zero U] [Zero V] [Zero W] :=
  BinaryAmbientCarrier.Carrier U V W

/-- A finite state of ambient nonzero-factor triples. -/
abbrev AmbientState
    (U : Type u) (V : Type v) (W : Type w)
    [Zero U] [Zero V] [Zero W] :=
  BinaryAmbientCarrier.State U V W

/-- Executable coordinates on the three exact factor spans generated jointly
by the ordered ambient endpoints. -/
structure ExactSpanPresentation
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (A B : AmbientState U V W) where
  profile : NormalizedBinaryCarrier.Profile
  firstCoordinates :
    BinaryAmbientTensorCoordinates.Coord profile.first ≃ₗ[F2]
      BinaryAmbientCarrier.firstSpan (A ∪ B)
  secondCoordinates :
    BinaryAmbientTensorCoordinates.Coord profile.second ≃ₗ[F2]
      BinaryAmbientCarrier.secondSpan (A ∪ B)
  thirdCoordinates :
    BinaryAmbientTensorCoordinates.Coord profile.third ≃ₗ[F2]
      BinaryAmbientCarrier.thirdSpan (A ∪ B)

/-- The first profile coordinate is forced by the first exact span. -/
theorem ExactSpanPresentation.first_eq_finrank
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    P.profile.first = Module.finrank F2 (BinaryAmbientCarrier.firstSpan (A ∪ B)) := by
  rw [← P.firstCoordinates.finrank_eq]
  exact (Module.finrank_fin_fun (R := F2) (n := P.profile.first)).symm

/-- The second profile coordinate is forced by the second exact span. -/
theorem ExactSpanPresentation.second_eq_finrank
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    P.profile.second = Module.finrank F2 (BinaryAmbientCarrier.secondSpan (A ∪ B)) := by
  rw [← P.secondCoordinates.finrank_eq]
  exact (Module.finrank_fin_fun (R := F2) (n := P.profile.second)).symm

/-- The third profile coordinate is forced by the third exact span. -/
theorem ExactSpanPresentation.third_eq_finrank
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    P.profile.third = Module.finrank F2 (BinaryAmbientCarrier.thirdSpan (A ∪ B)) := by
  rw [← P.thirdCoordinates.finrank_eq]
  exact (Module.finrank_fin_fun (R := F2) (n := P.profile.third)).symm

/-- Any two supplied presentations of the same endpoints have the same forced
profile, independently of their coordinate bases. -/
theorem ExactSpanPresentation.profile_eq
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P Q : ExactSpanPresentation A B) :
    P.profile = Q.profile := by
  have hfirst : P.profile.first = Q.profile.first := by
    rw [P.first_eq_finrank, Q.first_eq_finrank]
  have hsecond : P.profile.second = Q.profile.second := by
    rw [P.second_eq_finrank, Q.second_eq_finrank]
  have hthird : P.profile.third = Q.profile.third := by
    rw [P.third_eq_finrank, Q.third_eq_finrank]
  cases hp : P.profile
  cases hq : Q.profile
  simp_all

/-- Restrict one term known to lie in a state to that state's three exact
factor spans. -/
def restrictTerm
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) (t : AmbientCarrier U V W) (ht : t ∈ K) :
    AmbientCarrier (BinaryAmbientCarrier.firstSpan K)
      (BinaryAmbientCarrier.secondSpan K)
      (BinaryAmbientCarrier.thirdSpan K) :=
  (⟨⟨t.1.1, BinaryAmbientCarrier.first_mem_firstSpan ht⟩,
      fun h => t.1.2 (congrArg Subtype.val h)⟩,
    ⟨⟨t.2.1.1, BinaryAmbientCarrier.second_mem_secondSpan ht⟩,
      fun h => t.2.1.2 (congrArg Subtype.val h)⟩,
    ⟨⟨t.2.2.1, BinaryAmbientCarrier.third_mem_thirdSpan ht⟩,
      fun h => t.2.2.2 (congrArg Subtype.val h)⟩)

/-- Forget exact-span subtype information from one restricted term. -/
def includeTerm
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    AmbientCarrier (BinaryAmbientCarrier.firstSpan K)
        (BinaryAmbientCarrier.secondSpan K)
        (BinaryAmbientCarrier.thirdSpan K) →
      AmbientCarrier U V W :=
  fun t =>
    (⟨t.1.1.1, fun h => t.1.2 (Subtype.ext h)⟩,
      ⟨t.2.1.1.1, fun h => t.2.1.2 (Subtype.ext h)⟩,
      ⟨t.2.2.1.1, fun h => t.2.2.2 (Subtype.ext h)⟩)

/-- Restricting a term to the exact spans generated by `K` and then
forgetting the subtype witnesses recovers the original ambient term. -/
@[simp] theorem includeTerm_restrictTerm
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) (t : AmbientCarrier U V W) (ht : t ∈ K) :
    includeTerm K (restrictTerm K t ht) = t := by
  rfl

/-- Forgetting exact-span subtype information is injective. -/
theorem includeTerm_injective
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) : Function.Injective (includeTerm K) := by
  intro s t hst
  apply Prod.ext
  · apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun q : AmbientCarrier U V W => q.1.1) hst
  · apply Prod.ext
    · apply Subtype.ext
      apply Subtype.ext
      exact congrArg (fun q : AmbientCarrier U V W => q.2.1.1) hst
    · apply Subtype.ext
      apply Subtype.ext
      exact congrArg (fun q : AmbientCarrier U V W => q.2.2.1) hst

/-- The embedding of exact-span terms into the original ambient carrier. -/
def includeTermEmbedding
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    AmbientCarrier (BinaryAmbientCarrier.firstSpan K)
        (BinaryAmbientCarrier.secondSpan K)
        (BinaryAmbientCarrier.thirdSpan K) ↪ AmbientCarrier U V W :=
  ⟨includeTerm K, includeTerm_injective K⟩

/-- Restrict a substate of `K` termwise to the exact spans generated by `K`. -/
def restrictState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D : AmbientState U V W) (hDK : D ⊆ K) :
    AmbientState (BinaryAmbientCarrier.firstSpan K)
      (BinaryAmbientCarrier.secondSpan K)
      (BinaryAmbientCarrier.thirdSpan K) :=
  D.attach.map
    { toFun := fun t => restrictTerm K t.1 (hDK t.2)
      inj' := by
        intro s t hst
        apply Subtype.ext
        simpa using congrArg (includeTerm K) hst }

/-- Include a finite exact-span state into the original ambient state. -/
def includeState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W)
    (D : AmbientState (BinaryAmbientCarrier.firstSpan K)
      (BinaryAmbientCarrier.secondSpan K)
      (BinaryAmbientCarrier.thirdSpan K)) : AmbientState U V W :=
  D.map (includeTermEmbedding K)

/-- Restriction followed by inclusion reconstructs the original substate. -/
@[simp] theorem includeState_restrictState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D : AmbientState U V W) (hDK : D ⊆ K) :
    includeState K (restrictState K D hDK) = D := by
  rw [includeState, restrictState, Finset.map_map]
  convert Finset.attach_map_val using 1
  ext t
  rfl

/-- Restriction preserves finite-state cardinality. -/
@[simp] theorem restrictState_card
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D : AmbientState U V W) (hDK : D ⊆ K) :
    (restrictState K D hDK).card = D.card := by
  simp [restrictState]

/-- Restriction of two substates preserves and reflects disjointness. -/
@[simp] theorem restrictState_disjoint_iff
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D E : AmbientState U V W) (hDK : D ⊆ K) (hEK : E ⊆ K) :
    Disjoint (restrictState K D hDK) (restrictState K E hEK) ↔
      Disjoint D E := by
  rw [← Finset.disjoint_map (includeTermEmbedding K)]
  change Disjoint (includeState K (restrictState K D hDK))
    (includeState K (restrictState K E hEK)) ↔ Disjoint D E
  rw [includeState_restrictState, includeState_restrictState]

/-- A constructive decidable equality on restricted terms, inherited through
the injective inclusion into the supplied ambient carrier. -/
def restrictedCarrierDecidableEq
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    DecidableEq (AmbientCarrier (BinaryAmbientCarrier.firstSpan K)
      (BinaryAmbientCarrier.secondSpan K)
      (BinaryAmbientCarrier.thirdSpan K)) :=
  fun s t => decidable_of_iff (includeTerm K s = includeTerm K t)
    (includeTerm_injective K).eq_iff

/-- Normalize an arbitrary substate of the endpoint union through a supplied
exact-span presentation. -/
def normalizeSubstate
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    NormalizedBinaryCarrier.State P.profile :=
  BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
    P.secondCoordinates P.thirdCoordinates
    (restrictState (A ∪ B) D hD)

/-- The normalized left endpoint, preserving the ordered endpoint slot. -/
def normalizedLeft
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    NormalizedBinaryCarrier.State P.profile :=
  normalizeSubstate P A (Finset.subset_union_left)

/-- The normalized right endpoint, preserving the ordered endpoint slot. -/
def normalizedRight
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    NormalizedBinaryCarrier.State P.profile :=
  normalizeSubstate P B (Finset.subset_union_right)

/-- Ordered normalized endpoints derived from an exact-span presentation. -/
def normalizedEndpoints
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    NormalizedBinaryFiniteAction.RelationEndpoints P.profile where
  left := normalizedLeft P
  right := normalizedRight P

/-- Restriction commutes with unions of substates. -/
theorem restrictState_union
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D E : AmbientState U V W) (hD : D ⊆ K) (hE : E ⊆ K) :
    letI := restrictedCarrierDecidableEq K
    restrictState K D hD ∪ restrictState K E hE =
      restrictState K (D ∪ E) (Finset.union_subset hD hE) := by
  letI := restrictedCarrierDecidableEq K
  apply Finset.map_injective (includeTermEmbedding K)
  rw [Finset.map_union]
  change includeState K (restrictState K D hD) ∪
      includeState K (restrictState K E hE) =
    includeState K (restrictState K (D ∪ E) (Finset.union_subset hD hE))
  rw [includeState_restrictState, includeState_restrictState,
    includeState_restrictState]

/-- Normalization preserves the endpoint union. -/
theorem normalizedLeft_union_normalizedRight
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    normalizedLeft P ∪ normalizedRight P =
      normalizeSubstate P (A ∪ B) (by rfl) := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  change
    BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates
        (restrictState (A ∪ B) A Finset.subset_union_left) ∪
      BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates
        (restrictState (A ∪ B) B Finset.subset_union_right) =
    BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
      P.secondCoordinates P.thirdCoordinates
      (restrictState (A ∪ B) (A ∪ B) (by rfl))
  unfold BinaryAmbientTensorCoordinates.normalizeState
  rw [← Finset.map_union]
  congr 1
  simpa only using restrictState_union (A ∪ B) A B
    Finset.subset_union_left Finset.subset_union_right

/-- Restricting a state to its own exact spans has full first subtype span. -/
theorem firstSpan_restrictState_self
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    letI := restrictedCarrierDecidableEq K
    BinaryAmbientCarrier.firstSpan (restrictState K K (by rfl)) = ⊤ := by
  letI := restrictedCarrierDecidableEq K
  apply top_unique
  rintro ⟨x, hx⟩ -
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨t, ht, rfl⟩
      have htk : t ∈ K := by simpa using ht
      apply Submodule.subset_span
      refine ⟨restrictTerm K t htk, ?_, rfl⟩
      unfold restrictState
      apply Finset.mem_map.mpr
      refine ⟨⟨t, htk⟩, Finset.mem_attach _ _, ?_⟩
      apply includeTerm_injective K
      change includeTerm K (restrictTerm K t htk) = t
      exact includeTerm_restrictTerm K t htk
  | zero => exact Submodule.zero_mem _
  | add x y hx hy ihx ihy => exact Submodule.add_mem _ ihx ihy
  | smul a x hx ihx => exact Submodule.smul_mem _ a ihx

/-- Restricting a state to its own exact spans has full second subtype span. -/
theorem secondSpan_restrictState_self
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    letI := restrictedCarrierDecidableEq K
    BinaryAmbientCarrier.secondSpan (restrictState K K (by rfl)) = ⊤ := by
  letI := restrictedCarrierDecidableEq K
  apply top_unique
  rintro ⟨x, hx⟩ -
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨t, ht, rfl⟩
      have htk : t ∈ K := by simpa using ht
      apply Submodule.subset_span
      refine ⟨restrictTerm K t htk, ?_, rfl⟩
      unfold restrictState
      apply Finset.mem_map.mpr
      refine ⟨⟨t, htk⟩, Finset.mem_attach _ _, ?_⟩
      apply includeTerm_injective K
      change includeTerm K (restrictTerm K t htk) = t
      exact includeTerm_restrictTerm K t htk
  | zero => exact Submodule.zero_mem _
  | add x y hx hy ihx ihy => exact Submodule.add_mem _ ihx ihy
  | smul a x hx ihx => exact Submodule.smul_mem _ a ihx

/-- Restricting a state to its own exact spans has full third subtype span. -/
theorem thirdSpan_restrictState_self
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W) :
    letI := restrictedCarrierDecidableEq K
    BinaryAmbientCarrier.thirdSpan (restrictState K K (by rfl)) = ⊤ := by
  letI := restrictedCarrierDecidableEq K
  apply top_unique
  rintro ⟨x, hx⟩ -
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨t, ht, rfl⟩
      have htk : t ∈ K := by simpa using ht
      apply Submodule.subset_span
      refine ⟨restrictTerm K t htk, ?_, rfl⟩
      unfold restrictState
      apply Finset.mem_map.mpr
      refine ⟨⟨t, htk⟩, Finset.mem_attach _ _, ?_⟩
      apply includeTerm_injective K
      change includeTerm K (restrictTerm K t htk) = t
      exact includeTerm_restrictTerm K t htk
  | zero => exact Submodule.zero_mem _
  | add x y hx hy ihx ihy => exact Submodule.add_mem _ ihx ihy
  | smul a x hx ihx => exact Submodule.smul_mem _ a ihx

/-- First factor spans transform by the inverse supplied coordinate map. -/
theorem firstFactorSpan_normalizeState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {a b c : ℕ}
    (eU : BinaryAmbientTensorCoordinates.Coord a ≃ₗ[F2] U)
    (eV : BinaryAmbientTensorCoordinates.Coord b ≃ₗ[F2] V)
    (eW : BinaryAmbientTensorCoordinates.Coord c ≃ₗ[F2] W)
    (D : AmbientState U V W) :
    NormalizedBinaryFiveCircuitCertificate.firstFactorSpan
        (BinaryAmbientTensorCoordinates.normalizeState eU eV eW D) =
      Submodule.map eU.symm.toLinearMap (BinaryAmbientCarrier.firstSpan D) := by
  unfold NormalizedBinaryFiveCircuitCertificate.firstFactorSpan
    BinaryAmbientCarrier.firstSpan BinaryAmbientTensorCoordinates.normalizeState
  rw [Finset.coe_image, Finset.coe_map, Set.image_image]
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W =>
        (BinaryAmbientTensorCoordinates.normalizeTerm eU eV eW t).1.1) ''
          (D : Set _)) = _
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W => eU.symm t.1.1) '' (D : Set _)) = _
  rw [← Set.image_image, LinearMap.map_span]
  rfl

/-- Second factor spans transform by the inverse supplied coordinate map. -/
theorem secondFactorSpan_normalizeState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {a b c : ℕ}
    (eU : BinaryAmbientTensorCoordinates.Coord a ≃ₗ[F2] U)
    (eV : BinaryAmbientTensorCoordinates.Coord b ≃ₗ[F2] V)
    (eW : BinaryAmbientTensorCoordinates.Coord c ≃ₗ[F2] W)
    (D : AmbientState U V W) :
    NormalizedBinaryFiveCircuitCertificate.secondFactorSpan
        (BinaryAmbientTensorCoordinates.normalizeState eU eV eW D) =
      Submodule.map eV.symm.toLinearMap (BinaryAmbientCarrier.secondSpan D) := by
  unfold NormalizedBinaryFiveCircuitCertificate.secondFactorSpan
    BinaryAmbientCarrier.secondSpan BinaryAmbientTensorCoordinates.normalizeState
  rw [Finset.coe_image, Finset.coe_map, Set.image_image]
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W =>
        (BinaryAmbientTensorCoordinates.normalizeTerm eU eV eW t).2.1.1) ''
          (D : Set _)) = _
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W => eV.symm t.2.1.1) '' (D : Set _)) = _
  rw [← Set.image_image, LinearMap.map_span]
  rfl

/-- Third factor spans transform by the inverse supplied coordinate map. -/
theorem thirdFactorSpan_normalizeState
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {a b c : ℕ}
    (eU : BinaryAmbientTensorCoordinates.Coord a ≃ₗ[F2] U)
    (eV : BinaryAmbientTensorCoordinates.Coord b ≃ₗ[F2] V)
    (eW : BinaryAmbientTensorCoordinates.Coord c ≃ₗ[F2] W)
    (D : AmbientState U V W) :
    NormalizedBinaryFiveCircuitCertificate.thirdFactorSpan
        (BinaryAmbientTensorCoordinates.normalizeState eU eV eW D) =
      Submodule.map eW.symm.toLinearMap (BinaryAmbientCarrier.thirdSpan D) := by
  unfold NormalizedBinaryFiveCircuitCertificate.thirdFactorSpan
    BinaryAmbientCarrier.thirdSpan BinaryAmbientTensorCoordinates.normalizeState
  rw [Finset.coe_image, Finset.coe_map, Set.image_image]
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W =>
        (BinaryAmbientTensorCoordinates.normalizeTerm eU eV eW t).2.2.1) ''
          (D : Set _)) = _
  change Submodule.span F2
      ((fun t : AmbientCarrier U V W => eW.symm t.2.2.1) '' (D : Set _)) = _
  rw [← Set.image_image, LinearMap.map_span]
  rfl

/-- The first normalized substate span is the inverse-coordinate image of
the restricted ambient span. -/
theorem firstFactorSpan_normalizeSubstate
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    letI := restrictedCarrierDecidableEq (A ∪ B)
    NormalizedBinaryFiveCircuitCertificate.firstFactorSpan
        (normalizeSubstate P D hD) =
      Submodule.map P.firstCoordinates.symm.toLinearMap
        (BinaryAmbientCarrier.firstSpan (restrictState (A ∪ B) D hD)) := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  change NormalizedBinaryFiveCircuitCertificate.firstFactorSpan
      (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD)) = _
  exact firstFactorSpan_normalizeState _ _ _ _

/-- The second normalized substate span is the inverse-coordinate image of
the restricted ambient span. -/
theorem secondFactorSpan_normalizeSubstate
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    letI := restrictedCarrierDecidableEq (A ∪ B)
    NormalizedBinaryFiveCircuitCertificate.secondFactorSpan
        (normalizeSubstate P D hD) =
      Submodule.map P.secondCoordinates.symm.toLinearMap
        (BinaryAmbientCarrier.secondSpan (restrictState (A ∪ B) D hD)) := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  change NormalizedBinaryFiveCircuitCertificate.secondFactorSpan
      (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD)) = _
  exact secondFactorSpan_normalizeState _ _ _ _

/-- The third normalized substate span is the inverse-coordinate image of
the restricted ambient span. -/
theorem thirdFactorSpan_normalizeSubstate
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    letI := restrictedCarrierDecidableEq (A ∪ B)
    NormalizedBinaryFiveCircuitCertificate.thirdFactorSpan
        (normalizeSubstate P D hD) =
      Submodule.map P.thirdCoordinates.symm.toLinearMap
        (BinaryAmbientCarrier.thirdSpan (restrictState (A ∪ B) D hD)) := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  change NormalizedBinaryFiveCircuitCertificate.thirdFactorSpan
      (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD)) = _
  exact thirdFactorSpan_normalizeState _ _ _ _

/-- Normalizing the endpoint union through its exact-span presentation produces
full spans in all three coordinate factors. -/
theorem normalizedEndpoints_hasExactFactorProfile
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    NormalizedBinaryFiveCircuitCertificate.HasExactFactorProfile
      (normalizedLeft P ∪ normalizedRight P) := by
  rw [normalizedLeft_union_normalizedRight]
  letI := restrictedCarrierDecidableEq (A ∪ B)
  refine ⟨?_, ?_, ?_⟩
  · rw [firstFactorSpan_normalizeSubstate]
    apply top_unique
    intro x hx
    refine ⟨P.firstCoordinates x, ?_, P.firstCoordinates.symm_apply_apply x⟩
    rw [firstSpan_restrictState_self]
    exact Submodule.mem_top
  · rw [secondFactorSpan_normalizeSubstate]
    apply top_unique
    intro x hx
    refine ⟨P.secondCoordinates x, ?_, P.secondCoordinates.symm_apply_apply x⟩
    rw [secondSpan_restrictState_self]
    exact Submodule.mem_top
  · rw [thirdFactorSpan_normalizeSubstate]
    apply top_unique
    intro x hx
    refine ⟨P.thirdCoordinates x, ?_, P.thirdCoordinates.symm_apply_apply x⟩
    rw [thirdSpan_restrictState_self]
    exact Submodule.mem_top

/-- Normalizing and then denormalizing a substate reconstructs its exact-span
restriction, and inclusion reconstructs the original ambient state. -/
theorem normalizeSubstate_reconstruction
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    includeState (A ∪ B)
      (BinaryAmbientTensorCoordinates.denormalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (normalizeSubstate P D hD)) = D := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  rw [normalizeSubstate,
    BinaryAmbientTensorCoordinates.denormalizeState_normalizeState]
  exact includeState_restrictState (A ∪ B) D hD

/-- Denormalizing and including the normalized left endpoint recovers the
original left endpoint in its ordered slot. -/
@[simp] theorem normalizedLeft_reconstruction
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    includeState (A ∪ B)
      (BinaryAmbientTensorCoordinates.denormalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (normalizedLeft P)) = A :=
  normalizeSubstate_reconstruction P A Finset.subset_union_left

/-- Denormalizing and including the normalized right endpoint recovers the
original right endpoint in its ordered slot. -/
@[simp] theorem normalizedRight_reconstruction
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B) :
    includeState (A ∪ B)
      (BinaryAmbientTensorCoordinates.denormalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (normalizedRight P)) = B :=
  normalizeSubstate_reconstruction P B Finset.subset_union_right

/-- Normalization preserves endpoint-substate cardinality. -/
@[simp] theorem normalizeSubstate_card
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D : AmbientState U V W) (hD : D ⊆ A ∪ B) :
    (normalizeSubstate P D hD).card = D.card := by
  change (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
    P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD)).card = D.card
  calc
    _ = (restrictState (A ∪ B) D hD).card :=
      BinaryAmbientTensorCoordinates.normalizeState_card _ _ _ _
    _ = D.card := restrictState_card _ _ _

/-- Normalization preserves and reflects disjointness of two endpoint
substates. -/
@[simp] theorem normalizeSubstate_disjoint_iff
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D E : AmbientState U V W) (hD : D ⊆ A ∪ B) (hE : E ⊆ A ∪ B) :
    Disjoint (normalizeSubstate P D hD) (normalizeSubstate P E hE) ↔
      Disjoint D E := by
  change Disjoint
      (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD))
      (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
        P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) E hE)) ↔
    Disjoint D E
  exact (BinaryAmbientTensorCoordinates.normalizeState_disjoint_iff
    P.firstCoordinates P.secondCoordinates P.thirdCoordinates
    (restrictState (A ∪ B) D hD) (restrictState (A ∪ B) E hE)).trans
      (restrictState_disjoint_iff (A ∪ B) D E hD hE)

/-- Evaluation of an exact-span term is covariant under inclusion into the
original nested ambient tensor product. -/
@[simp] theorem exactSpanTensorMap_tensorEvaluation
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K : AmbientState U V W)
    (t : AmbientCarrier (BinaryAmbientCarrier.firstSpan K)
      (BinaryAmbientCarrier.secondSpan K)
      (BinaryAmbientCarrier.thirdSpan K)) :
    BinaryAmbientTensorCoordinates.exactSpanTensorMap
        (BinaryAmbientCarrier.firstSpan K)
        (BinaryAmbientCarrier.secondSpan K)
        (BinaryAmbientCarrier.thirdSpan K)
        (BinaryAmbientCarrier.tensorEvaluation t) =
      BinaryAmbientCarrier.tensorEvaluation (includeTerm K t) := by
  simp [BinaryAmbientTensorCoordinates.exactSpanTensorMap,
    BinaryAmbientCarrier.tensorEvaluation, includeTerm]

/-- Evaluation of a restricted state is covariant under exact-span tensor
inclusion and reconstructs the original ambient state evaluation. -/
theorem exactSpanTensorMap_restrictStateEvaluation
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (K D : AmbientState U V W) (hD : D ⊆ K) :
    letI := restrictedCarrierDecidableEq K
    BinaryAmbientTensorCoordinates.exactSpanTensorMap
        (BinaryAmbientCarrier.firstSpan K)
        (BinaryAmbientCarrier.secondSpan K)
        (BinaryAmbientCarrier.thirdSpan K)
        (BinaryAmbientCarrier.stateEvaluation (restrictState K D hD)) =
      BinaryAmbientCarrier.stateEvaluation D := by
  let R := restrictState K D hD
  calc
    _ = BinaryAmbientCarrier.stateEvaluation (includeState K R) := by
      simp [R, BinaryAmbientCarrier.stateEvaluation, includeState,
        BinaryAmbientTensorCoordinates.exactSpanTensorMap,
        includeTermEmbedding, includeTerm]
    _ = BinaryAmbientCarrier.stateEvaluation D :=
      congrArg BinaryAmbientCarrier.stateEvaluation
        (includeState_restrictState K D hD)

/-- Ambient equality of substate evaluations is equivalent to equality of
the normalized coordinate evaluations supplied by the presentation. -/
theorem normalized_stateEvaluation_eq_iff
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (D E : AmbientState U V W) (hD : D ⊆ A ∪ B) (hE : E ⊆ A ∪ B) :
    NormalizedBinaryCarrier.stateEvaluation (normalizeSubstate P D hD) =
        NormalizedBinaryCarrier.stateEvaluation (normalizeSubstate P E hE) ↔
      BinaryAmbientCarrier.stateEvaluation D =
        BinaryAmbientCarrier.stateEvaluation E := by
  letI := restrictedCarrierDecidableEq (A ∪ B)
  change
    NormalizedBinaryCarrier.stateEvaluation
        (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
          P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) D hD)) =
      NormalizedBinaryCarrier.stateEvaluation
        (BinaryAmbientTensorCoordinates.normalizeState P.firstCoordinates
          P.secondCoordinates P.thirdCoordinates (restrictState (A ∪ B) E hE)) ↔
    BinaryAmbientCarrier.stateEvaluation D = BinaryAmbientCarrier.stateEvaluation E
  rw [BinaryAmbientTensorCoordinates.normalized_stateEvaluation_eq_iff]
  constructor
  · intro h
    have hm := congrArg
      (BinaryAmbientTensorCoordinates.exactSpanTensorMap
        (BinaryAmbientCarrier.firstSpan (A ∪ B))
        (BinaryAmbientCarrier.secondSpan (A ∪ B))
        (BinaryAmbientCarrier.thirdSpan (A ∪ B))) h
    simpa only [exactSpanTensorMap_restrictStateEvaluation] using hm
  · intro h
    apply BinaryAmbientTensorCoordinates.exactSpanTensorMap_injective
      (BinaryAmbientCarrier.firstSpan (A ∪ B))
      (BinaryAmbientCarrier.secondSpan (A ∪ B))
      (BinaryAmbientCarrier.thirdSpan (A ∪ B))
    simpa only [exactSpanTensorMap_restrictStateEvaluation] using h

/-- An ordered ambient binary relation with sizes two and three, disjoint
endpoints, and equal evaluations normalizes to an exact relation in the profile
forced by its defining factor spans. -/
def normalizedExactRelation
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (hA : A.card = 2) (hB : B.card = 3) (hDisjoint : Disjoint A B)
    (hEvaluation : BinaryAmbientCarrier.stateEvaluation A =
      BinaryAmbientCarrier.stateEvaluation B) :
    NormalizedBinaryRelationEnumeration.ExactRelation P.profile := by
  refine ⟨normalizedEndpoints P, ?_⟩
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · change (normalizeSubstate P A Finset.subset_union_left).card = 2
    rw [normalizeSubstate_card, hA]
  · change (normalizeSubstate P B Finset.subset_union_right).card = 3
    rw [normalizeSubstate_card, hB]
  · change Disjoint
      (normalizeSubstate P A Finset.subset_union_left)
      (normalizeSubstate P B Finset.subset_union_right)
    exact (normalizeSubstate_disjoint_iff P A B
      Finset.subset_union_left Finset.subset_union_right).2 hDisjoint
  · change NormalizedBinaryCarrier.stateEvaluation
        (normalizeSubstate P A Finset.subset_union_left) =
      NormalizedBinaryCarrier.stateEvaluation
        (normalizeSubstate P B Finset.subset_union_right)
    exact (normalized_stateEvaluation_eq_iff P A B
      Finset.subset_union_left Finset.subset_union_right).2 hEvaluation
  · exact normalizedEndpoints_hasExactFactorProfile P

/-- The exact-relation constructor retains the ordered normalized endpoints
as its data component. -/
@[simp] theorem normalizedExactRelation_value
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    {A B : AmbientState U V W} (P : ExactSpanPresentation A B)
    (hA : A.card = 2) (hB : B.card = 3) (hDisjoint : Disjoint A B)
    (hEvaluation : BinaryAmbientCarrier.stateEvaluation A =
      BinaryAmbientCarrier.stateEvaluation B) :
    (normalizedExactRelation P hA hB hDisjoint hEvaluation).val =
      normalizedEndpoints P := rfl

/-- Proof-side existence of exact-span coordinates in finite-dimensional
ambient modules.  This theorem is not an executable compiler. -/
theorem exists_exactSpanPresentation
    {U : Type u} {V : Type v} {W : Type w}
    [AddCommGroup U] [AddCommGroup V] [AddCommGroup W]
    [Module F2 U] [Module F2 V] [Module F2 W]
    [FiniteDimensional F2 U] [FiniteDimensional F2 V] [FiniteDimensional F2 W]
    [DecidableEq (AmbientCarrier U V W)]
    (A B : AmbientState U V W) : Nonempty (ExactSpanPresentation A B) := by
  let p : NormalizedBinaryCarrier.Profile :=
    ⟨Module.finrank F2 (BinaryAmbientCarrier.firstSpan (A ∪ B)),
      Module.finrank F2 (BinaryAmbientCarrier.secondSpan (A ∪ B)),
      Module.finrank F2 (BinaryAmbientCarrier.thirdSpan (A ∪ B))⟩
  exact ⟨{
    profile := p
    firstCoordinates :=
      BinaryAmbientTensorCoordinates.exactSpanCoordinates
        (BinaryAmbientCarrier.firstSpan (A ∪ B))
    secondCoordinates :=
      BinaryAmbientTensorCoordinates.exactSpanCoordinates
        (BinaryAmbientCarrier.secondSpan (A ∪ B))
    thirdCoordinates :=
      BinaryAmbientTensorCoordinates.exactSpanCoordinates
        (BinaryAmbientCarrier.thirdSpan (A ∪ B)) }⟩

/-! ## Choice-free zero-dimensional ground checks -/

private def subsingletonLinearEquiv
    {M N : Type} [AddCommMonoid M] [AddCommMonoid N]
    [Module F2 M] [Module F2 N] [Subsingleton M] [Subsingleton N] :
    M ≃ₗ[F2] N where
  toFun _ := 0
  invFun _ := 0
  left_inv _ := Subsingleton.elim _ _
  right_inv _ := Subsingleton.elim _ _
  map_add' _ _ := Subsingleton.elim _ _
  map_smul' _ _ := Subsingleton.elim _ _

private abbrev ZeroCoord := NormalizedBinaryCarrier.CoordinateVector 0

private instance : DecidableEq (AmbientCarrier ZeroCoord ZeroCoord ZeroCoord) :=
  inferInstance

/-- A fully explicit supplied presentation of the three zero-dimensional exact
spans.  Unlike `exists_exactSpanPresentation`, this ground datum uses no basis
selection or choice. -/
private def emptyExactSpanPresentation :
    ExactSpanPresentation
      (∅ : AmbientState ZeroCoord ZeroCoord ZeroCoord)
      (∅ : AmbientState ZeroCoord ZeroCoord ZeroCoord) where
  profile := ⟨0, 0, 0⟩
  firstCoordinates := subsingletonLinearEquiv
  secondCoordinates := subsingletonLinearEquiv
  thirdCoordinates := subsingletonLinearEquiv

example : emptyExactSpanPresentation.profile = ⟨0, 0, 0⟩ := rfl

example : normalizedLeft emptyExactSpanPresentation = ∅ := rfl

example : normalizedRight emptyExactSpanPresentation = ∅ := rfl

example : (normalizedEndpoints emptyExactSpanPresentation).left = ∅ := rfl

example : (normalizedEndpoints emptyExactSpanPresentation).right = ∅ := rfl

example :
    NormalizedBinaryFiveCircuitCertificate.HasExactFactorProfile
      (normalizedLeft emptyExactSpanPresentation ∪
        normalizedRight emptyExactSpanPresentation) :=
  normalizedEndpoints_hasExactFactorProfile emptyExactSpanPresentation

open NormalizedBinaryFiveCircuitRows

/-- The concrete `221-01` endpoints have equal evaluations in the abstract
ambient tensor product, as reflected through identity coordinates. -/
theorem row22101_ambient_evaluation_eq :
    BinaryAmbientCarrier.stateEvaluation row22101Start =
      BinaryAmbientCarrier.stateEvaluation row22101Finish := by
  apply (BinaryAmbientTensorCoordinates.normalized_stateEvaluation_eq_iff
    (LinearEquiv.refl F2 (BinaryAmbientTensorCoordinates.Coord 2))
    (LinearEquiv.refl F2 (BinaryAmbientTensorCoordinates.Coord 2))
    (LinearEquiv.refl F2 (BinaryAmbientTensorCoordinates.Coord 1))
    row22101Start row22101Finish).mp
  exact (NormalizedBinaryAllModeMove.allModeMovePath_preserves_evaluation
    row22101Certificate.forward).symm

/-- A nonempty joint model of every hypothesis consumed by exact-span
normalization: the actual `221-01` circuit endpoints normalize to an exact
relation with the ordered endpoint data prescribed by the presentation. -/
theorem row22101_normalizedExactRelation_regression :
    ∃ P : ExactSpanPresentation row22101Start row22101Finish,
      let R := normalizedExactRelation P row22101Certificate.card_left
        row22101Certificate.card_right row22101Certificate.disjoint
        row22101_ambient_evaluation_eq
      R.val.left = normalizedLeft P ∧
        R.val.right = normalizedRight P ∧
        NormalizedBinaryRelationEnumeration.IsExactRelation R.val := by
  obtain ⟨P⟩ := exists_exactSpanPresentation row22101Start row22101Finish
  refine ⟨P, ?_⟩
  exact ⟨rfl, rfl, (normalizedExactRelation P row22101Certificate.card_left
    row22101Certificate.card_right row22101Certificate.disjoint
    row22101_ambient_evaluation_eq).property⟩

#print axioms normalizedEndpoints_hasExactFactorProfile
#print axioms normalizedExactRelation
#print axioms row22101_normalizedExactRelation_regression

end BilinearComplexity.BinaryAmbientNormalization
