import BilinearComplexity.FieldRankOne
import Mathlib.Algebra.CharP.Two
import Mathlib.Data.Finset.Card
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

set_option autoImplicit false

namespace BilinearComplexity
namespace FieldContextual

open FieldRankOne

variable {k : Type*} {a b c : ℕ}

/-- Exact local replacement data for finite sets of actual atoms. Endpoint disjointness rules out
silently retaining a source atom as an output atom. -/
structure Replacement [Field k] (A B : State k a b c) : Prop where
  /-- Local source and target atom sets are disjoint. -/
  endpoints_disjoint : Disjoint A B
  /-- The two local finite sets have exactly equal tensor evaluation. -/
  eval_eq : stateEval A = stateEval B

/-- A fixed outside context is compatible with both endpoints exactly when it has no atom
collision with either endpoint. Sharing factor rays is allowed. -/
def ContextCompatible [Field k] (C A B : State k a b c) : Prop :=
  Disjoint C A ∧ Disjoint C B

/-- The empty context is compatible with empty endpoints, so the contextual hypotheses are
jointly satisfiable. -/
example [Field k] : ContextCompatible (∅ : State k a b c) ∅ ∅ := by
  simp [ContextCompatible]

/-- Classically compute the union of two atom states; equality remains evaluated equality. -/
noncomputable def stateUnion [Field k] (S T : State k a b c) : State k a b c := by
  classical
  exact S ∪ T

/-- Classically erase every atom of a second state from a first state. -/
noncomputable def stateDifference [Field k] (S T : State k a b c) : State k a b c := by
  classical
  exact S \ T

/-- Empty-state union and difference provide ground checks for the classical proof-side set
operations. -/
example [Field k] :
    stateUnion (∅ : State k a b c) ∅ = ∅ ∧
      stateDifference (∅ : State k a b c) ∅ = ∅ := by
  simp [stateUnion, stateDifference]

/-- Evaluation of a disjoint finite-set union is the sum of the two evaluations. -/
theorem stateEval_union [Field k] {S T : State k a b c} (hST : Disjoint S T) :
    stateEval (stateUnion S T) = stateEval S + stateEval T := by
  classical
  unfold stateEval stateUnion
  rw [Finset.sum_union hST]

/-- Reversing an exact replacement preserves all semantic obligations. -/
theorem Replacement.symm [Field k] {A B : State k a b c} (h : Replacement A B) :
    Replacement B A :=
  ⟨h.endpoints_disjoint.symm, h.eval_eq.symm⟩

/-- Two exact replacements compose when the new endpoints are themselves disjoint. -/
theorem Replacement.trans [Field k] {A B D : State k a b c}
    (hAB : Replacement A B) (hBD : Replacement B D) (hAD : Disjoint A D) :
    Replacement A D :=
  ⟨hAD, hAB.eval_eq.trans hBD.eval_eq⟩

/-- A context-compatible exact replacement preserves the whole ambient state's evaluation. -/
theorem contextual_eval [Field k] {C A B : State k a b c}
    (hlocal : Replacement A B) (hcontext : ContextCompatible C A B) :
    stateEval (stateUnion C A) = stateEval (stateUnion C B) := by
  rw [stateEval_union hcontext.1, stateEval_union hcontext.2, hlocal.eval_eq]

/-- Removing a disjoint local endpoint from its union with the context restores exactly the
outside context, rather than merely restoring its evaluation. -/
theorem erase_endpoint_restores_context [Field k] {C A : State k a b c}
    (hCA : Disjoint C A) : stateDifference (stateUnion C A) A = C := by
  classical
  unfold stateDifference stateUnion
  ext x
  constructor
  · intro hx
    simp only [Finset.mem_sdiff, Finset.mem_union] at hx
    rcases hx.1 with hxC | hxA
    · exact hxC
    · exact (hx.2 hxA).elim
  · intro hxC
    have hxA : x ∉ A := Finset.disjoint_left.mp hCA hxC
    simp only [Finset.mem_sdiff, Finset.mem_union]
    exact ⟨Or.inl hxC, hxA⟩

/-- Two context-compatible local steps with the same middle endpoint compose semantically in
the fixed context; no claim about shortest paths is made. -/
theorem contextual_eval_trans [Field k] {C A B D : State k a b c}
    (hAB : Replacement A B) (hBD : Replacement B D)
    (hCAB : ContextCompatible C A B) (hCBD : ContextCompatible C B D) :
    stateEval (stateUnion C A) = stateEval (stateUnion C D) :=
  (contextual_eval hAB hCAB).trans (contextual_eval hBD hCBD)

/-- The singleton native state containing one actual atom. -/
noncomputable def singletonState [Field k] (x : Atom k a b c) : State k a b c := by
  classical
  exact {x}

/-- The finite-set state generated by two actual atoms. A separate inequality hypothesis is
needed whenever it is semantically required to contain two terms. -/
noncomputable def pairState [Field k] (x y : Atom k a b c) : State k a b c := by
  classical
  exact {x, y}

/-- The finite-set state generated by three actual atoms. Distinctness remains an explicit
obligation for any theorem asserting cardinality or a three-term evaluation. -/
noncomputable def tripleState [Field k] (x y z : Atom k a b c) : State k a b c := by
  classical
  exact {x, y, z}

/-- A singleton state evaluates to its atom. -/
@[simp] theorem stateEval_singletonState [Field k] (x : Atom k a b c) :
    stateEval (singletonState x) = x.val := by
  classical
  simp [singletonState, stateEval]

/-- A collision-free two-atom state evaluates to the displayed sum. -/
theorem stateEval_pairState [Field k] (x y : Atom k a b c) (hxy : x ≠ y) :
    stateEval (pairState x y) = x.val + y.val := by
  classical
  simp [pairState, stateEval, hxy]

/-- A pairwise collision-free three-atom state evaluates to the displayed sum. -/
theorem stateEval_tripleState [Field k] (x y z : Atom k a b c)
    (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z) :
    stateEval (tripleState x y z) = x.val + y.val + z.val := by
  classical
  simp [tripleState, stateEval, hxy, hxz, hyz, add_assoc]

/-- A pairwise collision-free triple state has exactly three atoms. -/
theorem tripleState_card [Field k] (x y z : Atom k a b c)
    (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z) :
    (tripleState x y z).card = 3 := by
  classical
  simp [tripleState, hxy, hxz, hyz]

/-- Package a one-to-two algebraic identity as an exact Split replacement. Atom types enforce
nonzero outputs, while the three inequalities are precisely output distinctness and cross-freshness. -/
theorem splitReplacement [Field k] (source left right : Atom k a b c)
    (hsource_left : source ≠ left) (hsource_right : source ≠ right)
    (hleft_right : left ≠ right) (heval : source.val = left.val + right.val) :
    Replacement (singletonState source) (pairState left right) := by
  classical
  refine ⟨?_, ?_⟩
  · simp [singletonState, pairState, hsource_left, hsource_right]
  · rw [stateEval_singletonState, stateEval_pairState left right hleft_right]
    exact heval

/-- Package a two-to-one algebraic identity as a directed Reduction replacement. -/
theorem reductionReplacement [Field k] (left right target : Atom k a b c)
    (hleft_right : left ≠ right) (hleft_target : left ≠ target)
    (hright_target : right ≠ target) (heval : left.val + right.val = target.val) :
    Replacement (pairState left right) (singletonState target) := by
  exact (splitReplacement target left right hleft_target.symm hright_target.symm
    hleft_right heval.symm).symm

/-- Package a two-to-two shear identity as an exact Flip replacement. The six inequalities
explicitly rule out source duplication, output duplication, and every source/output collision. -/
theorem flipReplacement [Field k] (source₁ source₂ target₁ target₂ : Atom k a b c)
    (hsource : source₁ ≠ source₂) (htarget : target₁ ≠ target₂)
    (h11 : source₁ ≠ target₁) (h12 : source₁ ≠ target₂)
    (h21 : source₂ ≠ target₁) (h22 : source₂ ≠ target₂)
    (heval : source₁.val + source₂.val = target₁.val + target₂.val) :
    Replacement (pairState source₁ source₂) (pairState target₁ target₂) := by
  classical
  refine ⟨?_, ?_⟩
  · apply Finset.disjoint_left.mpr
    intro x hxsource hxtarget
    have hs : x = source₁ ∨ x = source₂ := by
      simpa only [pairState, Finset.mem_insert, Finset.mem_singleton] using hxsource
    have ht : x = target₁ ∨ x = target₂ := by
      simpa only [pairState, Finset.mem_insert, Finset.mem_singleton] using hxtarget
    rcases hs with hs | hs <;> rcases ht with ht | ht
    · exact h11 (hs.symm.trans ht)
    · exact h12 (hs.symm.trans ht)
    · exact h21 (hs.symm.trans ht)
    · exact h22 (hs.symm.trans ht)
  · rw [stateEval_pairState source₁ source₂ hsource,
      stateEval_pairState target₁ target₂ htarget]
    exact heval

/-- Package a collision-free two-to-three tensor equality as an exact finite-set replacement. -/
theorem pairTripleReplacement [Field k]
    (source₁ source₂ target₁ target₂ target₃ : Atom k a b c)
    (hsource : source₁ ≠ source₂)
    (h12 : target₁ ≠ target₂) (h13 : target₁ ≠ target₃) (h23 : target₂ ≠ target₃)
    (hdisjoint : Disjoint (pairState source₁ source₂) (tripleState target₁ target₂ target₃))
    (heval : source₁.val + source₂.val = target₁.val + target₂.val + target₃.val) :
    Replacement (pairState source₁ source₂) (tripleState target₁ target₂ target₃) := by
  refine ⟨hdisjoint, ?_⟩
  rw [stateEval_pairState source₁ source₂ hsource,
    stateEval_tripleState target₁ target₂ target₃ h12 h13 h23]
  exact heval

/-- Exact Split packaging records a one-atom source and a two-atom target. -/
theorem splitReplacement_card [Field k] (source left right : Atom k a b c)
    (hleft_right : left ≠ right) :
    (singletonState source).card = 1 ∧ (pairState left right).card = 2 := by
  classical
  simp [singletonState, pairState, hleft_right]

section AlgebraicLaws

variable [Field k]

/-- Splitting the first factor is an exact one-to-two tensor equation. -/
theorem splitFirst_eval (q : k) (u₁ u₂ : Fin a → k) (v : Fin b → k)
    (w : Fin c → k) :
    evalFactors q (u₁ + u₂) v w =
      evalFactors q u₁ v w + evalFactors q u₂ v w := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.add_apply]
  ring

/-- Splitting the second factor is an exact one-to-two tensor equation. -/
theorem splitSecond_eval (q : k) (u : Fin a → k) (v₁ v₂ : Fin b → k)
    (w : Fin c → k) :
    evalFactors q u (v₁ + v₂) w =
      evalFactors q u v₁ w + evalFactors q u v₂ w := by
  funext i j l
  simp only [evalFactors, Pi.add_apply]
  ring

/-- Splitting the third factor is an exact one-to-two tensor equation. -/
theorem splitThird_eval (q : k) (u : Fin a → k) (v : Fin b → k)
    (w₁ w₂ : Fin c → k) :
    evalFactors q u v (w₁ + w₂) =
      evalFactors q u v w₁ + evalFactors q u v w₂ := by
  funext i j l
  simp only [evalFactors, Pi.add_apply]
  ring

/-- Shared-last-two-factor reduction is the exact reverse of coefficient-aware first splitting. -/
theorem reduceFirst_eval (q₁ q₂ : k) (u₁ u₂ : Fin a → k) (v : Fin b → k)
    (w : Fin c → k) :
    evalFactors q₁ u₁ v w + evalFactors q₂ u₂ v w =
      evalFactors 1 (q₁ • u₁ + q₂ • u₂) v w := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, smul_eq_mul, one_mul]
  ring

/-- Shared-first-and-third-factor reduction combines coefficients in the second factor. -/
theorem reduceSecond_eval (q₁ q₂ : k) (u : Fin a → k) (v₁ v₂ : Fin b → k)
    (w : Fin c → k) :
    evalFactors q₁ u v₁ w + evalFactors q₂ u v₂ w =
      evalFactors 1 u (q₁ • v₁ + q₂ • v₂) w := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, smul_eq_mul, one_mul]
  ring

/-- Shared-first-two-factor reduction combines coefficients in the third factor. -/
theorem reduceThird_eval (q₁ q₂ : k) (u : Fin a → k) (v : Fin b → k)
    (w₁ w₂ : Fin c → k) :
    evalFactors q₁ u v w₁ + evalFactors q₂ u v w₂ =
      evalFactors 1 u v (q₁ • w₁ + q₂ • w₂) := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, smul_eq_mul, one_mul]
  ring

/-- A coefficient-aware shear for two terms sharing the third factor is exact over every field.
Subtraction is genuine subtraction; no characteristic-two rule is used. -/
theorem flipThird_eval (q₁ q₂ : k) (u₁ u₂ : Fin a → k) (v₁ v₂ : Fin b → k)
    (w : Fin c → k) :
    evalFactors q₁ u₁ v₁ w + evalFactors q₂ u₂ v₂ w =
      evalFactors 1 (q₁ • u₁ + q₂ • u₂) v₁ w +
        evalFactors 1 (q₂ • u₂) (v₂ - v₁) w := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, Pi.sub_apply, smul_eq_mul, one_mul]
  ring

/-- The corresponding coefficient-aware shear for two terms sharing the second factor is exact. -/
theorem flipSecond_eval (q₁ q₂ : k) (u₁ u₂ : Fin a → k) (v : Fin b → k)
    (w₁ w₂ : Fin c → k) :
    evalFactors q₁ u₁ v w₁ + evalFactors q₂ u₂ v w₂ =
      evalFactors 1 (q₁ • u₁ + q₂ • u₂) v w₁ +
        evalFactors 1 (q₂ • u₂) v (w₂ - w₁) := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, Pi.sub_apply, smul_eq_mul, one_mul]
  ring

/-- The corresponding coefficient-aware shear for two terms sharing the first factor is exact. -/
theorem flipFirst_eval (q₁ q₂ : k) (u : Fin a → k) (v₁ v₂ : Fin b → k)
    (w₁ w₂ : Fin c → k) :
    evalFactors q₁ u v₁ w₁ + evalFactors q₂ u v₂ w₂ =
      evalFactors 1 u (q₁ • v₁ + q₂ • v₂) w₁ +
        evalFactors 1 u (q₂ • v₂) (w₂ - w₁) := by
  funext i j l
  simp only [evalFactors, Pi.add_apply, Pi.smul_apply, Pi.sub_apply, smul_eq_mul, one_mul]
  ring

/-- In characteristic two the subtraction in a flip specializes to addition; this theorem
isolates the hypothesis used by binary implementations. -/
theorem sub_eq_add_of_charTwo [CharP k 2] (x y : k) : x - y = x + y := by
  rw [sub_eq_add_neg, CharTwo.neg_eq]

end AlgebraicLaws

namespace F3Profile221

/-- The three-element field used by the concrete profile-221 fixture. -/
abbrev F3 := ZMod 3

/-- The first standard vector in `F3²`. -/
def e0 : Fin 2 → F3 := ![1, 0]

/-- The second standard vector in `F3²`. -/
def e1 : Fin 2 → F3 := ![0, 1]

/-- The nonzero vector spanning the one-dimensional third factor. -/
def unit : Fin 1 → F3 := ![1]

/-- The profile-221 atom tensor `A=e0⊗e0⊗1`. -/
def A : Tensor F3 2 2 1 := evalFactors 1 e0 e0 unit

/-- The profile-221 atom tensor `B=e1⊗e1⊗1`. -/
def B : Tensor F3 2 2 1 := evalFactors 1 e1 e1 unit

/-- The profile-221 atom tensor `C=e0⊗e1⊗1`. -/
def C : Tensor F3 2 2 1 := evalFactors 1 e0 e1 unit

/-- The profile-221 atom tensor `D=e1⊗e0⊗1`. -/
def D : Tensor F3 2 2 1 := evalFactors 1 e1 e0 unit

/-- The profile-221 atom tensor `J=(e0+e1)⊗(e0+e1)⊗1`. -/
def J : Tensor F3 2 2 1 := evalFactors 1 (e0 + e1) (e0 + e1) unit

/-- Construct an actual profile-221 atom from a nonzero coefficient and two nonzero factors. -/
def fixtureAtom (q : F3) (u v : Fin 2 → F3)
    (hq : q ≠ 0) (hu : u ≠ 0) (hv : v ≠ 0) : Atom F3 2 2 1 :=
  Atom.ofRep {
    coeff := q
    first := u
    second := v
    third := unit
    coeff_ne_zero := hq
    first_ne_zero := hu
    second_ne_zero := hv
    third_ne_zero := by decide }

/-- The fixture atom constructor retains the intended coefficient-bearing tensor. -/
@[simp] theorem fixtureAtom_val (q : F3) (u v : Fin 2 → F3)
    (hq : q ≠ 0) (hu : u ≠ 0) (hv : v ≠ 0) :
    (fixtureAtom q u v hq hu hv).val = evalFactors q u v unit := rfl

/-- The actual semantic atom with tensor value `A`. -/
def atomA : Atom F3 2 2 1 := fixtureAtom 1 e0 e0 (by decide) (by decide) (by decide)

/-- The actual semantic atom with tensor value `B`. -/
def atomB : Atom F3 2 2 1 := fixtureAtom 1 e1 e1 (by decide) (by decide) (by decide)

/-- The actual semantic atom with tensor value `2C`. -/
def atom2C : Atom F3 2 2 1 := fixtureAtom 2 e0 e1 (by decide) (by decide) (by decide)

/-- The actual semantic atom with tensor value `2D`. -/
def atom2D : Atom F3 2 2 1 := fixtureAtom 2 e1 e0 (by decide) (by decide) (by decide)

/-- The actual semantic atom with tensor value `J`. -/
def atomJ : Atom F3 2 2 1 :=
  fixtureAtom 1 (e0 + e1) (e0 + e1) (by decide) (by decide) (by decide)

/-- The unscaled `C` atom supplies a nonempty outside context disjoint from both endpoints. -/
def atomC : Atom F3 2 2 1 := fixtureAtom 1 e0 e1 (by decide) (by decide) (by decide)

/-- The five concrete atoms expose exactly the coefficient-bearing endpoint tensors. -/
theorem concrete_atom_values :
    atomA.val = A ∧ atomB.val = B ∧ atom2C.val = (2 : F3) • C ∧
      atom2D.val = (2 : F3) • D ∧ atomJ.val = J := by
  repeat' apply And.intro
  all_goals
    funext i j l
    fin_cases i <;> fin_cases j <;> fin_cases l <;> decide

/-- The five actual semantic atoms are pairwise distinct. -/
theorem concrete_atoms_pairwise :
    List.Pairwise (· ≠ ·) [atomA, atomB, atom2C, atom2D, atomJ] := by
  have hAB : atomA ≠ atomB := Atom.ne_of_val_ne (by decide)
  have hAC : atomA ≠ atom2C := Atom.ne_of_val_ne (by decide)
  have hAD : atomA ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hAJ : atomA ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hBC : atomB ≠ atom2C := Atom.ne_of_val_ne (by decide)
  have hBD : atomB ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hBJ : atomB ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hCD : atom2C ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hCJ : atom2C ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hDJ : atom2D ≠ atomJ := Atom.ne_of_val_ne (by decide)
  simp only [List.pairwise_cons, List.mem_cons, List.not_mem_nil, or_false]
  exact ⟨fun x hx => hx.elim (fun h => by simpa only [h] using hAB)
      (fun hx => hx.elim (fun h => by simpa only [h] using hAC)
        (fun hx => hx.elim (fun h => by simpa only [h] using hAD)
          (fun h => by simpa only [h] using hAJ))),
    fun x hx => hx.elim (fun h => by simpa only [h] using hBC)
      (fun hx => hx.elim (fun h => by simpa only [h] using hBD)
        (fun h => by simpa only [h] using hBJ)),
    fun x hx => hx.elim (fun h => by simpa only [h] using hCD)
      (fun h => by simpa only [h] using hCJ),
    fun x hx => by simpa only [hx] using hDJ,
    fun _ h => h.elim, by simp⟩

/-- The two-atom source endpoint, computed with decidable F3 coordinate equality. -/
def A2 : State F3 2 2 1 := {atomA, atomB}

/-- The three-atom target endpoint, computed with decidable F3 coordinate equality. -/
def B3 : State F3 2 2 1 := {atom2C, atom2D, atomJ}

/-- The computed source agrees extensionally with the general proof-side pair constructor. -/
theorem A2_eq_pairState : A2 = pairState atomA atomB := by
  classical
  ext x
  simp only [A2, pairState, Finset.mem_insert, Finset.mem_singleton]

/-- The computed target agrees extensionally with the general proof-side triple constructor. -/
theorem B3_eq_tripleState : B3 = tripleState atom2C atom2D atomJ := by
  classical
  ext x
  simp only [B3, tripleState, Finset.mem_insert, Finset.mem_singleton]

/-- The source atoms have the expected actual tensor values. -/
theorem source_atom_values : atomA.val = A ∧ atomB.val = B :=
  ⟨concrete_atom_values.1, concrete_atom_values.2.1⟩

/-- The target atoms have the expected actual scaled tensor values. -/
theorem target_atom_values : atom2C.val = (2 : F3) • C ∧
    atom2D.val = (2 : F3) • D ∧ atomJ.val = J :=
  ⟨concrete_atom_values.2.2.1, concrete_atom_values.2.2.2.1,
    concrete_atom_values.2.2.2.2⟩

/-- A computed nonempty outside context consisting of the actual unscaled `C` atom. -/
def fixtureContext : State F3 2 2 1 := {atomC}

#eval (A2.card, B3.card, fixtureContext.card)

/-- The computed fixture context is genuinely nonempty. -/
theorem fixtureContext_nonempty : fixtureContext.Nonempty := by
  exact ⟨atomC, by simp [fixtureContext]⟩

/-- The computed context agrees extensionally with the general proof-side singleton constructor. -/
theorem fixtureContext_eq_singletonState : fixtureContext = singletonState atomC := by
  classical
  ext x
  simp only [fixtureContext, singletonState, Finset.mem_singleton]

/-- The genuine ternary two-versus-three equality is `A+B=2C+2D+J`. -/
theorem two_three_eq : A + B = (2 : F3) • C + (2 : F3) • D + J := by
  funext i j l
  fin_cases i <;> fin_cases j <;> fin_cases l <;> decide

/-- On the five actual endpoint atoms `(A,B,2C,2D,J)`, the signed dependence
coefficients are `(1,1,2,2,2)`. -/
theorem signed_dependence :
    A + B + (2 : F3) • ((2 : F3) • C) + (2 : F3) • ((2 : F3) • D) +
      (2 : F3) • J = 0 := by
  funext i j l
  fin_cases i <;> fin_cases j <;> fin_cases l <;> decide

/-- The five unscaled pure tensors are all nonzero and pairwise distinct. -/
theorem nonzero_and_pairwise_distinct :
    A ≠ 0 ∧ B ≠ 0 ∧ C ≠ 0 ∧ D ≠ 0 ∧ J ≠ 0 ∧
      List.Pairwise (· ≠ ·) [A, B, C, D, J] := by
  decide

/-- The right endpoint consists of the actual scaled atoms `2C`, `2D`, and `J`, all nonzero
and pairwise distinct; coefficients are not represented as duplicate occurrences. -/
theorem scaled_endpoint_nonzero_distinct :
    (2 : F3) • C ≠ 0 ∧ (2 : F3) • D ≠ 0 ∧ J ≠ 0 ∧
      List.Pairwise (· ≠ ·) [(2 : F3) • C, (2 : F3) • D, J] := by
  decide

/-- The concrete source and target are disjoint actual-atom finite sets. -/
theorem endpoints_disjoint : Disjoint A2 B3 := by
  classical
  have hAC : atomA ≠ atom2C := Atom.ne_of_val_ne (by decide)
  have hAD : atomA ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hAJ : atomA ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hBC : atomB ≠ atom2C := Atom.ne_of_val_ne (by decide)
  have hBD : atomB ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hBJ : atomB ≠ atomJ := Atom.ne_of_val_ne (by decide)
  rw [A2_eq_pairState, B3_eq_tripleState]
  simp [pairState, tripleState, hAC.symm, hAD.symm, hAJ.symm,
    hBC.symm, hBD.symm, hBJ.symm]

/-- The concrete endpoint states have respectively two and three actual atoms. -/
theorem endpoint_cards : A2.card = 2 ∧ B3.card = 3 := by
  have hAB : atomA ≠ atomB := Atom.ne_of_val_ne (by decide)
  have hCD : atom2C ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hCJ : atom2C ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hDJ : atom2D ≠ atomJ := Atom.ne_of_val_ne (by decide)
  constructor
  · rw [A2_eq_pairState]
    classical
    simp [pairState, hAB]
  · rw [B3_eq_tripleState]
    exact tripleState_card atom2C atom2D atomJ hCD hCJ hDJ

/-- The concrete finite source and target states have exactly equal tensor evaluation. -/
theorem endpoint_eval_eq : stateEval A2 = stateEval B3 := by
  have hAB : atomA ≠ atomB := Atom.ne_of_val_ne (by decide)
  have hCD : atom2C ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hCJ : atom2C ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hDJ : atom2D ≠ atomJ := Atom.ne_of_val_ne (by decide)
  rw [A2_eq_pairState, B3_eq_tripleState,
    stateEval_pairState atomA atomB hAB,
    stateEval_tripleState atom2C atom2D atomJ hCD hCJ hDJ,
    source_atom_values.1, source_atom_values.2,
    target_atom_values.1, target_atom_values.2.1, target_atom_values.2.2]
  exact two_three_eq

/-- The displayed F3 profile-221 equality is a genuine exact replacement of finite atom sets. -/
theorem concreteReplacement : Replacement A2 B3 := by
  have hAB : atomA ≠ atomB := Atom.ne_of_val_ne (by decide)
  have hCD : atom2C ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hCJ : atom2C ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have hDJ : atom2D ≠ atomJ := Atom.ne_of_val_ne (by decide)
  have heval : atomA.val + atomB.val = atom2C.val + atom2D.val + atomJ.val := by
    rw [source_atom_values.1, source_atom_values.2,
      target_atom_values.1, target_atom_values.2.1, target_atom_values.2.2]
    exact two_three_eq
  have hdisjoint :
      Disjoint (pairState atomA atomB) (tripleState atom2C atom2D atomJ) := by
    rw [← A2_eq_pairState, ← B3_eq_tripleState]
    exact endpoints_disjoint
  rw [A2_eq_pairState, B3_eq_tripleState]
  exact pairTripleReplacement atomA atomB atom2C atom2D atomJ hAB hCD hCJ hDJ
    hdisjoint heval

/-- The unscaled `C` atom gives a nonempty context compatible with both concrete endpoints. -/
theorem fixtureContext_compatible : ContextCompatible fixtureContext A2 B3 := by
  classical
  have hCA : atomC ≠ atomA := Atom.ne_of_val_ne (by decide)
  have hCB : atomC ≠ atomB := Atom.ne_of_val_ne (by decide)
  have hCC : atomC ≠ atom2C := Atom.ne_of_val_ne (by decide)
  have hCD : atomC ≠ atom2D := Atom.ne_of_val_ne (by decide)
  have hCJ : atomC ≠ atomJ := Atom.ne_of_val_ne (by decide)
  rw [fixtureContext_eq_singletonState, A2_eq_pairState, B3_eq_tripleState]
  simp [ContextCompatible, singletonState, pairState, tripleState, hCA, hCB, hCC, hCD, hCJ]

/-- Replacing inside the nonempty fixture context preserves evaluation and erasing either endpoint
restores exactly the same context. -/
theorem contextual_fixture_satisfiable :
    stateEval (stateUnion fixtureContext A2) = stateEval (stateUnion fixtureContext B3) ∧
      stateDifference (stateUnion fixtureContext A2) A2 = fixtureContext ∧
      stateDifference (stateUnion fixtureContext B3) B3 = fixtureContext := by
  refine ⟨contextual_eval concreteReplacement fixtureContext_compatible, ?_, ?_⟩
  · exact erase_endpoint_restores_context fixtureContext_compatible.1
  · exact erase_endpoint_restores_context fixtureContext_compatible.2

/-- The ordered family of the five actual endpoint tensors `A`, `B`, `2C`, `2D`, and `J`. -/
def fixtureFamily : Fin 5 → Tensor F3 2 2 1 :=
  ![A, B, (2 : F3) • C, (2 : F3) • D, J]

/-- The signed coefficients `(1,1,2,2,2)` of the fixture dependence over F3. -/
def fixtureSigned : Fin 5 → F3 := ![1, 1, 2, 2, 2]

example : fixtureFamily 0 = A := rfl
example : fixtureFamily 2 = (2 : F3) • C := rfl
example : fixtureSigned 0 = 1 := rfl
example : fixtureSigned 4 = 2 := rfl

/-- Every linear relation among the five fixture tensors is a scalar multiple of the displayed
signed relation. -/
theorem relation_eq_smul_signed (q : Fin 5 → F3)
    (h : ∑ i, q i • fixtureFamily i = 0) : q = q 0 • fixtureSigned := by
  have h00 := congrFun (congrFun (congrFun h 0) 0) 0
  have h01 := congrFun (congrFun (congrFun h 0) 1) 0
  have h10 := congrFun (congrFun (congrFun h 1) 0) 0
  have h11 := congrFun (congrFun (congrFun h 1) 1) 0
  simp only [fixtureFamily, A, e0, unit, B, e1, C, D, J, Matrix.add_cons,
    Matrix.head_cons, add_zero, Matrix.tail_cons, zero_add, Matrix.empty_add_empty,
    Fin.isValue, Finset.sum_apply, Pi.smul_apply, Matrix.cons_val', Matrix.cons_val_fin_one,
    FieldRankOne.evalFactors, Matrix.cons_val_zero, mul_one, mul_zero, smul_eq_mul,
    Fin.sum_univ_succ, Matrix.cons_val_succ, Fin.succ_zero_eq_one, Fin.succ_one_eq_two,
    Fin.reduceSucc, Finset.univ_unique, Fin.default_eq_zero, Finset.sum_singleton,
    Pi.zero_apply, Matrix.cons_val_one] at h00 h01 h10 h11
  have htwo : (2 : F3) = -1 := by decide
  rw [htwo] at h01 h10
  funext i
  fin_cases i
  · simp [fixtureSigned]
  · simp only [Fin.mk_one, Fin.isValue, fixtureSigned, Pi.smul_apply, Matrix.cons_val_one,
      Matrix.cons_val_zero, smul_eq_mul, mul_one]
    linear_combination h11 - h00
  · simp only [Fin.reduceFinMk, Fin.isValue, fixtureSigned, htwo, Pi.smul_apply,
      Matrix.cons_val, smul_eq_mul, mul_neg, mul_one]
    linear_combination -h01 + h00
  · simp only [Fin.reduceFinMk, Fin.isValue, fixtureSigned, htwo, Pi.smul_apply,
      Matrix.cons_val, smul_eq_mul, mul_neg, mul_one]
    linear_combination -h10 + h00
  · simp only [Fin.reduceFinMk, Fin.isValue, fixtureSigned, htwo, Pi.smul_apply,
      Matrix.cons_val, smul_eq_mul, mul_neg, mul_one]
    linear_combination h00

/-- The displayed signed coefficient vector is a nonzero relation among the fixture tensors. -/
theorem fixtureSigned_relation : ∑ i, fixtureSigned i • fixtureFamily i = 0 := by
  simp only [fixtureSigned, fixtureFamily, Fin.sum_univ_succ, Fin.isValue,
    Matrix.cons_val_zero, one_smul, Matrix.cons_val_succ, Finset.univ_unique,
    Fin.default_eq_zero, Matrix.cons_val_fin_one, Finset.sum_const, Finset.card_singleton]
  simpa only [add_assoc] using signed_dependence

/-- The five actual endpoint tensors form a circuit: they admit a nonzero relation, but every
relation with a vanishing coefficient is the zero relation. -/
theorem fixture_is_circuit :
    (∃ q : Fin 5 → F3, q ≠ 0 ∧ ∑ i, q i • fixtureFamily i = 0) ∧
      ∀ q : Fin 5 → F3, (∑ i, q i • fixtureFamily i = 0) →
        (∃ i, q i = 0) → q = 0 := by
  constructor
  · exact ⟨fixtureSigned, by
      intro hzero
      have hone := congrFun hzero 0
      norm_num [fixtureSigned] at hone, fixtureSigned_relation⟩
  · intro q hrel hvanish
    have hq := relation_eq_smul_signed q hrel
    rcases hvanish with ⟨i, hi⟩
    have hi' := congrFun hq i
    rw [hi] at hi'
    have hsigned : fixtureSigned i ≠ 0 := by
      fin_cases i <;> decide
    have hq0 : q 0 = 0 := by
      rw [Pi.smul_apply, smul_eq_mul] at hi'
      exact (mul_eq_zero.mp hi'.symm).resolve_right hsigned
    rw [hq, hq0, zero_smul]

/-- Flatten the five fixture tensors in row-major `(i,j)` order for executable auditing. -/
def fixtureCoordinates : List (List F3) :=
  [A, B, C, D, J].map fun T => [T 0 0 0, T 0 1 0, T 1 0 0, T 1 1 0]

#eval fixtureCoordinates

example : fixtureCoordinates =
    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [1, 1, 1, 1]] := by
  decide

end F3Profile221

#check @splitFirst_eval
#check @flipThird_eval
#check @contextual_eval
#check @splitReplacement
#check @reductionReplacement
#check @flipReplacement
#check @pairTripleReplacement
#check @F3Profile221.concreteReplacement
#check @F3Profile221.contextual_fixture_satisfiable
#check @F3Profile221.fixtureContext_nonempty
#check @F3Profile221.relation_eq_smul_signed
#check @F3Profile221.fixture_is_circuit
#check @F3Profile221.two_three_eq
#print axioms contextual_eval_trans
#print axioms F3Profile221.concreteReplacement
#print axioms F3Profile221.contextual_fixture_satisfiable
#print axioms F3Profile221.relation_eq_smul_signed
#print axioms F3Profile221.fixture_is_circuit
#print axioms F3Profile221.nonzero_and_pairwise_distinct

end FieldContextual
end BilinearComplexity
