import BilinearComplexity.NormalizedBinaryCoverageCompiler
import BilinearComplexity.NormalizedBinaryCoverageTables
import BilinearComplexity.NormalizedBinaryCoverageCompleteness

set_option autoImplicit false

/-!
# Concrete normalized binary coverage compiler

This module closes the generic coverage compiler with the generated,
kernel-checked coverage tables and their semantic completeness theorems.  Its
output retains the selected family, orientation, replay-row index, checked
action witness, both bounded paths, and their endpoint-span confinement.

AI disclosure: produced with AI assistance (see `README`).
-/

namespace BilinearComplexity.NormalizedBinaryCoverage

open BinaryCircuit
open NormalizedBinaryAllModeMove
open NormalizedBinaryCarrier
open NormalizedBinaryCoverageCompleteness
open NormalizedBinaryCoverageData
open NormalizedBinaryCoverageTables
open NormalizedBinaryFiveCircuitCertificate
open NormalizedBinaryFiveCircuitRows
open NormalizedBinaryProfileOrientation
open NormalizedBinaryRelationEnumeration
open RawCoverageAction

/-- The four generated checked coverage tables, closed by the independently
proved semantic completeness equalities. -/
def concreteFamilyCoverageTables : FamilyCoverageTables
  | .family221 => {
      entries := coverageEntries221
      decoded_complete := by
        change decodedTargetSet (coverageEntries221.map Entry.raw) =
          allExactRelations profile221
        rw [coverageEntries221_raws]
        exact literalTargetSet221_eq_allExactRelations
    }
  | .family411 => {
      entries := coverageEntries411
      decoded_complete := by
        change decodedTargetSet (coverageEntries411.map Entry.raw) =
          allExactRelations profile411
        rw [coverageEntries411_raws]
        exact literalTargetSet411_eq_allExactRelations
    }
  | .family321 => {
      entries := coverageEntries321
      decoded_complete := by
        change decodedTargetSet (coverageEntries321.map Entry.raw) =
          allExactRelations profile321
        rw [coverageEntries321_raws]
        exact literalTargetSet321_eq_allExactRelations
    }
  | .family222 => {
      entries := coverageEntries222
      decoded_complete := by
        change decodedTargetSet (coverageEntries222.map Entry.raw) =
          allExactRelations profile222
        rw [coverageEntries222_raws]
        exact literalTargetSet222_eq_allExactRelations
    }

/-- Compile any exact normalized binary relation using the closed checked
coverage tables, with no coverage hypothesis required from the caller. -/
def compileNormalized {p : Profile} (target : ExactRelation p) :
    CompilationResult target :=
  compileWithCoverage concreteFamilyCoverageTables target

/-- The final certificate produced by the closed compiler.  Its forward and
reverse fields are the two concrete transported all-mode paths. -/
def compileNormalizedCertificate {p : Profile} (target : ExactRelation p) :
    FiveCircuitCertificate p target.1.left target.1.right :=
  (compileNormalized target).certificate

/-- The checked action witness exposed by a compilation maps its selected
replay-row endpoints to the oriented requested endpoints. -/
theorem compileNormalized_witness_maps_endpoints {p : Profile}
    (target : ExactRelation p) :
    let compiled := compileNormalized target
    compiled.witness.action.actEndpoints
        ((familyRowSources compiled.choice.family)
          compiled.selectedRowIndex).endpoints = compiled.oriented.1 := by
  dsimp only
  exact (compileNormalized target).witness.maps_endpoints

/-- Both paths produced by the compiler satisfy the advertised edge-count and
altitude bounds. -/
theorem compileNormalized_principal_bounds {p : Profile}
    (target : ExactRelation p) :
    let certificate := compileNormalizedCertificate target
    certificate.forward.length ≤ 3 ∧
      certificate.reverse.length ≤ 3 ∧
      certificate.forward.altitude ≤ 4 ∧
      certificate.reverse.altitude ≤ 4 := by
  dsimp only
  exact ⟨(compileNormalizedCertificate target).forward_length_le,
    (compileNormalizedCertificate target).reverse_length_le,
    (compileNormalizedCertificate target).forward_altitude_le,
    (compileNormalizedCertificate target).reverse_altitude_le⟩

/-- Every vertex of both compiler-produced paths remains confined to the
factor spans generated by the exact relation's two endpoints. -/
theorem compileNormalized_path_confinement {p : Profile}
    (target : ExactRelation p) :
    let certificate := compileNormalizedCertificate target
    PathFactorSpanConfined certificate.forward
        (target.1.left ∪ target.1.right) ∧
      PathFactorSpanConfined certificate.reverse
        (target.1.left ∪ target.1.right) := by
  dsimp only
  exact ⟨(compileNormalizedCertificate target).forward_confined,
    (compileNormalizedCertificate target).reverse_confined⟩

/-- The five endpoint terms of every compiled exact relation form a circuit. -/
theorem compileNormalized_circuit {p : Profile}
    (target : ExactRelation p) :
    Circuit (@tensorEvaluation p) (target.1.left ∪ target.1.right) :=
  (compileNormalizedCertificate target).circuit

private def exactRelationOfCertifiedReplayRow (r : CertifiedReplayRow) :
    ExactRelation r.row.profile :=
  ⟨{ left := r.row.start, right := r.row.finish },
    r.card_start, r.card_finish, r.disjoint,
    (allModeMovePath_preserves_evaluation r.certificate.forward).symm,
    r.exact_profile⟩

example :
    let target := exactRelationOfCertifiedReplayRow certified22101
    let compiled := compileNormalized target
    compiled.choice.family = .family221 ∧
      compiled.choice.orientation = .abc ∧
      Nonempty (FiveCircuitCertificate certified22101.row.profile
        target.1.left target.1.right) ∧
      compiled.certificate.forward.length ≤ 3 := by
  dsimp only
  exact ⟨rfl, rfl, ⟨(compileNormalized
    (exactRelationOfCertifiedReplayRow certified22101)).certificate⟩,
    (compileNormalized
      (exactRelationOfCertifiedReplayRow certified22101)).certificate.forward_length_le⟩

example :
    let target := exactRelationOfCertifiedReplayRow certified41101
    let compiled := compileNormalized target
    compiled.choice.family = .family411 ∧
      compiled.choice.orientation = .abc ∧
      Nonempty (FiveCircuitCertificate certified41101.row.profile
        target.1.left target.1.right) ∧
      compiled.certificate.reverse.length ≤ 3 := by
  dsimp only
  exact ⟨rfl, rfl, ⟨(compileNormalized
    (exactRelationOfCertifiedReplayRow certified41101)).certificate⟩,
    (compileNormalized
      (exactRelationOfCertifiedReplayRow certified41101)).certificate.reverse_length_le⟩

example :
    let target := exactRelationOfCertifiedReplayRow certified32101
    let compiled := compileNormalized target
    compiled.choice.family = .family321 ∧
      compiled.choice.orientation = .abc ∧
      Nonempty (FiveCircuitCertificate certified32101.row.profile
        target.1.left target.1.right) ∧
      compiled.certificate.forward.altitude ≤ 4 := by
  dsimp only
  exact ⟨rfl, rfl, ⟨(compileNormalized
    (exactRelationOfCertifiedReplayRow certified32101)).certificate⟩,
    (compileNormalized
      (exactRelationOfCertifiedReplayRow certified32101)).certificate.forward_altitude_le⟩

example :
    let target := exactRelationOfCertifiedReplayRow certified22201
    let compiled := compileNormalized target
    compiled.choice.family = .family222 ∧
      compiled.choice.orientation = .abc ∧
      Nonempty (FiveCircuitCertificate certified22201.row.profile
        target.1.left target.1.right) ∧
      compiled.certificate.reverse.altitude ≤ 4 := by
  dsimp only
  exact ⟨rfl, rfl, ⟨(compileNormalized
    (exactRelationOfCertifiedReplayRow certified22201)).certificate⟩,
    (compileNormalized
      (exactRelationOfCertifiedReplayRow certified22201)).certificate.reverse_altitude_le⟩

#check @concreteFamilyCoverageTables
#check @compileNormalized
#check @compileNormalizedCertificate
#check @compileNormalized_witness_maps_endpoints
#check @compileNormalized_principal_bounds
#check @compileNormalized_path_confinement
#check @compileNormalized_circuit

#print axioms concreteFamilyCoverageTables
#print axioms compileNormalized
#print axioms compileNormalizedCertificate
#print axioms compileNormalized_principal_bounds
#print axioms compileNormalized_path_confinement
#print axioms compileNormalized_circuit

end BilinearComplexity.NormalizedBinaryCoverage
