import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Matrix.Rank
import BilinearComplexity.Support

set_option autoImplicit false

/-!
# Pair-to-triple constraints for binary scheme search

The broader objective is to organize searches for rank-one decompositions of
the matrix-multiplication tensor around constrained local dependencies. In the
intended normalized finite-set carrier over $\mathbb F_2$, the symmetric
difference of two equal-valued states is a zero-sum binary cycle, whose minimal
nonempty subcycles are circuits. `BilinearComplexity.BinaryCircuit` formalizes
this abstract finite-set layer.

That layer is not the repository's ordered `BilinearComplexity.Scheme` carrier,
and the present file does not bridge them. Applying the result to a full scheme
requires a normalized injective carrier representation, nonzero and distinct
terms such as those required by `Scheme.Valid`, coherent `Fin`-indexed
enumeration and replacement data across cardinality-changing adjacent states,
and separate checks that a local replacement is collision-free and legal in its
unchanged context.

This file supplies a dimension-free constraint for the five-term relation
relevant to a collision-free two-for-three replacement. If five pairwise
distinct nonzero pure tensors satisfy a two-equals-three relation, then in at
least one mode all three replacement factors lie in the span of the original
pair. Once the required carrier bridge provides such a relation, candidate
replacements lie in the union of three structured loci, one for each
constrained mode, rather than in the unrestricted space of triples. The result
is independent of the target tensor, but this module proves neither a global
search reduction nor compilation to a legal move system.

The intended search-space program is broader than $\mathbb F_2$, while the
current theorem and finite-set cycle API are deliberately binary. The
Lovitz–Petrov connectedness and dimension framework below is field-independent;
the current symmetric-difference carrier is not. A nonbinary extension must
retain dependence coefficients and scalar-refactorization data rather than
reuse the binary carrier unchanged.

## Prior art and the broader search-space constraint

The general structural result is the arbitrary-field Splitting Theorem in
[Lovitz–Petrov, *A generalization of Kruskal's theorem on tensor
decomposition*, Theorem 4](https://doi.org/10.1017/fms.2023.20). A multiset $E$
of nonzero product tensors splits when a nonempty proper submultiset and its
complement have spans forming a direct sum, equivalently when the represented
vector matroid is disconnected. If $d_j$ is the factor-span dimension in mode
$j$, their theorem states

$$\dim \operatorname{span}(E) \leq \sum_j(d_j-1) \quad\Longrightarrow\quad
E\text{ splits}.$$

Consequently every connected candidate configuration obeys the strict reverse
inequality. In particular, an $n$-element product-tensor circuit has span
dimension $n-1$ and therefore

$$\sum_j(d_j-1) \leq n-2.$$

Although Lovitz–Petrov use splitting theory to study tensor decompositions and
uniqueness, its contrapositive can also serve as a target-independent necessary
condition for a future search: factor profiles violating the dimension budget
cannot occur in a local circuit. The present theorem supplies the
distinguished-side condition relevant to binary two-for-three search.
Mathematically, its nonzero, injective binary relation makes the five terms a
circuit of span dimension four, so $\sum_j(d_j-1) \leq 3$; this module does not
package that deduction as a `BinaryCircuit.Circuit` theorem. If $e_j$ is the
span dimension of the original pair in mode $j$, then $e_j \in \{1,2\}$ and
$\sum_j e_j \geq 4$; growth beyond the pair span in all three modes would force
$\sum_j(d_j-1) \geq 4$, a contradiction.

As independent geometric prior art,
[Ballico, *Linear dependent subsets of Segre varieties*, Theorem
1.1](https://arxiv.org/abs/2002.05367) classifies nondegenerate five-point
circuits on Segre varieties over a field. After passing to the multiprojective
space generated by the factor projections and discarding $\mathbb P^0$ factors,
that classification also yields the binary span restriction: a discarded
factor already gives a constrained mode, while the three-factor case is
$\mathbb P^1 \times \mathbb P^1 \times \mathbb P^1$; uniqueness of nonzero
projective representatives over $\mathbb F_2$ then forces the original pair to
span a full mode somewhere. Ballico supplies a small-circuit geometric
classification, whereas Lovitz–Petrov supplies the scalable connectedness and
dimension framework.

Neither cited theorem states the distinguished binary rule or a
matrix-multiplication search reduction verbatim. Those are corollary-level
applications here, not claims of mathematical novelty. The proof in this file
is self-contained and does not formalize the broader splitting theory.

## Proof strategy

An annihilator of a pair span contracts the relation to its outside support. A
singleton support is impossible, while a three-term support has a common
complementary factor. Contracting that common factor forces the desired span
conclusion in another mode. Thus, under the contrary assumption that all three
coordinate conclusions fail, every nonempty outside support has exactly two
indices. Equal two-index supports in two modes identify two pure tensors;
distinct supports have a unique common index, which two annihilators isolate
and contradict factor nonzeroness.

The file also includes the binary rank and outer-product lemmas used by these
contractions.
-/

namespace BilinearComplexity.PairTripleSpan

local instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- Every scalar in `ZMod 2` is zero or one. -/
theorem scalar_eq_zero_or_one (x : ZMod 2) : x = 0 ∨ x = 1 := by
  have hx : x.val < 2 := ZMod.val_lt x
  have hval : x.val = 0 ∨ x.val = 1 := by omega
  rcases hval with hval | hval
  · left
    apply ZMod.val_injective
    simpa using hval
  · right
    apply ZMod.val_injective
    change x.val = 1
    exact hval

/-- Two distinct nonzero vectors over `ZMod 2` are linearly independent. -/
theorem pair_linearIndependent_of_ne {ι : Type*} {x y : ι → ZMod 2}
    (hx : x ≠ 0) (hy : y ≠ 0) (hxy : x ≠ y) :
    LinearIndependent (ZMod 2) ![x, y] := by
  rw [LinearIndependent.pair_iff]
  intro s t h
  rcases scalar_eq_zero_or_one s with rfl | rfl <;>
    rcases scalar_eq_zero_or_one t with rfl | rfl
  · simp
  · simp only [zero_smul, one_smul, zero_add] at h
    exact (hy h).elim
  · simp only [zero_smul, one_smul, add_zero] at h
    exact (hx h).elim
  · simp only [one_smul] at h
    have heq : x = y := by
      funext i
      have hi := congrFun h i
      rcases scalar_eq_zero_or_one (x i) with hxi | hxi <;>
        rcases scalar_eq_zero_or_one (y i) with hyi | hyi <;>
        simp_all
    exact (hxy heq).elim

/-- Distinct nonzero binary vectors expose two distinct nonzero coordinate pairs. -/
theorem coordinate_witness {n : Type*} (v y : n → ZMod 2)
    (hv : v ≠ 0) (hy : y ≠ 0) (hvy : v ≠ y) :
    ∃ j k,
      (![v j, y j] : Fin 2 → ZMod 2) ≠ 0 ∧
      (![v k, y k] : Fin 2 → ZMod 2) ≠ 0 ∧
      (![v j, y j] : Fin 2 → ZMod 2) ≠ ![v k, y k] := by
  classical
  have ev : ∃ i, v i ≠ 0 := by
    by_contra! h
    apply hv
    funext i
    exact h i
  let i := Classical.choose ev
  have hi : v i ≠ 0 := Classical.choose_spec ev
  rcases scalar_eq_zero_or_one (v i) with vi0 | vi1
  · exact (hi vi0).elim
  · rcases scalar_eq_zero_or_one (y i) with yi0 | yi1
    · have ey : ∃ k, y k ≠ 0 := by
        by_contra! h
        apply hy
        funext k
        exact h k
      let k := Classical.choose ey
      have hk : y k ≠ 0 := Classical.choose_spec ey
      rcases scalar_eq_zero_or_one (y k) with yk0 | yk1
      · exact (hk yk0).elim
      · refine ⟨i, k, ?_, ?_, ?_⟩ <;> intro h
        all_goals
          have h0 := congrFun h (0 : Fin 2)
          have h1 := congrFun h (1 : Fin 2)
          simp_all
    · have ed : ∃ k, v k ≠ y k := by
        by_contra! h
        apply hvy
        funext k
        exact h k
      let k := Classical.choose ed
      have hd : v k ≠ y k := Classical.choose_spec ed
      rcases scalar_eq_zero_or_one (v k) with vk0 | vk1 <;>
        rcases scalar_eq_zero_or_one (y k) with yk0 | yk1
      · exact (hd (vk0.trans yk0.symm)).elim
      · refine ⟨i, k, ?_, ?_, ?_⟩
        · intro h
          have h0 := congrFun h (0 : Fin 2)
          simp [vi1] at h0
        · intro h
          have h1 := congrFun h (1 : Fin 2)
          simp [yk1] at h1
        · intro h
          have h0 := congrFun h (0 : Fin 2)
          simp [vi1, vk0] at h0
      · refine ⟨i, k, ?_, ?_, ?_⟩
        · intro h
          have h0 := congrFun h (0 : Fin 2)
          simp [vi1] at h0
        · intro h
          have h0 := congrFun h (0 : Fin 2)
          simp [vk1] at h0
        · intro h
          have h1 := congrFun h (1 : Fin 2)
          simp [yi1, yk0] at h1
      · exact (hd (vk1.trans yk1.symm)).elim

/-- Independent vectors give an injective two-coefficient linear combination. -/
theorem pairCombination_injective {m : Type*} (u x : m → ZMod 2)
    (hLI : LinearIndependent (ZMod 2) ![u, x]) :
    Function.Injective (fun c : Fin 2 → ZMod 2 => c 0 • u + c 1 • x) := by
  intro a b h
  have hzero :
      (a 0 - b 0) • u + (a 1 - b 1) • x = 0 := by
    rw [sub_smul, sub_smul]
    calc
      (a 0 • u - b 0 • u) + (a 1 • x - b 1 • x) =
          (a 0 • u + a 1 • x) - (b 0 • u + b 1 • x) := by
            abel
      _ = 0 := sub_eq_zero.mpr h
  obtain ⟨h0, h1⟩ := hLI.eq_zero_of_pair hzero
  funext i
  fin_cases i
  · exact sub_eq_zero.mp h0
  · exact sub_eq_zero.mp h1

/-- A matrix over `ZMod 2` containing two distinct nonzero columns has rank at least two. -/
theorem two_le_rank_of_cols_ne {m n : Type*} [Fintype m] [Fintype n]
    (M : Matrix m n (ZMod 2)) (p q : n)
    (hp : M.col p ≠ 0) (hq : M.col q ≠ 0) (hpq : M.col p ≠ M.col q) :
    2 ≤ M.rank := by
  let w : Fin 2 → m → ZMod 2 := ![M.col p, M.col q]
  have hLI : LinearIndependent (ZMod 2) w :=
    pair_linearIndependent_of_ne hp hq hpq
  rw [Matrix.rank_eq_finrank_span_cols]
  calc
    2 = Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) := by
      rw [finrank_span_eq_card hLI, Fintype.card_fin]
    _ ≤ Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range M.col)) := by
      apply Submodule.finrank_mono
      apply Submodule.span_mono
      rintro _ ⟨j, rfl⟩
      refine ⟨![p, q] j, ?_⟩
      fin_cases j <;> rfl

/-- The sum of two pure matrices with independent left and right factors has rank at least two. -/
theorem rank_add_vecMulVec_ge_two
    {m n : Type*} [Fintype m] [Fintype n]
    {u x : m → ZMod 2} {v y : n → ZMod 2}
    (hu : u ≠ 0) (hx : x ≠ 0) (hux : u ≠ x)
    (hv : v ≠ 0) (hy : y ≠ 0) (hvy : v ≠ y) :
    2 ≤ Matrix.rank
      (Matrix.vecMulVec u v + Matrix.vecMulVec x y) := by
  classical
  obtain ⟨j, k, hj0, hk0, hjk⟩ :=
    coordinate_witness v y hv hy hvy
  let A : Matrix m n (ZMod 2) :=
    Matrix.vecMulVec u v + Matrix.vecMulVec x y
  let T : (Fin 2 → ZMod 2) → (m → ZMod 2) :=
    fun c => c 0 • u + c 1 • x
  have hT : Function.Injective T := by
    simpa [T] using
      pairCombination_injective u x
        (pair_linearIndependent_of_ne hu hx hux)
  have hcol (r : n) : A.col r = T ![v r, y r] := by
    ext i
    simp [A, T, Matrix.vecMulVec, mul_comm]
  have hAj0 : A.col j ≠ 0 := by
    rw [hcol j]
    intro h
    apply hj0
    apply hT
    simpa [T] using h
  have hAk0 : A.col k ≠ 0 := by
    rw [hcol k]
    intro h
    apply hk0
    apply hT
    simpa [T] using h
  have hAjk : A.col j ≠ A.col k := by
    rw [hcol j, hcol k]
    intro h
    exact hjk (hT h)
  simpa [A] using
    two_le_rank_of_cols_ne A j k hAj0 hAk0 hAjk

/-- A sum of two nonzero pure binary matrices of rank at most one has a shared factor. -/
theorem eq_left_or_eq_right_of_rank_add_vecMulVec_le_one
    {m n : Type*} [Fintype m] [Fintype n]
    {u x : m → ZMod 2} {v y : n → ZMod 2}
    (hu : u ≠ 0) (hx : x ≠ 0) (hv : v ≠ 0) (hy : y ≠ 0)
    (hrank : Matrix.rank
      (Matrix.vecMulVec u v + Matrix.vecMulVec x y) ≤ 1) :
    u = x ∨ v = y := by
  by_contra h
  rw [not_or] at h
  have hrank' := rank_add_vecMulVec_ge_two hu hx h.1 hv hy h.2
  omega

/-- A nonzero binary combination of two matrices is an endpoint or their sum. -/
theorem zmod_two_combination_classification
    {m n : Type*} (P Q M : Matrix m n (ZMod 2)) (a b : ZMod 2)
    (hM0 : M ≠ 0) (hM : M = a • P + b • Q) :
    M = P ∨ M = Q ∨ M = P + Q := by
  rcases scalar_eq_zero_or_one a with ha | ha <;>
    rcases scalar_eq_zero_or_one b with hb | hb
  · have hMzero : M = 0 := by simpa [ha, hb] using hM
    exact (hM0 hMzero).elim
  · right
    left
    simpa [ha, hb] using hM
  · left
    simpa [ha, hb] using hM
  · right
    right
    simpa [ha, hb] using hM

/-- A nonzero rank-one point in a binary plane whose third point has rank at least two
is an endpoint. -/
theorem zmod_two_combination
    {m n : Type*} [Fintype m] [Fintype n]
    (P Q M : Matrix m n (ZMod 2)) (a b : ZMod 2)
    (hM0 : M ≠ 0)
    (hMrank : M.rank ≤ 1)
    (hPQrank : 2 ≤ (P + Q).rank)
    (hM : M = a • P + b • Q) :
    M = P ∨ M = Q := by
  rcases zmod_two_combination_classification P Q M a b hM0 hM with
    hMP | hMQ | hMPQ
  · exact Or.inl hMP
  · exact Or.inr hMQ
  · rw [hMPQ] at hMrank
    have hbad := hPQrank.trans hMrank
    norm_num at hbad

/-- Two nonempty zero-sum blocks cannot partition five distinct nonzero binary vectors. -/
theorem fin5_partition_sum_contradiction
    {a : Type*}
    (r : Fin 5 → a → ZMod 2)
    (I J : Finset (Fin 5))
    (hr : ∀ i, r i ≠ 0) (hI : I.Nonempty) (hJ : J.Nonempty)
    (hdis : Disjoint I J) (hcover : I ∪ J = Finset.univ)
    (hsI : ∑ i ∈ I, r i = 0) (hsJ : ∑ i ∈ J, r i = 0)
    (hinjI : Set.InjOn r (↑I : Set (Fin 5)))
    (hinjJ : Set.InjOn r (↑J : Set (Fin 5))) : False := by
  classical
  have hdup (f : a → ZMod 2) : f + f = 0 := by
    funext x
    simp only [Pi.add_apply, Pi.zero_apply]
    rcases scalar_eq_zero_or_one (f x) with h | h
    · simp [h]
    · rw [h]
      decide
  have bad (s : Finset (Fin 5)) (hs : s.card = 2)
      (hz : ∑ i ∈ s, r i = 0)
      (hinj : Set.InjOn r (↑s : Set (Fin 5))) : False := by
    obtain ⟨i, j, hij, rfl⟩ := Finset.card_eq_two.mp hs
    have hsum : r i + r j = 0 := by simpa [hij] using hz
    have heq : r i = r j := by
      calc
        r i = r i + 0 := by simp
        _ = r i + (r j + r j) := by rw [hdup (r j)]
        _ = (r i + r j) + r j := by abel
        _ = r j := by rw [hsum]; simp
    exact hij (hinj (by simp) (by simp) heq)
  have hI1 : I.card ≠ 1 := by
    rintro h
    obtain ⟨i, rfl⟩ := Finset.card_eq_one.mp h
    exact hr i (by simpa using hsI)
  have hJ1 : J.card ≠ 1 := by
    rintro h
    obtain ⟨j, rfl⟩ := Finset.card_eq_one.mp h
    exact hr j (by simpa using hsJ)
  have hcard : I.card + J.card = 5 := by
    calc
      I.card + J.card = (I ∪ J).card :=
        (Finset.card_union_of_disjoint hdis).symm
      _ = 5 := by rw [hcover]; simp
  have hsizes :
      (I.card = 2 ∧ J.card = 3) ∨
      (I.card = 3 ∧ J.card = 2) := by
    have := Finset.card_pos.mpr hI
    have := Finset.card_pos.mpr hJ
    omega
  rcases hsizes with ⟨hI2, _⟩ | ⟨_, hJ2⟩
  · exact bad I hI2 hsI hinjI
  · exact bad J hJ2 hsJ hinjJ

/-- A vector with a nonzero coordinate is not the zero vector. -/
theorem exists_apply_ne_zero {ι : Type*} {x : ι → ZMod 2} (hx : x ≠ 0) :
    ∃ i, x i ≠ 0 := by
  by_contra h
  push Not at h
  apply hx
  funext i
  exact h i

/-- The only nonzero scalar in `ZMod 2` is one. -/
theorem eq_one_of_ne_zero {x : ZMod 2} (hx : x ≠ 0) : x = 1 := by
  rcases scalar_eq_zero_or_one x with hx0 | hx1
  · exact (hx hx0).elim
  · exact hx1

/-- Every vector over `ZMod 2` is its own additive inverse. -/
theorem add_self_eq_zero_f2 {M : Type*} [AddCommGroup M] [Module (ZMod 2) M]
    (x : M) : x + x = 0 := by
  calc
    x + x = (1 : ZMod 2) • x + (1 : ZMod 2) • x := by simp
    _ = ((1 : ZMod 2) + 1) • x := by rw [add_smul]
    _ = 0 := by
      have hchar : (1 : ZMod 2) + 1 = 0 := by decide
      rw [hchar, zero_smul]

/-- In characteristic two, a two-term zero sum is an equality. -/
theorem add_eq_zero_iff_eq_f2 {M : Type*} [AddCommGroup M] [Module (ZMod 2) M]
    (x y : M) : x + y = 0 ↔ x = y := by
  constructor
  · intro h
    calc
      x = x + 0 := by simp
      _ = x + (y + y) := by rw [add_self_eq_zero_f2 y]
      _ = (x + y) + y := by abel
      _ = y := by rw [h]; simp
  · intro hxy
    subst y
    exact add_self_eq_zero_f2 x

/-- Nonzeroness of a pure tensor forces nonzeroness of every factor. -/
theorem factors_ne_zero_of_triad_ne_zero {a b c : ℕ}
    {u : Fin a → ZMod 2} {v : Fin b → ZMod 2} {w : Fin c → ZMod 2}
    (h : BilinearComplexity.triad u v w ≠ 0) : u ≠ 0 ∧ v ≠ 0 ∧ w ≠ 0 := by
  constructor
  · intro hu
    apply h
    ext i j k
    simp [BilinearComplexity.triad, hu]
  constructor
  · intro hv
    apply h
    ext i j k
    simp [BilinearComplexity.triad, hv]
  · intro hw
    apply h
    ext i j k
    simp [BilinearComplexity.triad, hw]

/-- An outer product of two nonzero binary vectors is nonzero. -/
theorem vecMulVec_ne_zero {m n : Type*} {u : m → ZMod 2} {v : n → ZMod 2}
    (hu : u ≠ 0) (hv : v ≠ 0) : Matrix.vecMulVec u v ≠ 0 := by
  obtain ⟨i, hi⟩ := exists_apply_ne_zero hu
  obtain ⟨j, hj⟩ := exists_apply_ne_zero hv
  intro h
  have hij := congrArg (fun M : Matrix m n (ZMod 2) => M i j) h
  exact mul_ne_zero hi hj (by simpa [Matrix.vecMulVec] using hij)

/-- Nonzero outer products have unique binary factors. -/
theorem vecMulVec_eq_vecMulVec {m n : Type*}
    {u u' : m → ZMod 2} {v v' : n → ZMod 2}
    (hu : u ≠ 0) (hv : v ≠ 0) (_hu' : u' ≠ 0) (_hv' : v' ≠ 0)
    (h : Matrix.vecMulVec u v = Matrix.vecMulVec u' v') : u = u' ∧ v = v' := by
  obtain ⟨i, hi⟩ := exists_apply_ne_zero hu
  obtain ⟨j, hj⟩ := exists_apply_ne_zero hv
  have hi1 := eq_one_of_ne_zero hi
  have hj1 := eq_one_of_ne_zero hj
  have hij := congrArg (fun M : Matrix m n (ZMod 2) => M i j) h
  have hij' : (1 : ZMod 2) = u' i * v' j := by
    simpa [Matrix.vecMulVec, hi1, hj1] using hij
  have hprod : u' i * v' j ≠ 0 := by
    rw [← hij']
    exact one_ne_zero
  have hui' := eq_one_of_ne_zero (mul_ne_zero_iff.mp hprod).1
  have hvj' := eq_one_of_ne_zero (mul_ne_zero_iff.mp hprod).2
  constructor
  · funext k
    have hk := congrArg (fun M : Matrix m n (ZMod 2) => M k j) h
    simpa [Matrix.vecMulVec, hj1, hvj'] using hk
  · funext k
    have hk := congrArg (fun M : Matrix m n (ZMod 2) => M i k) h
    simpa [Matrix.vecMulVec, hi1, hui'] using hk

/-- Three nonzero pure binary matrices summing to zero share a left or right factor. -/
theorem common_factor_of_three_vecMulVec
    {m n : Type*} [Fintype m] [Fintype n]
    {u₂ u₃ u₄ : m → ZMod 2} {v₂ v₃ v₄ : n → ZMod 2}
    (hu₂ : u₂ ≠ 0) (hv₂ : v₂ ≠ 0)
    (hu₃ : u₃ ≠ 0) (hv₃ : v₃ ≠ 0)
    (hu₄ : u₄ ≠ 0) (hv₄ : v₄ ≠ 0)
    (h : Matrix.vecMulVec u₂ v₂ + Matrix.vecMulVec u₃ v₃ +
      Matrix.vecMulVec u₄ v₄ = 0) :
    (u₂ = u₃ ∧ u₃ = u₄) ∨ (v₂ = v₃ ∧ v₃ = v₄) := by
  have hsum : Matrix.vecMulVec u₂ v₂ + Matrix.vecMulVec u₃ v₃ =
      Matrix.vecMulVec u₄ v₄ := by
    exact (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [add_assoc] using h)
  have hrank : Matrix.rank
      (Matrix.vecMulVec u₂ v₂ + Matrix.vecMulVec u₃ v₃) ≤ 1 := by
    rw [hsum]
    exact Matrix.rank_vecMulVec_le _ _
  rcases eq_left_or_eq_right_of_rank_add_vecMulVec_le_one
      hu₂ hu₃ hv₂ hv₃ hrank with hu | hv
  · left
    have hfactor : Matrix.vecMulVec u₂ (v₂ + v₃) =
        Matrix.vecMulVec u₄ v₄ := by
      rw [← hsum]
      ext i j
      simp [Matrix.vecMulVec, mul_add, hu]
    have hvsum : v₂ + v₃ ≠ 0 := by
      intro hz
      apply vecMulVec_ne_zero hu₄ hv₄
      rw [← hfactor, hz]
      ext i j
      simp [Matrix.vecMulVec]
    have hfac := vecMulVec_eq_vecMulVec hu₂ hvsum hu₄ hv₄ hfactor
    exact ⟨hu, hu.symm.trans hfac.1⟩
  · right
    have hfactor : Matrix.vecMulVec (u₂ + u₃) v₂ =
        Matrix.vecMulVec u₄ v₄ := by
      rw [← hsum]
      ext i j
      simp [Matrix.vecMulVec, add_mul, hv]
    have husum : u₂ + u₃ ≠ 0 := by
      intro hz
      apply vecMulVec_ne_zero hu₄ hv₄
      rw [← hfactor, hz]
      ext i j
      simp [Matrix.vecMulVec]
    have hfac := vecMulVec_eq_vecMulVec husum hv₂ hu₄ hv₄ hfactor
    exact ⟨hv, hv.symm.trans hfac.2⟩

/-- A vector outside a subspace is detected by a binary linear functional
that annihilates the subspace. -/
theorem exists_annihilator_one {M : Type*} [AddCommGroup M] [Module (ZMod 2) M]
    (S : Subspace (ZMod 2) M) {x : M} (hx : x ∉ S) :
    ∃ f : M →ₗ[ZMod 2] ZMod 2, (∀ y ∈ S, f y = 0) ∧ f x = 1 := by
  have hnot : ¬∀ f : Module.Dual (ZMod 2) M,
      f ∈ S.dualAnnihilator → f x = 0 := by
    intro h
    exact hx ((Subspace.forall_mem_dualAnnihilator_apply_eq_zero_iff
      (K := ZMod 2) (V := M) S x).mp h)
  push Not at hnot
  obtain ⟨f, hf, hfx⟩ := hnot
  refine ⟨f, (Submodule.mem_dualAnnihilator f).mp hf, ?_⟩
  exact eq_one_of_ne_zero hfx

/-- Contract the first coordinate of a concrete tensor with a linear functional. -/
def contractFirst {a b c : ℕ} (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2) :
    BilinearComplexity.Tensor (ZMod 2) a b c →ₗ[ZMod 2]
      Matrix (Fin b) (Fin c) (ZMod 2) where
  toFun T := fun j k => f (fun i => T i j k)
  map_add' T T' := by
    ext j k
    change f (fun i => T i j k + T' i j k) =
      f (fun i => T i j k) + f (fun i => T' i j k)
    rw [← f.map_add]
    congr 1
  map_smul' r T := by
    ext j k
    change f (r • (fun i => T i j k)) = r • f (fun i => T i j k)
    exact f.map_smul r _

/-- Contracting the first factor of a pure tensor scales its complementary outer product. -/
@[simp]
theorem contractFirst_triad {a b c : ℕ}
    (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (u : Fin a → ZMod 2) (v : Fin b → ZMod 2) (w : Fin c → ZMod 2) :
    contractFirst f (BilinearComplexity.triad u v w) =
      (f u) • Matrix.vecMulVec v w := by
  ext j k
  change f (fun i => u i * v j * w k) = f u * (v j * w k)
  rw [show (fun i => u i * v j * w k) = (v j * w k) • u by
    funext i
    simp [mul_left_comm, mul_comm]]
  simp [mul_assoc, mul_comm]

/-- Contract the first two coordinates of a concrete tensor. -/
def contractFirstTwo {a b c : ℕ}
    (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (g : (Fin b → ZMod 2) →ₗ[ZMod 2] ZMod 2) :
    BilinearComplexity.Tensor (ZMod 2) a b c →ₗ[ZMod 2] (Fin c → ZMod 2) where
  toFun T := fun k => f (fun i => g (fun j => T i j k))
  map_add' T T' := by
    ext k
    change f (fun i => g (fun j => T i j k + T' i j k)) =
      f (fun i => g (fun j => T i j k)) + f (fun i => g (fun j => T' i j k))
    rw [← f.map_add]
    congr 1
    funext i
    change g (fun j => T i j k + T' i j k) =
      g (fun j => T i j k) + g (fun j => T' i j k)
    rw [← g.map_add]
    congr 1
  map_smul' r T := by
    ext k
    change f (fun i => g (fun j => r * T i j k)) =
      r • f (fun i => g (fun j => T i j k))
    rw [← f.map_smul]
    congr 1
    funext i
    change g (r • (fun j => T i j k)) = r • g (fun j => T i j k)
    exact g.map_smul r _

/-- Contracting the first two factors of a pure tensor scales its remaining factor. -/
@[simp]
theorem contractFirstTwo_triad {a b c : ℕ}
    (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (g : (Fin b → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (u : Fin a → ZMod 2) (v : Fin b → ZMod 2) (w : Fin c → ZMod 2) :
    contractFirstTwo f g (BilinearComplexity.triad u v w) =
      (f u * g v) • w := by
  ext k
  change f (fun i => g (fun j => u i * v j * w k)) =
    (f u * g v) * w k
  have hg (i : Fin a) : g (fun j => u i * v j * w k) =
      (u i * w k) * g v := by
    rw [show (fun j => u i * v j * w k) = (u i * w k) • v by
      funext j
      simp [mul_left_comm, mul_comm]]
    simp
  rw [show (fun i => g (fun j => u i * v j * w k)) =
      (g v * w k) • u by
    funext i
    rw [hg]
    simp [mul_assoc, mul_comm]]
  simp [mul_left_comm, mul_comm]

/-- A pair span admits a separator normalized at any outside vector. -/
theorem exists_pair_annihilator_one {M : Type*} [AddCommGroup M] [Module (ZMod 2) M]
    (x₀ x₁ x : M) (hx : x ∉ Submodule.span (ZMod 2) ({x₀, x₁} : Set M)) :
    ∃ f : M →ₗ[ZMod 2] ZMod 2,
      f x₀ = 0 ∧ f x₁ = 0 ∧ f x = 1 ∧
        ∀ y ∈ Submodule.span (ZMod 2) ({x₀, x₁} : Set M), f y = 0 := by
  obtain ⟨f, hf, hfx⟩ := exists_annihilator_one
    (Submodule.span (ZMod 2) ({x₀, x₁} : Set M)) hx
  refine ⟨f, hf x₀ (Submodule.subset_span (by simp)),
    hf x₁ (Submodule.subset_span (by simp)), hfx, hf⟩

/-- Contracting a pair-to-triple relation in its first coordinate annihilates
both terms on the pair side. -/
theorem contracted_first_relation {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (hf₀ : f u₀ = 0) (hf₁ : f u₁ = 0) :
    (f u₂) • Matrix.vecMulVec v₂ w₂ +
      (f u₃) • Matrix.vecMulVec v₃ w₃ +
      (f u₄) • Matrix.vecMulVec v₄ w₄ = 0 := by
  have hc := congrArg (fun T => contractFirst f T) h
  simpa [hf₀, hf₁] using hc.symm

/-- Contracting in two coordinates isolates products of the two coefficients. -/
theorem contracted_first_two_relation {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (f : (Fin a → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (g : (Fin b → ZMod 2) →ₗ[ZMod 2] ZMod 2)
    (hf₀ : f u₀ = 0) (hf₁ : f u₁ = 0)
    (hg₀ : g v₀ = 0) (hg₁ : g v₁ = 0) :
    (f u₂ * g v₂) • w₂ + (f u₃ * g v₃) • w₃ +
      (f u₄ * g v₄) • w₄ = 0 := by
  have hc := congrArg (fun T => contractFirstTwo f g T) h
  simpa [hf₀, hf₁, hg₀, hg₁] using hc.symm

/-- Exactly one first-coordinate survivor is impossible. -/
theorem singleton_outside_first_impossible {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₃ : u₃ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) : False := by
  obtain ⟨f, hf₀, hf₁, hf₂, hf⟩ := exists_pair_annihilator_one u₀ u₁ u₂ hu₂
  have hr := contracted_first_relation u₀ u₁ u₂ u₃ u₄
    v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f hf₀ hf₁
  have hfac := factors_ne_zero_of_triad_ne_zero hnz₂
  apply vecMulVec_ne_zero hfac.2.1 hfac.2.2
  simpa [hf₂, hf u₃ hu₃, hf u₄ hu₄] using hr

/-- With two first-coordinate survivors, their complementary outer products agree. -/
theorem two_survivors_force_outer_eq {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) :
    Matrix.vecMulVec v₂ w₂ = Matrix.vecMulVec v₃ w₃ := by
  obtain ⟨f, hf₀, hf₁, hf₂, hf⟩ := exists_pair_annihilator_one u₀ u₁ u₂ hu₂
  have hr := contracted_first_relation u₀ u₁ u₂ u₃ u₄
    v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f hf₀ hf₁
  have hM₂ : Matrix.vecMulVec v₂ w₂ ≠ 0 := by
    have hfac := factors_ne_zero_of_triad_ne_zero hnz₂
    exact vecMulVec_ne_zero hfac.2.1 hfac.2.2
  rcases scalar_eq_zero_or_one (f u₃) with hf₃ | hf₃
  · exfalso
    apply hM₂
    simpa [hf₂, hf₃, hf u₄ hu₄] using hr
  · exact (add_eq_zero_iff_eq_f2 _ _).mp (by
      simpa [hf₂, hf₃, hf u₄ hu₄] using hr)

/-- If all three first-coordinate factors survive modulo the pair span, then
the three complementary pure matrices share one factor. -/
theorem common_factor_of_all_outside_first {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hnz₃ : BilinearComplexity.triad u₃ v₃ w₃ ≠ 0)
    (hnz₄ : BilinearComplexity.triad u₄ v₄ w₄ ≠ 0)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₃ : u₃ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) :
    (v₂ = v₃ ∧ v₃ = v₄) ∨ (w₂ = w₃ ∧ w₃ = w₄) := by
  obtain ⟨f₂, hf₂₀, hf₂₁, hf₂₂, -⟩ :=
    exists_pair_annihilator_one u₀ u₁ u₂ hu₂
  obtain ⟨f₃, hf₃₀, hf₃₁, hf₃₃, -⟩ :=
    exists_pair_annihilator_one u₀ u₁ u₃ hu₃
  obtain ⟨f₄, hf₄₀, hf₄₁, hf₄₄, -⟩ :=
    exists_pair_annihilator_one u₀ u₁ u₄ hu₄
  let M₂ := Matrix.vecMulVec v₂ w₂
  let M₃ := Matrix.vecMulVec v₃ w₃
  let M₄ := Matrix.vecMulVec v₄ w₄
  have hfac₂ := factors_ne_zero_of_triad_ne_zero hnz₂
  have hfac₃ := factors_ne_zero_of_triad_ne_zero hnz₃
  have hfac₄ := factors_ne_zero_of_triad_ne_zero hnz₄
  have hM₂ : M₂ ≠ 0 := vecMulVec_ne_zero hfac₂.2.1 hfac₂.2.2
  have hM₃ : M₃ ≠ 0 := vecMulVec_ne_zero hfac₃.2.1 hfac₃.2.2
  have hM₄ : M₄ ≠ 0 := vecMulVec_ne_zero hfac₄.2.1 hfac₄.2.2
  have hr₂ := contracted_first_relation u₀ u₁ u₂ u₃ u₄
    v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f₂ hf₂₀ hf₂₁
  change (f₂ u₂) • M₂ + (f₂ u₃) • M₃ + (f₂ u₄) • M₄ = 0 at hr₂
  rw [hf₂₂] at hr₂
  rcases scalar_eq_zero_or_one (f₂ u₃) with h₂₃ | h₂₃ <;>
    rcases scalar_eq_zero_or_one (f₂ u₄) with h₂₄ | h₂₄
  · exact (hM₂ (by simpa [h₂₃, h₂₄] using hr₂)).elim
  · have h₂₄M : M₂ = M₄ :=
      (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [h₂₃, h₂₄] using hr₂)
    have hr₃ := contracted_first_relation u₀ u₁ u₂ u₃ u₄
      v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f₃ hf₃₀ hf₃₁
    change (f₃ u₂) • M₂ + (f₃ u₃) • M₃ + (f₃ u₄) • M₄ = 0 at hr₃
    rcases scalar_eq_zero_or_one (f₃ u₂) with h₃₂ | h₃₂ <;>
      rcases scalar_eq_zero_or_one (f₃ u₄) with h₃₄ | h₃₄
    · exact (hM₃ (by simpa [hf₃₃, h₃₂, h₃₄] using hr₃)).elim
    · have h₃₄M : M₃ = M₄ :=
        (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [hf₃₃, h₃₂, h₃₄] using hr₃)
      have hfac := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₄.2.1 hfac₄.2.2 h₂₄M
      exact Or.inl ⟨hfac.1.trans (vecMulVec_eq_vecMulVec hfac₃.2.1 hfac₃.2.2
        hfac₄.2.1 hfac₄.2.2 h₃₄M).1.symm, (vecMulVec_eq_vecMulVec
          hfac₃.2.1 hfac₃.2.2 hfac₄.2.1 hfac₄.2.2 h₃₄M).1⟩
    · have h₂₃M : M₂ = M₃ :=
        (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [hf₃₃, h₃₂, h₃₄] using hr₃)
      have e₂₃ := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₃.2.1 hfac₃.2.2 h₂₃M
      have e₂₄ := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₄.2.1 hfac₄.2.2 h₂₄M
      exact Or.inl ⟨e₂₃.1, e₂₃.1.symm.trans e₂₄.1⟩
    · have h' : M₃ + (M₄ + M₄) = 0 := by
        simpa only [hf₃₃, h₃₂, h₃₄, one_smul, h₂₄M,
          add_assoc, add_left_comm, add_comm] using hr₃
      rw [add_self_eq_zero_f2, add_zero] at h'
      exact (hM₃ h').elim
  · have h₂₃M : M₂ = M₃ :=
      (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [h₂₃, h₂₄] using hr₂)
    have hr₄ := contracted_first_relation u₀ u₁ u₂ u₃ u₄
      v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f₄ hf₄₀ hf₄₁
    change (f₄ u₂) • M₂ + (f₄ u₃) • M₃ + (f₄ u₄) • M₄ = 0 at hr₄
    rcases scalar_eq_zero_or_one (f₄ u₂) with h₄₂ | h₄₂ <;>
      rcases scalar_eq_zero_or_one (f₄ u₃) with h₄₃ | h₄₃
    · exact (hM₄ (by simpa [hf₄₄, h₄₂, h₄₃] using hr₄)).elim
    · have h₃₄M : M₃ = M₄ :=
        (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [hf₄₄, h₄₂, h₄₃] using hr₄)
      have e₂₃ := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₃.2.1 hfac₃.2.2 h₂₃M
      have e₃₄ := vecMulVec_eq_vecMulVec hfac₃.2.1 hfac₃.2.2
        hfac₄.2.1 hfac₄.2.2 h₃₄M
      exact Or.inl ⟨e₂₃.1, e₃₄.1⟩
    · have h₂₄M : M₂ = M₄ :=
        (add_eq_zero_iff_eq_f2 _ _).mp (by simpa [hf₄₄, h₄₂, h₄₃] using hr₄)
      have e₂₃ := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₃.2.1 hfac₃.2.2 h₂₃M
      have e₂₄ := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
        hfac₄.2.1 hfac₄.2.2 h₂₄M
      exact Or.inl ⟨e₂₃.1, e₂₃.1.symm.trans e₂₄.1⟩
    · have : M₄ = 0 := by
        simpa [hf₄₄, h₄₂, h₄₃, h₂₃M, add_self_eq_zero_f2] using hr₄
      exact (hM₄ this).elim
  · have hsum : M₂ + M₃ + M₄ = 0 := by simpa [h₂₃, h₂₄] using hr₂
    exact common_factor_of_three_vecMulVec hfac₂.2.1 hfac₂.2.2
      hfac₃.2.1 hfac₃.2.2 hfac₄.2.1 hfac₄.2.2 hsum

/-- If all three first-coordinate factors survive modulo the pair span, then
all three factors lie in the pair span in one of the other two coordinates. -/
theorem all_outside_first_forces_other_span {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hnz₃ : BilinearComplexity.triad u₃ v₃ w₃ ≠ 0)
    (hnz₄ : BilinearComplexity.triad u₄ v₄ w₄ ≠ 0)
    (hne₀₁ : BilinearComplexity.triad u₀ v₀ w₀ ≠
      BilinearComplexity.triad u₁ v₁ w₁)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₃ : u₃ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) :
    (v₂ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)) ∧
      v₃ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)) ∧
      v₄ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2))) ∨
    (w₂ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2)) ∧
      w₃ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2)) ∧
      w₄ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2))) := by
  rcases common_factor_of_all_outside_first u₀ u₁ u₂ u₃ u₄
      v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h hnz₂ hnz₃ hnz₄ hu₂ hu₃ hu₄ with
    hv | hw
  · by_cases hv₂ : v₂ ∈ Submodule.span (ZMod 2)
        ({v₀, v₁} : Set (Fin b → ZMod 2))
    · left
      exact ⟨hv₂, by simpa [← hv.1] using hv₂,
        by simpa [← hv.1, ← hv.2] using hv₂⟩
    · obtain ⟨g, hg₀, hg₁, hg₂, -⟩ :=
        exists_pair_annihilator_one v₀ v₁ v₂ hv₂
      have hswap :
          BilinearComplexity.triad v₀ u₀ w₀ + BilinearComplexity.triad v₁ u₁ w₁ =
            BilinearComplexity.triad v₂ u₂ w₂ +
              BilinearComplexity.triad v₃ u₃ w₃ +
                BilinearComplexity.triad v₄ u₄ w₄ := by
        ext j i k
        have hijk := congrFun (congrFun (congrFun h i) j) k
        simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hijk
      have hr := contracted_first_relation v₀ v₁ v₂ v₃ v₄
        u₀ u₁ u₂ u₃ u₄ w₀ w₁ w₂ w₃ w₄ hswap g hg₀ hg₁
      have hr' : Matrix.vecMulVec u₂ w₂ + Matrix.vecMulVec u₃ w₃ +
          Matrix.vecMulVec u₄ w₄ = 0 := by
        simpa [hg₂, ← hv.1, ← hv.2] using hr
      have hright : BilinearComplexity.triad u₂ v₂ w₂ +
          BilinearComplexity.triad u₃ v₃ w₃ +
            BilinearComplexity.triad u₄ v₄ w₄ = 0 := by
        ext i j k
        have hrijk := congrArg (fun M : Matrix (Fin a) (Fin c) (ZMod 2) => M i k) hr'
        simp only [Matrix.add_apply, Matrix.zero_apply, Matrix.vecMulVec_apply] at hrijk
        simp only [Pi.add_apply, Pi.zero_apply, BilinearComplexity.triad]
        have hv₂₄ : v₂ = v₄ := hv.1.trans hv.2
        rw [← hv.1, ← hv₂₄]
        calc
          u₂ i * v₂ j * w₂ k + u₃ i * v₂ j * w₃ k + u₄ i * v₂ j * w₄ k =
              v₂ j * (u₂ i * w₂ k + u₃ i * w₃ k + u₄ i * w₄ k) := by ring
          _ = 0 := by rw [hrijk, mul_zero]
      exfalso
      apply hne₀₁
      exact (add_eq_zero_iff_eq_f2 _ _).mp (h.trans hright)
  · by_cases hw₂ : w₂ ∈ Submodule.span (ZMod 2)
        ({w₀, w₁} : Set (Fin c → ZMod 2))
    · right
      exact ⟨hw₂, by simpa [← hw.1] using hw₂,
        by simpa [← hw.1, ← hw.2] using hw₂⟩
    · obtain ⟨g, hg₀, hg₁, hg₂, -⟩ :=
        exists_pair_annihilator_one w₀ w₁ w₂ hw₂
      have hswap :
          BilinearComplexity.triad w₀ u₀ v₀ + BilinearComplexity.triad w₁ u₁ v₁ =
            BilinearComplexity.triad w₂ u₂ v₂ +
              BilinearComplexity.triad w₃ u₃ v₃ +
                BilinearComplexity.triad w₄ u₄ v₄ := by
        ext k i j
        have hijk := congrFun (congrFun (congrFun h i) j) k
        simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hijk
      have hr := contracted_first_relation w₀ w₁ w₂ w₃ w₄
        u₀ u₁ u₂ u₃ u₄ v₀ v₁ v₂ v₃ v₄ hswap g hg₀ hg₁
      have hr' : Matrix.vecMulVec u₂ v₂ + Matrix.vecMulVec u₃ v₃ +
          Matrix.vecMulVec u₄ v₄ = 0 := by
        simpa [hg₂, ← hw.1, ← hw.2] using hr
      have hright : BilinearComplexity.triad u₂ v₂ w₂ +
          BilinearComplexity.triad u₃ v₃ w₃ +
            BilinearComplexity.triad u₄ v₄ w₄ = 0 := by
        ext i j k
        have hrijk := congrArg (fun M : Matrix (Fin a) (Fin b) (ZMod 2) => M i j) hr'
        simp only [Matrix.add_apply, Matrix.zero_apply, Matrix.vecMulVec_apply] at hrijk
        simp only [Pi.add_apply, Pi.zero_apply, BilinearComplexity.triad]
        have hw₂₄ : w₂ = w₄ := hw.1.trans hw.2
        rw [← hw.1, ← hw₂₄]
        calc
          u₂ i * v₂ j * w₂ k + u₃ i * v₃ j * w₂ k + u₄ i * v₄ j * w₂ k =
              w₂ k * (u₂ i * v₂ j + u₃ i * v₃ j + u₄ i * v₄ j) := by ring
          _ = 0 := by rw [hrijk, mul_zero]
      exfalso
      apply hne₀₁
      exact (add_eq_zero_iff_eq_f2 _ _).mp (h.trans hright)

/-- If no coordinate conclusion holds, exactly two triple-side first factors
survive outside the corresponding pair span. -/
theorem exactly_two_outside_first {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hnz₃ : BilinearComplexity.triad u₃ v₃ w₃ ≠ 0)
    (hnz₄ : BilinearComplexity.triad u₄ v₄ w₄ ≠ 0)
    (hne₀₁ : BilinearComplexity.triad u₀ v₀ w₀ ≠
      BilinearComplexity.triad u₁ v₁ w₁)
    (hfailu : ¬(u₂ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₃ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))))
    (hfailv : ¬(v₂ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)) ∧
      v₃ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)) ∧
      v₄ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2))))
    (hfailw : ¬(w₂ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2)) ∧
      w₃ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2)) ∧
      w₄ ∈ Submodule.span (ZMod 2) ({w₀, w₁} : Set (Fin c → ZMod 2)))) :
    (u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₃ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) ∨
    (u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₃ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₄ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) ∨
    (u₂ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₃ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)) ∧
      u₄ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))) := by
  classical
  let S := Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2))
  by_cases hu₂ : u₂ ∈ S <;> by_cases hu₃ : u₃ ∈ S <;> by_cases hu₄ : u₄ ∈ S
  · exact (hfailu ⟨hu₂, hu₃, hu₄⟩).elim
  · have hperm :
        BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
          BilinearComplexity.triad u₄ v₄ w₄ + BilinearComplexity.triad u₂ v₂ w₂ +
            BilinearComplexity.triad u₃ v₃ w₃ := by
      simpa only [add_assoc, add_left_comm, add_comm] using h
    exact (singleton_outside_first_impossible u₀ u₁ u₄ u₂ u₃
      v₀ v₁ v₄ v₂ v₃ w₀ w₁ w₄ w₂ w₃ hperm hnz₄ hu₄ hu₂ hu₃).elim
  · have hperm :
        BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
          BilinearComplexity.triad u₃ v₃ w₃ + BilinearComplexity.triad u₂ v₂ w₂ +
            BilinearComplexity.triad u₄ v₄ w₄ := by
      simpa only [add_assoc, add_left_comm, add_comm] using h
    exact (singleton_outside_first_impossible u₀ u₁ u₃ u₂ u₄
      v₀ v₁ v₃ v₂ v₄ w₀ w₁ w₃ w₂ w₄ hperm hnz₃ hu₃ hu₂ hu₄).elim
  · exact Or.inr (Or.inr ⟨hu₂, hu₃, hu₄⟩)
  · have hperm :
        BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
          BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
            BilinearComplexity.triad u₄ v₄ w₄ := h
    exact (singleton_outside_first_impossible u₀ u₁ u₂ u₃ u₄
      v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ hperm hnz₂ hu₂ hu₃ hu₄).elim
  · exact Or.inr (Or.inl ⟨hu₂, hu₃, hu₄⟩)
  · exact Or.inl ⟨hu₂, hu₃, hu₄⟩
  · rcases all_outside_first_forces_other_span u₀ u₁ u₂ u₃ u₄
        v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h hnz₂ hnz₃ hnz₄ hne₀₁
        hu₂ hu₃ hu₄ with hv | hw
    · exact (hfailv hv).elim
    · exact (hfailw hw).elim

/-- Equal two-element outside supports in the first two coordinates contradict
distinctness of the corresponding pure tensors. -/
theorem same_two_outside_modes_impossible {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hnz₃ : BilinearComplexity.triad u₃ v₃ w₃ ≠ 0)
    (hne₂₃ : BilinearComplexity.triad u₂ v₂ w₂ ≠
      BilinearComplexity.triad u₃ v₃ w₃)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hv₂ : v₂ ∉ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)))
    (hv₄ : v₄ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2))) : False := by
  have hvw := two_survivors_force_outer_eq u₀ u₁ u₂ u₃ u₄
    v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h hnz₂ hu₂ hu₄
  have hswap :
      BilinearComplexity.triad v₀ u₀ w₀ + BilinearComplexity.triad v₁ u₁ w₁ =
        BilinearComplexity.triad v₂ u₂ w₂ + BilinearComplexity.triad v₃ u₃ w₃ +
          BilinearComplexity.triad v₄ u₄ w₄ := by
    ext j i k
    have hijk := congrFun (congrFun (congrFun h i) j) k
    simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hijk
  have hnz₂swap : BilinearComplexity.triad v₂ u₂ w₂ ≠ 0 := by
    intro hz
    apply hnz₂
    ext i j k
    have hzjik := congrFun (congrFun (congrFun hz j) i) k
    simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hzjik
  have huw := two_survivors_force_outer_eq v₀ v₁ v₂ v₃ v₄
    u₀ u₁ u₂ u₃ u₄ w₀ w₁ w₂ w₃ w₄ hswap hnz₂swap hv₂ hv₄
  have hfac₂ := factors_ne_zero_of_triad_ne_zero hnz₂
  have hfac₃ := factors_ne_zero_of_triad_ne_zero hnz₃
  have evw := vecMulVec_eq_vecMulVec hfac₂.2.1 hfac₂.2.2
    hfac₃.2.1 hfac₃.2.2 hvw
  have euw := vecMulVec_eq_vecMulVec hfac₂.1 hfac₂.2.2
    hfac₃.1 hfac₃.2.2 huw
  apply hne₂₃
  simp [euw.1, evw.1, evw.2]

/-- Distinct two-element outside supports in the first two coordinates have a
unique common survivor, which a double contraction makes impossible. -/
theorem crossing_two_outside_modes_impossible {a b c : ℕ}
    (u₀ u₁ u₂ u₃ u₄ : Fin a → ZMod 2)
    (v₀ v₁ v₂ v₃ v₄ : Fin b → ZMod 2)
    (w₀ w₁ w₂ w₃ w₄ : Fin c → ZMod 2)
    (h : BilinearComplexity.triad u₀ v₀ w₀ + BilinearComplexity.triad u₁ v₁ w₁ =
      BilinearComplexity.triad u₂ v₂ w₂ + BilinearComplexity.triad u₃ v₃ w₃ +
        BilinearComplexity.triad u₄ v₄ w₄)
    (hnz₂ : BilinearComplexity.triad u₂ v₂ w₂ ≠ 0)
    (hu₂ : u₂ ∉ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hu₄ : u₄ ∈ Submodule.span (ZMod 2) ({u₀, u₁} : Set (Fin a → ZMod 2)))
    (hv₂ : v₂ ∉ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2)))
    (hv₃ : v₃ ∈ Submodule.span (ZMod 2) ({v₀, v₁} : Set (Fin b → ZMod 2))) : False := by
  obtain ⟨f, hf₀, hf₁, hf₂, hf⟩ := exists_pair_annihilator_one u₀ u₁ u₂ hu₂
  obtain ⟨g, hg₀, hg₁, hg₂, hg⟩ := exists_pair_annihilator_one v₀ v₁ v₂ hv₂
  have hr := contracted_first_two_relation u₀ u₁ u₂ u₃ u₄
    v₀ v₁ v₂ v₃ v₄ w₀ w₁ w₂ w₃ w₄ h f g hf₀ hf₁ hg₀ hg₁
  have hfac₂ := factors_ne_zero_of_triad_ne_zero hnz₂
  apply hfac₂.2.2
  simpa [hf₂, hg₂, hf u₄ hu₄, hg v₃ hv₃] using hr

/-- The hypotheses of `pair_triple_span_drop` are jointly satisfiable. -/
example :
    let U : Fin 5 → Fin 2 → ZMod 2 :=
      ![![1, 0], ![0, 1], ![1, 1], ![1, 0], ![0, 1]]
    let V : Fin 5 → Fin 1 → ZMod 2 :=
      ![![1], ![1], ![1], ![1], ![1]]
    let W : Fin 5 → Fin 2 → ZMod 2 :=
      ![![1, 0], ![0, 1], ![1, 1], ![0, 1], ![1, 0]]
    (∀ i, BilinearComplexity.triad (U i) (V i) (W i) ≠ 0) ∧
      Function.Injective (fun i => BilinearComplexity.triad (U i) (V i) (W i)) ∧
      BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 2) (V 2) (W 2) +
          BilinearComplexity.triad (U 3) (V 3) (W 3) +
            BilinearComplexity.triad (U 4) (V 4) (W 4) := by
  decide

/-- Five distinct nonzero pure binary tensors in a pair-to-triple relation
have a factor coordinate where the triple-side factors lie in the pair span. -/
theorem pair_triple_span_drop {a b c : ℕ}
    (U : Fin 5 → Fin a → ZMod 2) (V : Fin 5 → Fin b → ZMod 2)
    (W : Fin 5 → Fin c → ZMod 2)
    (hnz : ∀ i, BilinearComplexity.triad (U i) (V i) (W i) ≠ 0)
    (hinj : Function.Injective fun i => BilinearComplexity.triad (U i) (V i) (W i))
    (hsum : BilinearComplexity.triad (U 0) (V 0) (W 0) +
        BilinearComplexity.triad (U 1) (V 1) (W 1) =
      BilinearComplexity.triad (U 2) (V 2) (W 2) +
        BilinearComplexity.triad (U 3) (V 3) (W 3) +
          BilinearComplexity.triad (U 4) (V 4) (W 4)) :
    (∀ i : Fin 3, U i.succ.succ ∈
      Submodule.span (ZMod 2) ({U 0, U 1} : Set (Fin a → ZMod 2))) ∨
    (∀ i : Fin 3, V i.succ.succ ∈
      Submodule.span (ZMod 2) ({V 0, V 1} : Set (Fin b → ZMod 2))) ∨
    (∀ i : Fin 3, W i.succ.succ ∈
      Submodule.span (ZMod 2) ({W 0, W 1} : Set (Fin c → ZMod 2))) := by
  classical
  by_contra hconcl
  obtain ⟨hnotU, hnotVW⟩ := not_or.mp hconcl
  obtain ⟨hnotV, hnotW⟩ := not_or.mp hnotVW
  have hfailU : ¬(U 2 ∈ Submodule.span (ZMod 2)
        ({U 0, U 1} : Set (Fin a → ZMod 2)) ∧
      U 3 ∈ Submodule.span (ZMod 2) ({U 0, U 1} : Set (Fin a → ZMod 2)) ∧
      U 4 ∈ Submodule.span (ZMod 2) ({U 0, U 1} : Set (Fin a → ZMod 2))) := by
    intro hall
    apply hnotU
    intro i
    fin_cases i
    · simpa using hall.1
    · simpa using hall.2.1
    · simpa using hall.2.2
  have hfailV : ¬(V 2 ∈ Submodule.span (ZMod 2)
        ({V 0, V 1} : Set (Fin b → ZMod 2)) ∧
      V 3 ∈ Submodule.span (ZMod 2) ({V 0, V 1} : Set (Fin b → ZMod 2)) ∧
      V 4 ∈ Submodule.span (ZMod 2) ({V 0, V 1} : Set (Fin b → ZMod 2))) := by
    intro hall
    apply hnotV
    intro i
    fin_cases i
    · simpa using hall.1
    · simpa using hall.2.1
    · simpa using hall.2.2
  have hfailW : ¬(W 2 ∈ Submodule.span (ZMod 2)
        ({W 0, W 1} : Set (Fin c → ZMod 2)) ∧
      W 3 ∈ Submodule.span (ZMod 2) ({W 0, W 1} : Set (Fin c → ZMod 2)) ∧
      W 4 ∈ Submodule.span (ZMod 2) ({W 0, W 1} : Set (Fin c → ZMod 2))) := by
    intro hall
    apply hnotW
    intro i
    fin_cases i
    · simpa using hall.1
    · simpa using hall.2.1
    · simpa using hall.2.2
  have hne (i j : Fin 5) (hij : i ≠ j) :
      BilinearComplexity.triad (U i) (V i) (W i) ≠
        BilinearComplexity.triad (U j) (V j) (W j) := by
    intro heq
    exact hij (hinj heq)
  have hne₀₁ := hne 0 1 (by decide)
  have hU := exactly_two_outside_first (U 0) (U 1) (U 2) (U 3) (U 4)
    (V 0) (V 1) (V 2) (V 3) (V 4) (W 0) (W 1) (W 2) (W 3) (W 4)
    hsum (hnz 2) (hnz 3) (hnz 4) hne₀₁ hfailU hfailV hfailW
  have hswap : BilinearComplexity.triad (V 0) (U 0) (W 0) +
        BilinearComplexity.triad (V 1) (U 1) (W 1) =
      BilinearComplexity.triad (V 2) (U 2) (W 2) +
        BilinearComplexity.triad (V 3) (U 3) (W 3) +
          BilinearComplexity.triad (V 4) (U 4) (W 4) := by
    ext j i k
    have hijk := congrFun (congrFun (congrFun hsum i) j) k
    simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hijk
  have hnzswap (i : Fin 5) : BilinearComplexity.triad (V i) (U i) (W i) ≠ 0 := by
    intro hz
    apply hnz i
    ext x y z
    have hzyxz := congrFun (congrFun (congrFun hz y) x) z
    simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using hzyxz
  have hne₀₁swap : BilinearComplexity.triad (V 0) (U 0) (W 0) ≠
      BilinearComplexity.triad (V 1) (U 1) (W 1) := by
    intro heq
    apply hne₀₁
    ext i j k
    have heqjik := congrFun (congrFun (congrFun heq j) i) k
    simpa [BilinearComplexity.triad, mul_assoc, mul_left_comm, mul_comm] using heqjik
  have hV := exactly_two_outside_first (V 0) (V 1) (V 2) (V 3) (V 4)
    (U 0) (U 1) (U 2) (U 3) (U 4) (W 0) (W 1) (W 2) (W 3) (W 4)
    hswap (hnzswap 2) (hnzswap 3) (hnzswap 4) hne₀₁swap hfailV hfailU hfailW
  rcases hU with hU₂₃ | hU₂₄ | hU₃₄ <;>
    rcases hV with hV₂₃ | hV₂₄ | hV₃₄
  · exact same_two_outside_modes_impossible
      (U 0) (U 1) (U 2) (U 3) (U 4)
      (V 0) (V 1) (V 2) (V 3) (V 4)
      (W 0) (W 1) (W 2) (W 3) (W 4) hsum (hnz 2) (hnz 3)
      (hne 2 3 (by decide)) hU₂₃.1 hU₂₃.2.2 hV₂₃.1 hV₂₃.2.2
  · exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 2) (U 3) (U 4)
      (V 0) (V 1) (V 2) (V 3) (V 4)
      (W 0) (W 1) (W 2) (W 3) (W 4) hsum (hnz 2)
      hU₂₃.1 hU₂₃.2.2 hV₂₄.1 hV₂₄.2.1
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 3) (V 3) (W 3) +
          BilinearComplexity.triad (U 2) (V 2) (W 2) +
            BilinearComplexity.triad (U 4) (V 4) (W 4) := by
      rw [hsum]
      abel
    exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 3) (U 2) (U 4)
      (V 0) (V 1) (V 3) (V 2) (V 4)
      (W 0) (W 1) (W 3) (W 2) (W 4) hperm (hnz 3)
      hU₂₃.2.1 hU₂₃.2.2 hV₃₄.2.1 hV₃₄.1
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 2) (V 2) (W 2) +
          BilinearComplexity.triad (U 4) (V 4) (W 4) +
            BilinearComplexity.triad (U 3) (V 3) (W 3) := by
      rw [hsum]
      abel
    exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 2) (U 4) (U 3)
      (V 0) (V 1) (V 2) (V 4) (V 3)
      (W 0) (W 1) (W 2) (W 4) (W 3) hperm (hnz 2)
      hU₂₄.1 hU₂₄.2.1 hV₂₃.1 hV₂₃.2.2
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 2) (V 2) (W 2) +
          BilinearComplexity.triad (U 4) (V 4) (W 4) +
            BilinearComplexity.triad (U 3) (V 3) (W 3) := by
      rw [hsum]
      abel
    exact same_two_outside_modes_impossible
      (U 0) (U 1) (U 2) (U 4) (U 3)
      (V 0) (V 1) (V 2) (V 4) (V 3)
      (W 0) (W 1) (W 2) (W 4) (W 3) hperm (hnz 2) (hnz 4)
      (hne 2 4 (by decide)) hU₂₄.1 hU₂₄.2.1 hV₂₄.1 hV₂₄.2.1
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 4) (V 4) (W 4) +
          BilinearComplexity.triad (U 2) (V 2) (W 2) +
            BilinearComplexity.triad (U 3) (V 3) (W 3) := by
      rw [hsum]
      abel
    exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 4) (U 2) (U 3)
      (V 0) (V 1) (V 4) (V 2) (V 3)
      (W 0) (W 1) (W 4) (W 2) (W 3) hperm (hnz 4)
      hU₂₄.2.2 hU₂₄.2.1 hV₃₄.2.2 hV₃₄.1
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 3) (V 3) (W 3) +
          BilinearComplexity.triad (U 4) (V 4) (W 4) +
            BilinearComplexity.triad (U 2) (V 2) (W 2) := by
      rw [hsum]
      abel
    exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 3) (U 4) (U 2)
      (V 0) (V 1) (V 3) (V 4) (V 2)
      (W 0) (W 1) (W 3) (W 4) (W 2) hperm (hnz 3)
      hU₃₄.2.1 hU₃₄.1 hV₂₃.2.1 hV₂₃.2.2
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 4) (V 4) (W 4) +
          BilinearComplexity.triad (U 3) (V 3) (W 3) +
            BilinearComplexity.triad (U 2) (V 2) (W 2) := by
      rw [hsum]
      abel
    exact crossing_two_outside_modes_impossible
      (U 0) (U 1) (U 4) (U 3) (U 2)
      (V 0) (V 1) (V 4) (V 3) (V 2)
      (W 0) (W 1) (W 4) (W 3) (W 2) hperm (hnz 4)
      hU₃₄.2.2 hU₃₄.1 hV₂₄.2.2 hV₂₄.2.1
  · have hperm : BilinearComplexity.triad (U 0) (V 0) (W 0) +
          BilinearComplexity.triad (U 1) (V 1) (W 1) =
        BilinearComplexity.triad (U 3) (V 3) (W 3) +
          BilinearComplexity.triad (U 4) (V 4) (W 4) +
            BilinearComplexity.triad (U 2) (V 2) (W 2) := by
      rw [hsum]
      abel
    exact same_two_outside_modes_impossible
      (U 0) (U 1) (U 3) (U 4) (U 2)
      (V 0) (V 1) (V 3) (V 4) (V 2)
      (W 0) (W 1) (W 3) (W 4) (W 2) hperm (hnz 3) (hnz 4)
      (hne 3 4 (by decide)) hU₃₄.2.1 hU₃₄.1 hV₃₄.2.1 hV₃₄.1

#check @pair_triple_span_drop
#print axioms pair_triple_span_drop

end BilinearComplexity.PairTripleSpan
