import BilinearComplexity.SchemeReplacement
import Mathlib.Data.Multiset.Basic
import Mathlib.Logic.Relation

set_option autoImplicit false

/-!
# Exact move algebra for rank-one tensor decompositions

This file is a theorem-oriented scaffold for a future completeness theory of local moves on
rank-one tensor decompositions.  It deliberately separates four notions that are easy to
conflate in implementations and in the flip-graph literature:

1. a **decomposition** is a finite multiset of rank-one terms;
2. an **exact relation** is an equality between the tensors represented by two decompositions;
3. an oriented **move** applies one side of a relation inside a larger multiset context;
4. a **path** is a sequence of moves through decomposition states.

The decomposition carrier is a free commutative monoid.  It has no syntactic subtraction and
no elementwise inverses.  A relation may be read in the opposite direction because tensor
equality is symmetric, not because a decomposition has a monoid inverse.  In particular, the
historical operation often called “inverse Plus” should eventually be exposed as the
`3 → 2` contraction orientation of the same relation whose Plus expansion has orientation
`2 → 3`.

The semantic model alone is not a search algorithm.  A useful move system needs a family of
generators and a completeness theorem.  The strongest global goal says that contextual paths
generated by the family present the kernel congruence of tensor evaluation.  A more realistic
computational goal fixes a target tensor, coefficient domain, admissibility predicate, and
term-count ceiling, then proves connectivity or goal reachability without leaving that closed
space.

The declarations below distinguish:

* soundness of individual generators;
* one-step coverage of a local relation class;
* path generation of a local relation class;
* presentation of the full evaluation kernel;
* connectivity inside a restricted search space;
* completeness of a successor enumerator;
* reachability of a lower-term-count goal from a specified start.

Circuits are represented as reduced exact relations minimal under taking submultisets on both
sides, allowing the empty subrelation and excluding zero evaluated occurrences.  This is a
positive, coefficient-absorbed model: over a field, a nonzero scalar coefficient can be
absorbed into one factor of a rank-one term.  It is not yet a complete formalization of
projective Segre circuits over arbitrary rings.  In particular, the assertion that every linear
dependence is a linear combination of circuits does not by itself provide a legal path through
normalized, distinct, or term-count-bounded decomposition states.

No declaration in this file claims that Flip, Split, Plus, or shared-factor reduction is a
complete operation set.  `SupportFiveClassificationGoal`, `PresentsKernel`, and the bounded M4
goals package those missing claims as propositions to be proved or refuted.  The generic
lemmas are intentionally left as `sorry` obligations so the file can serve as a durable map of
the theory before implementation choices harden.

Relevant primary sources include Kauers--Moosbauer, *Flip Graphs for Matrix Multiplication*,
arXiv:2212.01175, and Arai--Ichikawa--Hukushima, *Adaptive Flip Graph Algorithm for Matrix
Multiplication*, arXiv:2312.16960.  Their connectivity statements must not be read as bounded
connectivity near rank 47 without an additional intermediate-term-count theorem.
-/

namespace BilinearComplexity
namespace Scheme
namespace MoveAlgebra

variable {k : Type*} {a b c : ℕ}

/-! ## Decompositions as an inverse-free commutative monoid -/

/-- A decomposition is a finite multiset of stored rank-one factor triples.  Multiplicity is
operational data: even when two occurrences cancel after evaluation in finite characteristic,
they remain two occurrences in this free commutative monoid. -/
abbrev Decomposition (k : Type*) (a b c : ℕ) :=
  Multiset (TriadData k a b c)

/-- Evaluate a decomposition by summing all of its rank-one tensors with multiplicity. -/
def evaluate [CommSemiring k] (D : Decomposition k a b c) : Tensor k a b c :=
  (D.map fun t => t.eval).sum

/-- The displayed term count of a decomposition.  This is not an assertion of minimal tensor
rank. -/
def termCount (D : Decomposition k a b c) : ℕ :=
  D.card

/-- The empty decomposition evaluates to the zero tensor. -/
@[simp] theorem evaluate_zero [CommSemiring k] :
    evaluate (0 : Decomposition k a b c) = 0 := by
  sorry

/-- Multiset addition is interpreted as addition of represented tensors. -/
@[simp] theorem evaluate_add [CommSemiring k] (L R : Decomposition k a b c) :
    evaluate (L + R) = evaluate L + evaluate R := by
  sorry

/-- Displayed term count is additive under multiset addition. -/
@[simp] theorem termCount_add (L R : Decomposition k a b c) :
    termCount (L + R) = termCount L + termCount R := by
  sorry

/-- The decomposition monoid is conical: two positive multisets cannot add to the empty
multiset unless both were already empty.  This is the precise inverse-free fact that would be
lost by replacing decompositions with a free abelian group. -/
theorem add_eq_zero_iff (L R : Decomposition k a b c) :
    L + R = 0 ↔ L = 0 ∧ R = 0 := by
  sorry

/-- Tensor evaluation as an additive-monoid homomorphism.  This packages the semantic map whose
kernel congruence a complete move family must present. -/
def evaluationHom [CommSemiring k] :
    Decomposition k a b c →+ Tensor k a b c where
  toFun := evaluate
  map_zero' := evaluate_zero
  map_add' := evaluate_add

/-- Equality in the kernel relation of tensor evaluation. -/
def KernelRelated [CommSemiring k]
    (L R : Decomposition k a b c) : Prop :=
  evaluationHom L = evaluationHom R

/-! ## Exact local relations and their orientations -/

/-- An exact relation stores two decomposition fragments and proof that they evaluate to the
same tensor.  `left` and `right` are not positive and negative elements of a group; they are
two elements of the decomposition monoid related by the kernel congruence of `evaluate`. -/
structure ExactRelation (k : Type*) [CommSemiring k] (a b c : ℕ) where
  /-- The fragment conventionally used as the source orientation. -/
  left : Decomposition k a b c
  /-- The fragment conventionally used as the target orientation. -/
  right : Decomposition k a b c
  /-- Exact equality of represented local tensors. -/
  tensor_eq : evaluate left = evaluate right

namespace ExactRelation

variable [CommSemiring k]

/-- Read an exact relation in the opposite direction.  This is a converse orientation, not a
monoid inverse. -/
def converse (W : ExactRelation k a b c) : ExactRelation k a b c where
  left := W.right
  right := W.left
  tensor_eq := W.tensor_eq.symm

/-- Reversing the orientation twice recovers the original relation witness. -/
@[simp] theorem converse_converse (W : ExactRelation k a b c) :
    W.converse.converse = W := by
  sorry

/-- Number of terms on the source side of the chosen orientation. -/
def inputArity (W : ExactRelation k a b c) : ℕ :=
  termCount W.left

/-- Number of terms on the target side of the chosen orientation. -/
def outputArity (W : ExactRelation k a b c) : ℕ :=
  termCount W.right

/-- The occurrence-level support of a relation witness.  This retains multiplicity and is not
yet quotient support in projective Segre space. -/
def occurrenceSupport (W : ExactRelation k a b c) : Decomposition k a b c :=
  W.left + W.right

/-- Total occurrence count on both sides.  For a reduced generic Plus relation this is five,
although Plus has input/output arity `2 → 3` and may factor as a two-edge path.  This is distinct
from the cardinality of projective relation support when repeated or refactorized terms occur. -/
def supportSize (W : ExactRelation k a b c) : ℕ :=
  termCount W.occurrenceSupport

/-- Signed change in displayed term count. -/
def termCountChange (W : ExactRelation k a b c) : ℤ :=
  Int.ofNat W.outputArity - Int.ofNat W.inputArity

/-- A relation orientation increases displayed term count. -/
def IsExpansion (W : ExactRelation k a b c) : Prop :=
  W.inputArity < W.outputArity

/-- A relation orientation decreases displayed term count. -/
def IsContraction (W : ExactRelation k a b c) : Prop :=
  W.outputArity < W.inputArity

/-- A relation orientation preserves displayed term count. -/
def IsBalanced (W : ExactRelation k a b c) : Prop :=
  W.inputArity = W.outputArity

/-- The two sides have no common stored occurrence.  Removing common occurrences is syntactic
cancellation in a relation witness, not introduction of inverses into the decomposition monoid. -/
def IsReduced (W : ExactRelation k a b c) : Prop :=
  Disjoint W.left W.right

/-- Every stored occurrence on both sides evaluates to a nonzero tensor.  This excludes
one-term zero artifacts from the circuit vocabulary without quotienting projectively equal
factor triples. -/
def HasNonzeroTerms (W : ExactRelation k a b c) : Prop :=
  (∀ t, t ∈ W.left → t.eval ≠ 0) ∧ (∀ t, t ∈ W.right → t.eval ≠ 0)

/-- A positive circuit is a reduced exact relation with nonempty, nonzero-supported sides and
no exact subrelation other than the empty relation and itself.  Empty-sided subrelations must
be tested: in positive characteristic a nonempty submultiset can evaluate to zero.  This still
uses stored occurrences rather than projective rank-one directions; a later normalized carrier
is needed for a literal Segre-circuit classification. -/
def IsCircuit (W : ExactRelation k a b c) : Prop :=
  W.IsReduced ∧ W.HasNonzeroTerms ∧ W.left ≠ 0 ∧ W.right ≠ 0 ∧
    ∀ L R, L ≤ W.left → R ≤ W.right → evaluate L = evaluate R →
      (L = 0 ∧ R = 0) ∨ (L = W.left ∧ R = W.right)

/-- Contextualizing both sides by the same decomposition gives another exact relation. -/
def inContext (C : Decomposition k a b c) (W : ExactRelation k a b c) :
    ExactRelation k a b c where
  left := C + W.left
  right := C + W.right
  tensor_eq := by
    sorry

/-- Independent exact relations can be applied in parallel by adding their two source and
target fragments. -/
def parallel (W Q : ExactRelation k a b c) : ExactRelation k a b c where
  left := W.left + Q.left
  right := W.right + Q.right
  tensor_eq := by
    sorry

/-- Converse exchanges input and output arities. -/
@[simp] theorem inputArity_converse (W : ExactRelation k a b c) :
    W.converse.inputArity = W.outputArity := by
  sorry

/-- Converse negates displayed term-count change. -/
@[simp] theorem termCountChange_converse (W : ExactRelation k a b c) :
    W.converse.termCountChange = -W.termCountChange := by
  sorry

end ExactRelation

/-! ## Bridge to ordered schemes and replacement certificates -/

/-- Forget the operational slot order of an existing `Scheme` while retaining every stored
occurrence.  The bridge is deliberately one-way: reconstructing an ordered scheme requires a
choice of enumeration. -/
def ofScheme {r : ℕ} (S : Scheme k a b c r) : Decomposition k a b c :=
  (List.ofFn S.term : Multiset (TriadData k a b c))

/-- The multiset bridge evaluates to the existing ordered scheme tensor. -/
theorem evaluate_ofScheme [CommSemiring k] {r : ℕ} (S : Scheme k a b c r) :
    evaluate (ofScheme S) = S.sumTensor := by
  sorry

/-- Forgetting order preserves the displayed number of occurrences. -/
@[simp] theorem termCount_ofScheme {r : ℕ} (S : Scheme k a b c r) :
    termCount (ofScheme S) = r := by
  sorry

/-- The multiset of terms selected by concrete ordered slots. -/
def selectedDecomposition {r : ℕ} (S : Scheme k a b c r) (I : Finset (Fin r)) :
    Decomposition k a b c :=
  I.1.map S.term

/-- The multiset underlying an ordered insertion payload. -/
def insertedDecomposition (L : List (TriadData k a b c)) : Decomposition k a b c :=
  (L : Multiset (TriadData k a b c))

/-- The selected-fragment bridge agrees with `Replacement.selectedTensor`. -/
theorem evaluate_selectedDecomposition [CommSemiring k] {r : ℕ}
    (S : Scheme k a b c r) (I : Finset (Fin r)) :
    evaluate (selectedDecomposition S I) = Replacement.selectedTensor S I := by
  sorry

/-- The insertion-list bridge agrees with `Replacement.insertedTensor`. -/
theorem evaluate_insertedDecomposition [CommSemiring k]
    (L : List (TriadData k a b c)) :
    evaluate (insertedDecomposition L) = Replacement.insertedTensor L := by
  sorry

/-- The exact local relation carried by an existing replacement certificate.  Slot and list
order are forgotten only at this semantic boundary; the certificate itself remains available
for deterministic replay. -/
def relationOfCertificate [CommSemiring k] {r : ℕ} {S : Scheme k a b c r}
    (C : Replacement.Certificate S) : ExactRelation k a b c where
  left := selectedDecomposition S C.removed
  right := insertedDecomposition C.inserted
  tensor_eq := by
    sorry

/-- Certificate removal count is the source arity of its induced relation. -/
@[simp] theorem inputArity_relationOfCertificate [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C : Replacement.Certificate S) :
    (relationOfCertificate C).inputArity = C.removed.card := by
  sorry

/-- Certificate insertion-list length is the target arity of its induced relation. -/
@[simp] theorem outputArity_relationOfCertificate [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C : Replacement.Certificate S) :
    (relationOfCertificate C).outputArity = C.inserted.length := by
  sorry

/-- The untouched context of a certificate consists of the terms in complementary source
slots. -/
def contextOfCertificate [CommSemiring k] {r : ℕ} {S : Scheme k a b c r}
    (C : Replacement.Certificate S) : Decomposition k a b c :=
  selectedDecomposition S C.removedᶜ

/-- Forgetting order decomposes the certificate source into untouched context and removed
fragment.  The equality is multiset equality, so no survivor-order statement is hidden here. -/
theorem ofScheme_eq_context_add_removed [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C : Replacement.Certificate S) :
    ofScheme S = contextOfCertificate C + (relationOfCertificate C).left := by
  sorry

/-- Forgetting order decomposes deterministic certificate output into the same untouched
context and the inserted fragment. -/
theorem ofScheme_output_eq_context_add_inserted [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C : Replacement.Certificate S) :
    ofScheme C.output = contextOfCertificate C + (relationOfCertificate C).right := by
  sorry

/-! ## Move families, contextual steps, and path length -/

/-- A move family is an oriented relation on decomposition fragments.  Soundness is kept as a
separate proposition so an experimental recognizer cannot acquire correctness by construction. -/
abbrev MoveFamily (k : Type*) (a b c : ℕ) :=
  Decomposition k a b c → Decomposition k a b c → Prop

/-- One move family is extensionally contained in another. -/
def FamilyContained (G H : MoveFamily k a b c) : Prop :=
  ∀ ⦃L R⦄, G L R → H L R

/-- Every move recognized by a family preserves the represented local tensor. -/
def Sound [CommSemiring k] (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃L R⦄, G L R → evaluate L = evaluate R

/-- Reverse every recognized orientation. -/
def converseFamily (G : MoveFamily k a b c) : MoveFamily k a b c :=
  fun L R => G R L

/-- Expose both orientations of every recognized relation. -/
def symmetrize (G : MoveFamily k a b c) : MoveFamily k a b c :=
  fun L R => G L R ∨ G R L

/-- The universal family of all exact fragment replacements.  It is complete by definition but
not computationally useful: enumerating it is the original tensor-decomposition problem. -/
def allExactMoves [CommSemiring k] : MoveFamily k a b c :=
  fun L R => evaluate L = evaluate R

/-- A local move applies inside an arbitrary common multiset context. -/
def ContextualStep (G : MoveFamily k a b c) :
    Decomposition k a b c → Decomposition k a b c → Prop :=
  fun S T => ∃ C L R, G L R ∧ S = C + L ∧ T = C + R

/-- Local relations realized by the existing ordered replacement-certificate API.  The source
scheme, selected slots, and insertion list remain existential witnesses rather than being
erased from the operational layer. -/
def certificateMoves [CommSemiring k] : MoveFamily k a b c :=
  fun L R => ∃ (r : ℕ) (S : Scheme k a b c r) (C : Replacement.Certificate S),
    selectedDecomposition S C.removed = L ∧ insertedDecomposition C.inserted = R

/-- Every certificate-realized local relation is exact. -/
theorem sound_certificateMoves [CommSemiring k] :
    Sound (certificateMoves : MoveFamily k a b c) := by
  sorry

/-- Replaying an existing certificate induces one contextual move after forgetting slot order.
This is the principal bridge from `Replacement.Certificate` to the abstract move algebra. -/
theorem certificate_contextualStep [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C : Replacement.Certificate S) :
    ContextualStep certificateMoves (ofScheme S) (ofScheme C.output) := by
  sorry

/-- An exact-length path counts edges, not states or participating circuit terms.  A path of
length four has five successive states. -/
inductive Path (G : MoveFamily k a b c) :
    ℕ → Decomposition k a b c → Decomposition k a b c → Prop
  /-- A zero-edge path stays at its initial state. -/
  | refl (S : Decomposition k a b c) : Path G 0 S S
  /-- Append one contextual edge to an existing path. -/
  | tail {n : ℕ} {S R T : Decomposition k a b c} :
      Path G n S R → ContextualStep G R T → Path G (n + 1) S T

/-- Two sequential ordered certificates become a two-edge abstract path.  Certificate
composition retains transport and output-order data; this statement records only the induced
semantic path after order is forgotten. -/
theorem certificate_composition_path [CommSemiring k]
    {r : ℕ} {S : Scheme k a b c r} (C₁ : Replacement.Certificate S)
    (C₂ : Replacement.Certificate C₁.output) :
    Path certificateMoves 2 (ofScheme S) (ofScheme C₂.output) := by
  sorry

/-- Reachability forgets the exact number of edges. -/
def Reachable (G : MoveFamily k a b c)
    (S T : Decomposition k a b c) : Prop :=
  Relation.ReflTransGen (ContextualStep G) S T

/-- Every exact-length path gives ordinary reflexive-transitive reachability. -/
theorem Path.reachable {G : MoveFamily k a b c} {n : ℕ}
    {S T : Decomposition k a b c} (h : Path G n S T) : Reachable G S T := by
  sorry

/-- Every finite reachable path has some edge count. -/
theorem reachable_iff_exists_path {G : MoveFamily k a b c}
    {S T : Decomposition k a b c} :
    Reachable G S T ↔ ∃ n, Path G n S T := by
  sorry

/-- Soundness survives reversal of orientation because exact tensor equality is symmetric. -/
theorem Sound.converseFamily [CommSemiring k] {G : MoveFamily k a b c}
    (hG : Sound G) : Sound (converseFamily G) := by
  sorry

/-- Soundness survives exposing both orientations. -/
theorem Sound.symmetrize [CommSemiring k] {G : MoveFamily k a b c}
    (hG : Sound G) : Sound (symmetrize G) := by
  sorry

/-- A contextual application of a sound local family preserves the represented tensor. -/
theorem Sound.contextualStep [CommSemiring k] {G : MoveFamily k a b c}
    (hG : Sound G) {S T : Decomposition k a b c}
    (hstep : ContextualStep G S T) : evaluate S = evaluate T := by
  sorry

/-- Every path generated by sound moves preserves the represented tensor. -/
theorem Sound.reachable [CommSemiring k] {G : MoveFamily k a b c}
    (hG : Sound G) {S T : Decomposition k a b c}
    (hpath : Reachable G S T) : evaluate S = evaluate T := by
  sorry

/-- A macro family factors through two atomic families when every macro edge has an
intermediate decomposition reached by a contextual `G` step followed by a contextual `H`
step.  Context is essential: a Split implementing a `2 → 3` Plus macro normally acts on only
one of the two source terms. -/
def FactorsThrough (Macro G H : MoveFamily k a b c) : Prop :=
  ∀ ⦃L R⦄, Macro L R →
    ∃ M, ContextualStep G L M ∧ ContextualStep H M R

/-- A two-stage local factorization yields a two-edge path in the union of its atomic families. -/
theorem path_two_of_factorsThrough {Macro G H : MoveFamily k a b c}
    (hfactor : FactorsThrough Macro G H) {L R : Decomposition k a b c}
    (hmove : Macro L R) :
    Path (fun S T => G S T ∨ H S T) 2 L R := by
  sorry

/-! ## Kernel presentations and local completeness -/

/-- Contextual paths after symmetrizing the generators.  This is the operational congruence
generated by a family of equations. -/
def congruenceGenerated (G : MoveFamily k a b c)
    (L R : Decomposition k a b c) : Prop :=
  Reachable (symmetrize G) L R

/-- An equivalence relation compatible with adding a common decomposition context.  Because the
carrier monoid is commutative, one-sided contextual compatibility is full monoid-congruence
compatibility. -/
def IsMonoidCongruence (E : MoveFamily k a b c) : Prop :=
  (∀ D, E D D) ∧
    (∀ ⦃L R⦄, E L R → E R L) ∧
    (∀ ⦃L R Q⦄, E L R → E R Q → E L Q) ∧
    (∀ C ⦃L R⦄, E L R → E (C + L) (C + R))

/-- The operationally generated relation is a decomposition-monoid congruence. -/
theorem isMonoidCongruence_congruenceGenerated (G : MoveFamily k a b c) :
    IsMonoidCongruence (congruenceGenerated G) := by
  sorry

/-- Every generator edge belongs to its generated congruence. -/
theorem generator_le_congruenceGenerated {G : MoveFamily k a b c}
    {L R : Decomposition k a b c} (h : G L R) :
    congruenceGenerated G L R := by
  sorry

/-- Generated congruence is least among monoid congruences containing the generators. -/
theorem congruenceGenerated_least {G E : MoveFamily k a b c}
    (hE : IsMonoidCongruence E) (hcontains : FamilyContained G E)
    {L R : Decomposition k a b c} (h : congruenceGenerated G L R) : E L R := by
  sorry

/-- Equality under tensor evaluation is a decomposition-monoid congruence. -/
theorem isMonoidCongruence_kernel [CommSemiring k] :
    IsMonoidCongruence (KernelRelated : MoveFamily k a b c) := by
  sorry

/-- A family presents the evaluation kernel when generated contextual equivalence is exactly
equality of represented tensors.  This is the strongest global move-completeness goal. -/
def PresentsKernel [CommSemiring k] (G : MoveFamily k a b c) : Prop :=
  ∀ L R, congruenceGenerated G L R ↔ evaluate L = evaluate R

/-- A class of local relations is covered in one step when every pair in the class is directly
recognized by the generator family. -/
def OneStepCompleteFor (G C : MoveFamily k a b c) : Prop :=
  ∀ ⦃L R⦄, C L R → G L R

/-- A class of local relations is generated by paths when every pair in the class is connected
by contextual generator steps, possibly through auxiliary decompositions. -/
def PathCompleteFor (G C : MoveFamily k a b c) : Prop :=
  ∀ ⦃L R⦄, C L R → Reachable G L R

/-- Exact relations whose two displayed sides together use at most `q` occurrences. -/
def ExactSupportAtMost [CommSemiring k] (q : ℕ) : MoveFamily k a b c :=
  fun L R => evaluate L = evaluate R ∧ termCount L + termCount R ≤ q

/-- Directed path completeness for every exact relation up to a total occurrence bound.  It
is useful when a family deliberately records both orientations. -/
def DirectedLocallyComplete [CommSemiring k]
    (G : MoveFamily k a b c) (q : ℕ) : Prop :=
  PathCompleteFor G (ExactSupportAtMost q)

/-- Unoriented local completeness for every exact relation up to a total occurrence bound.
This statement allows auxiliary states outside that support bound; bounded auxiliary support
is a separate and strictly stronger obligation. -/
def LocallyComplete [CommSemiring k] (G : MoveFamily k a b c) (q : ℕ) : Prop :=
  PathCompleteFor (symmetrize G) (ExactSupportAtMost q)

/-- One-step completeness implies path completeness for the same relation class. -/
theorem OneStepCompleteFor.pathComplete {G C : MoveFamily k a b c}
    (h : OneStepCompleteFor G C) : PathCompleteFor G C := by
  sorry

/-- A sound family presents the kernel exactly when its symmetrized paths are complete for all
exact relations. -/
theorem presentsKernel_iff [CommSemiring k] {G : MoveFamily k a b c}
    (hG : Sound G) :
    PresentsKernel G ↔ PathCompleteFor (symmetrize G) allExactMoves := by
  sorry

/-! ## Circuits and low-support classification goals -/

/-- The oriented family consisting of all positive circuits in the scaffold's minimal-support
sense. -/
def circuitMoves [CommSemiring k] : MoveFamily k a b c :=
  fun L R => ∃ W : ExactRelation k a b c,
    W.left = L ∧ W.right = R ∧ W.IsCircuit

/-- Circuit moves are sound by construction. -/
theorem sound_circuitMoves [CommSemiring k] :
    Sound (circuitMoves : MoveFamily k a b c) := by
  sorry

/-- Every recognized relation in a family has the stated source and target arity. -/
def HasArity (G : MoveFamily k a b c) (input output : ℕ) : Prop :=
  ∀ ⦃L R⦄, G L R → termCount L = input ∧ termCount R = output

/-- Named historical move strata.  These fields are predicates rather than constructors so the
future formalization can distinguish mathematical applicability from executable enumeration. -/
structure HistoricalFamilies (k : Type*) (a b c : ℕ) where
  /-- Split orientation of a one-versus-two shared-factor relation. -/
  split : MoveFamily k a b c
  /-- Ordinary balanced two-versus-two flip relations. -/
  flip : MoveFamily k a b c
  /-- Historical Plus expansion relations. -/
  plusExpand : MoveFamily k a b c
  /-- Plus contraction, historically called inverse Plus. -/
  plusContract : MoveFamily k a b c
  /-- Full shared-factor complementary-rank relations. -/
  sharedFactor : MoveFamily k a b c
  /-- Additional circuit relations not represented by the named templates. -/
  otherCircuit : MoveFamily k a b c

namespace HistoricalFamilies

/-- Union of all currently distinguished historical and residual circuit strata. -/
def all (H : HistoricalFamilies k a b c) : MoveFamily k a b c :=
  fun L R => H.split L R ∨ H.flip L R ∨ H.plusExpand L R ∨
    H.plusContract L R ∨ H.sharedFactor L R ∨ H.otherCircuit L R

/-- Plus expansion and contraction are converse orientations of one relation family.  This is a
specification obligation, not a claim about an unformalized payload. -/
def PlusOrientationsAgree (H : HistoricalFamilies k a b c) : Prop :=
  H.plusContract = converseFamily H.plusExpand

/-- Plus is a Split-then-Flip macro.  This is the relation-level factorization obligation that
should replace language suggesting a monoid inverse. -/
def PlusFactorsAsSplitThenFlip (H : HistoricalFamilies k a b c) : Prop :=
  FactorsThrough H.plusExpand H.split H.flip

/-- Semantic and arity contract for concrete historical templates over a field.  Keeping this
contract separate from the family record prevents arbitrary experimental recognizers from
silently acquiring soundness or the names Split, Flip, and Plus. -/
def Specification [Field k] (H : HistoricalFamilies k a b c) : Prop :=
  Sound H.all ∧
    HasArity H.split 1 2 ∧
    HasArity H.flip 2 2 ∧
    HasArity H.plusExpand 2 3 ∧
    HasArity H.plusContract 3 2 ∧
    H.PlusOrientationsAgree ∧
    H.PlusFactorsAsSplitThenFlip ∧
    FamilyContained H.otherCircuit circuitMoves

/-- Proposed support-five classification target.  This is the conjunction of the field-level
template contract and unoriented path completeness for all exact relations of total occurrence
count at most five.  It is deliberately stronger than classification of circuits alone: zero,
refactorization, and shared-factor degeneracies must either be generated or explicitly removed
by a future normalized carrier.  It is currently only a named proposition. -/
def SupportFiveClassificationGoal [Field k]
    (H : HistoricalFamilies k a b c) : Prop :=
  H.Specification ∧ LocallyComplete H.all 5

end HistoricalFamilies

/-! ## Restricted and bounded search spaces -/

/-- Every stored occurrence evaluates to a nonzero tensor. -/
def NonzeroTerms [CommSemiring k] (D : Decomposition k a b c) : Prop :=
  ∀ t, t ∈ D → t.eval ≠ 0

/-- No two stored occurrences are literally equal.  Literal distinctness is weaker than
projective distinctness and weaker than distinctness of evaluated terms unless normalization
is fixed. -/
def DistinctStoredTerms (D : Decomposition k a b c) : Prop :=
  D.Nodup

/-- Evaluated rank-one tensors are pairwise distinct with multiplicity.  This is the multiset
counterpart of the injectivity clause in `Scheme.Valid`; it still does not choose canonical
factor triples for a projective tensor. -/
def DistinctEvaluatedTerms [CommSemiring k] (D : Decomposition k a b c) : Prop :=
  (D.map fun t => t.eval).Nodup

/-- A multiplicity-bearing bounded tensor fiber.  It imposes only tensor equality, nonzero
occurrences, and a displayed term-count ceiling; repeated terms remain legal states. -/
def BoundedFiber [CommSemiring k] (target : Tensor k a b c) (bound : ℕ) :
    Set (Decomposition k a b c) :=
  {D | evaluate D = target ∧ termCount D ≤ bound ∧ NonzeroTerms D}

/-- A bounded target fiber with explicit nonzero and evaluated-distinctness policy.  Future
M4 work must decide whether characteristic-two duplicate pairs are forbidden, retained as
occurrences, or normalized away; this definition chooses the validity-style square-free policy. -/
def SearchSpace [CommSemiring k] (target : Tensor k a b c) (bound : ℕ) :
    Set (Decomposition k a b c) :=
  {D | D ∈ BoundedFiber target bound ∧ DistinctEvaluatedTerms D}

/-- Add an explicit normalization predicate to the square-free bounded search space.  A
normalization policy may choose representatives of projective rank-one terms, canonicalize
factor scalings, or impose a coefficient alphabet.  Closure under moves is a separate theorem
obligation. -/
def NormalizedSearchSpace [CommSemiring k]
    (normalForm : Set (Decomposition k a b c))
    (target : Tensor k a b c) (bound : ℕ) : Set (Decomposition k a b c) :=
  {D | D ∈ SearchSpace target bound ∧ D ∈ normalForm}

/-- A valid ordered scheme belongs to the corresponding validity-style multiset search space
at its own displayed term count.  This bridges exactness, nonzero terms, and evaluated-term
injectivity without pretending that the multiset retains slot order. -/
theorem Valid.ofScheme_mem_searchSpace [CommSemiring k]
    {r : ℕ} {T : Tensor k a b c} {S : Scheme k a b c r}
    (hS : S.Valid T) : ofScheme S ∈ SearchSpace T r := by
  sorry

/-- Restrict a contextual step by demanding that both endpoints lie in the chosen state space. -/
def RestrictedStep (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) : MoveFamily k a b c :=
  fun S T => S ∈ Ω ∧ ContextualStep G S T ∧ T ∈ Ω

/-- Reachability whose every edge records membership of both endpoints in the chosen space. -/
def RestrictedReachable (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) (S T : Decomposition k a b c) : Prop :=
  Relation.ReflTransGen (RestrictedStep Ω G) S T

/-- A state space is closed under all contextual applications of a move family. -/
def ClosedUnder (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃S T⦄, S ∈ Ω → ContextualStep G S T → T ∈ Ω

/-- Local completeness restricted to an explicitly supplied admissible state space.  Both
endpoints and every path endpoint must satisfy `Ω`; unlike `LocallyComplete`, this predicate
cannot use arbitrarily large or unnormalized auxiliary states. -/
def LocallyCompleteWithin [CommSemiring k]
    (Ω : Set (Decomposition k a b c)) (G : MoveFamily k a b c) (q : ℕ) : Prop :=
  ∀ ⦃L R⦄, L ∈ Ω → R ∈ Ω → ExactSupportAtMost q L R →
    RestrictedReachable Ω (symmetrize G) L R

/-- A support-local relation can be generated without exceeding a displayed term-count ceiling.
This multiplicity-bearing version does not impose nonzero, distinctness, or normalization
conditions; use `LocallyCompleteWithin` for those stronger policies. -/
def BoundedlyLocallyComplete [CommSemiring k]
    (G : MoveFamily k a b c) (supportBound termCeiling : ℕ) : Prop :=
  ∀ ⦃L R⦄, ExactSupportAtMost supportBound L R →
    termCount L ≤ termCeiling → termCount R ≤ termCeiling →
    RestrictedReachable
      {D | evaluate D = evaluate L ∧ termCount D ≤ termCeiling}
      (symmetrize G) L R

/-- A family is complete on a state space when equal-evaluation states in that space are joined
without leaving it. -/
def CompleteOn [CommSemiring k] (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃S T⦄, S ∈ Ω → T ∈ Ω → evaluate S = evaluate T →
    RestrictedReachable Ω G S T

/-- A move graph is connected on a state space when every ordered pair of states is joined.
For a state space contained in one evaluation fiber, this is equivalent to `CompleteOn`. -/
def ConnectedOn (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃S T⦄, S ∈ Ω → T ∈ Ω → RestrictedReachable Ω G S T

/-- On a single tensor fiber, restricted completeness and graph connectivity coincide. -/
theorem completeOn_iff_connectedOn_of_constantEvaluation [CommSemiring k]
    {Ω : Set (Decomposition k a b c)} {G : MoveFamily k a b c}
    {target : Tensor k a b c}
    (hΩ : ∀ ⦃S⦄, S ∈ Ω → evaluate S = target) :
    CompleteOn Ω G ↔ ConnectedOn Ω G := by
  sorry

/-- Closure upgrades an unrestricted generated path from a state in `Ω` to a path all of whose
recorded endpoints remain in `Ω`. -/
theorem restrictedReachable_of_reachable_of_closed
    {Ω : Set (Decomposition k a b c)} {G : MoveFamily k a b c}
    (hclosed : ClosedUnder Ω G) {S T : Decomposition k a b c}
    (hS : S ∈ Ω) (hpath : Reachable G S T) :
    RestrictedReachable Ω G S T := by
  sorry

/-- Global kernel completeness implies completeness on every generator-closed subspace. -/
theorem completeOn_of_presentsKernel [CommSemiring k]
    {Ω : Set (Decomposition k a b c)} {G : MoveFamily k a b c}
    (hpresent : PresentsKernel G) (hclosed : ClosedUnder Ω (symmetrize G)) :
    CompleteOn Ω (symmetrize G) := by
  sorry

/-! ## Successor enumeration and goal-directed completeness -/

/-- A mathematical successor enumerator.  Replacing `Set` by `Finset` later will add the
computability and finite-enumeration obligations appropriate to a concrete coefficient domain. -/
abbrev Successors (k : Type*) (a b c : ℕ) :=
  Decomposition k a b c → Set (Decomposition k a b c)

/-- Every emitted successor is a legal restricted contextual step. -/
def EnumeratorSound (next : Successors k a b c)
    (Ω : Set (Decomposition k a b c)) (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃S T⦄, T ∈ next S → RestrictedStep Ω G S T

/-- Every legal restricted contextual step is emitted by the successor enumerator. -/
def EnumeratorComplete (next : Successors k a b c)
    (Ω : Set (Decomposition k a b c)) (G : MoveFamily k a b c) : Prop :=
  ∀ ⦃S T⦄, RestrictedStep Ω G S T → T ∈ next S

/-- Exact agreement between the mathematical move relation and successor enumeration. -/
def ExactEnumerator (next : Successors k a b c)
    (Ω : Set (Decomposition k a b c)) (G : MoveFamily k a b c) : Prop :=
  EnumeratorSound next Ω G ∧ EnumeratorComplete next Ω G

/-- Goal-directed completeness from one source: whenever the chosen space contains a state
below `threshold`, restricted search from `source` reaches at least one such state.  This is
weaker than connecting the entire bounded fiber and closer to the theorem needed to justify a
rank-improvement search. -/
def FindsBelow (Ω : Set (Decomposition k a b c))
    (G : MoveFamily k a b c) (source : Decomposition k a b c)
    (threshold : ℕ) : Prop :=
  source ∈ Ω ∧
    ((∃ target, target ∈ Ω ∧ termCount target < threshold) →
      ∃ target, target ∈ Ω ∧ termCount target < threshold ∧
        RestrictedReachable Ω G source target)

/-- Exact successor enumeration preserves graph reachability: any proof using the abstract
restricted step relation can in principle be replayed by the enumerator. -/
theorem exactEnumerator_replays_reachability
    {next : Successors k a b c} {Ω : Set (Decomposition k a b c)}
    {G : MoveFamily k a b c} (hexact : ExactEnumerator next Ω G)
    {S T : Decomposition k a b c} (hpath : RestrictedReachable Ω G S T) :
    Relation.ReflTransGen (fun R Q => Q ∈ next R) S T := by
  sorry

/-! ## Concrete characteristic-two M4 goals -/

/-- The normalized finite-field M4 bounded state space.  The explicit `normalForm`
predicate records the representative policy rather than silently baking one into the algebra.
This space is finite in principle because the factor spaces and term-count ceiling are finite;
no claim is made that direct enumeration is computationally feasible. -/
def M4F2SearchSpace
    (normalForm : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)))
    (bound : ℕ) : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)) :=
  NormalizedSearchSpace normalForm (matMulTensor (ZMod 2) 4 4 4) bound

/-- The normalized bounded M4 state space is finite for every normalization predicate.  This is
a finiteness statement only, not a feasible-enumeration or termination bound. -/
theorem m4F2SearchSpace_finite
    (normalForm : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)))
    (bound : ℕ) : (M4F2SearchSpace normalForm bound).Finite := by
  sorry

/-- Bounded undirected connectivity target for a proposed characteristic-two M4 move family.
The conjunction keeps generator soundness separate from path completeness.  Every intermediate
endpoint must respect the target, nonzero, distinctness, normalization, and term-count policies. -/
def M4F2BoundedCompletenessGoal
    (normalForm : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)))
    (bound : ℕ) (G : MoveFamily (ZMod 2) (4 * 4) (4 * 4) (4 * 4)) : Prop :=
  Sound G ∧ ConnectedOn (M4F2SearchSpace normalForm bound) (symmetrize G)

/-- Goal-directed version relevant to improving a displayed 47-term M4 scheme.  It explicitly
requires a 47-term source.  If a normalized admissible decomposition with fewer than 47 terms
exists below the chosen ceiling, symmetrized search must reach one without leaving the space. -/
def M4F2Term47ImprovementGoal
    (normalForm : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)))
    (bound : ℕ) (G : MoveFamily (ZMod 2) (4 * 4) (4 * 4) (4 * 4))
    (source : Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)) : Prop :=
  termCount source = 47 ∧ Sound G ∧
    FindsBelow (M4F2SearchSpace normalForm bound) (symmetrize G) source 47

/-- Full mathematical successor contract for the normalized bounded M4 graph.  This remains
separate from graph connectivity: exact one-step enumeration does not imply that the move
family connects the state space. -/
def M4F2EnumeratorGoal
    (normalForm : Set (Decomposition (ZMod 2) (4 * 4) (4 * 4) (4 * 4)))
    (bound : ℕ) (G : MoveFamily (ZMod 2) (4 * 4) (4 * 4) (4 * 4))
    (next : Successors (ZMod 2) (4 * 4) (4 * 4) (4 * 4)) : Prop :=
  Sound G ∧ ExactEnumerator next (M4F2SearchSpace normalForm bound) (symmetrize G)

/-!
Characteristic zero intentionally has no parallel finite-state declaration here.  Bounding
coefficient height is generally not closed under shears, refactorizations, or circuit
replacements.  A future characteristic-zero search space must therefore choose and justify one
of the following: an algebraic parameter space, a normal-form theorem, a deliberately partial
bounded-height search, or a finite coefficient alphabet together with an explicit account of
which operations leave it.
-/

/-- A non-finite bounded-connectivity proposition over a characteristic-zero field.  The
explicit normalization predicate and closure embodied by restricted reachability prevent this
statement from suggesting that a coefficient-height cutoff is automatically move-closed.  No
finiteness or executable-search claim follows from this definition. -/
def CharacteristicZeroBoundedCompletenessGoal
    [Field k] [CharZero k]
    (normalForm : Set (Decomposition k a b c)) (target : Tensor k a b c)
    (bound : ℕ) (G : MoveFamily k a b c) : Prop :=
  Sound G ∧ ConnectedOn (NormalizedSearchSpace normalForm target bound) (symmetrize G)

end MoveAlgebra
end Scheme
end BilinearComplexity
