import GroupCount.Gnu

/-!
# Hölder's classification at order `p * q`

For primes `p < q`, Hölder's classical formula is

`gnu (p * q) = if p ∣ q - 1 then 2 else 1`.

This module formalizes the classification from Mathlib's Sylow, cyclic-group, and
semidirect-product APIs.  Every Sylow `q`-subgroup of a group of order `p * q` has order
`q` and is normal.  It proves uniqueness, by order, of subgroups of a finite cyclic
group and the resulting uniqueness of injective actions of a prime cyclic group up to
an automorphism of the source.  When `p ∣ q - 1`, Cauchy's theorem supplies an
automorphism of `C_q` of order `p`; the resulting `C_q ⋊ C_p` is explicitly shown to
have order `p * q` and noncommuting elements.  These ingredients give the full formula
above.

The mathematical source is the ROUTE paragraph “Hölder’s classical formula for groups
of order `p*q`” in `Formalize/A046057-dennis-surjectivity.md`; Dennis's surjectivity
conjecture is not addressed.
-/

set_option autoImplicit false

namespace GroupCount

/-- If primes `p < q` satisfy `p ∣ q - 1`, the canonical cyclic group of order `q`
has an automorphism of order `p`; its semidirect product with the subgroup generated by
that automorphism has order `p * q` and contains two noncommuting elements. -/
theorem exists_semidirectProduct_card_mul_primes_noncommutative
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q)
    (hdvd : p ∣ q - 1) :
    ∃ (σ : MulAut (Multiplicative (ZMod q))) (_hσ : orderOf σ = p),
      let H := Subgroup.zpowers σ
      let φ : H →* MulAut (Multiplicative (ZMod q)) := H.subtype
      Nonempty (Fintype (Multiplicative (ZMod q) ⋊[φ] H)) ∧
        Nat.card (Multiplicative (ZMod q) ⋊[φ] H) = p * q ∧
        ∃ x y : Multiplicative (ZMod q) ⋊[φ] H, x * y ≠ y * x := by
  letI : NeZero q := ⟨Nat.ne_of_gt (hp.pos.trans hpq)⟩
  let N := Multiplicative (ZMod q)
  letI : Fintype N := inferInstanceAs (Fintype (Multiplicative (ZMod q)))
  have hNcard : Nat.card N = q :=
    (Nat.card_congr Multiplicative.toAdd).trans (Nat.card_zmod q)
  letI : Fact p.Prime := ⟨hp⟩
  have hcardAut : Nat.card (MulAut N) = q - 1 := by
    rw [IsCyclic.card_mulAut, hNcard, Nat.totient_prime hq]
  obtain ⟨σ, hσ⟩ := exists_prime_orderOf_dvd_card' (G := MulAut N) p
    (hcardAut ▸ hdvd)
  refine ⟨σ, hσ, ?_⟩
  let H := Subgroup.zpowers σ
  let φ : H →* MulAut N := H.subtype
  have hHcard : Nat.card H = p := by
    rw [Nat.card_zpowers, hσ]
  constructor
  · exact ⟨Fintype.ofEquiv (N × H) SemidirectProduct.equivProd.symm⟩
  constructor
  · rw [SemidirectProduct.card, hNcard, hHcard, Nat.mul_comm]
  · have hσ_ne : σ ≠ 1 := by
      intro heq
      rw [heq, orderOf_one] at hσ
      exact hp.ne_one hσ.symm
    obtain ⟨n, hn⟩ : ∃ n : N, σ n ≠ n := by
      by_contra hnone
      apply hσ_ne
      apply DFunLike.ext σ 1
      intro n
      exact Classical.not_not.mp ((not_exists.mp hnone) n)
    let s : H := ⟨σ, Subgroup.mem_zpowers σ⟩
    let x : N ⋊[φ] H := SemidirectProduct.inr s
    let y : N ⋊[φ] H := SemidirectProduct.inl n
    refine ⟨x, y, fun hcomm => hn ?_⟩
    have hleft := congrArg SemidirectProduct.left hcomm
    simpa [x, y, φ, s] using hleft

/-- For distinct primes `p < q`, the exponent of `q` in `p * q` is exactly one. -/
theorem factorization_mul_primes_right {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p < q) : (p * q).factorization q = 1 := by
  rw [Nat.factorization_mul_of_coprime
    (Nat.Coprime.symm (hq.coprime_iff_not_dvd.mpr ?_))]
  · rw [hp.factorization, hq.factorization]
    simp [hpq.ne]
  · exact fun hdvd => (Nat.not_le_of_lt hpq) (Nat.le_of_dvd hp.pos hdvd)

/-- In a finite group of order `p * q`, where `p < q` are prime, every Sylow
`q`-subgroup has cardinality `q`. -/
theorem sylow_card_eq_larger_prime {G : Type*} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p < q) (hcard : Nat.card G = p * q)
    (Q : Sylow q G) : Nat.card Q = q := by
  letI : Fact q.Prime := ⟨hq⟩
  rw [Sylow.card_eq_multiplicity, hcard, factorization_mul_primes_right hp hq hpq,
    pow_one]

/-- In a finite group of order `p * q`, where `p < q` are prime, every Sylow
`q`-subgroup is normal.  This is the normal Hall subgroup in Hölder's classification. -/
theorem sylow_larger_prime_normal {G : Type*} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p < q) (hcard : Nat.card G = p * q)
    (Q : Sylow q G) : Q.Normal := by
  letI : Fact q.Prime := ⟨hq⟩
  have hQ : Nat.card Q = q := sylow_card_eq_larger_prime hp hq hpq hcard Q
  have hindex : Q.index = p := by
    have hmul := Q.1.card_mul_index
    rw [hQ, hcard] at hmul
    apply Nat.eq_of_mul_eq_mul_left hq.pos
    simpa [Nat.mul_comm] using hmul
  have hdvd : Nat.card (Sylow q G) ∣ p := by
    rw [← hindex]
    exact Q.card_dvd_index
  have hone_or : Nat.card (Sylow q G) = 1 ∨ Nat.card (Sylow q G) = p :=
    (Nat.dvd_prime hp).mp hdvd
  have hone : Nat.card (Sylow q G) = 1 := by
    rcases hone_or with hone | heq
    · exact hone
    · have hmod := card_sylow_modEq_one q G
      rw [heq] at hmod
      have hpone : p = 1 := hmod.eq_of_lt_of_lt hpq hq.one_lt
      omega
  letI : Subsingleton (Sylow q G) := (Nat.card_eq_one_iff_unique.mp hone).1
  exact Q.normal_of_subsingleton

/-- Two subgroups with the same finite cardinality in a finite cyclic group are equal.
The proof explicitly identifies both with the subgroup generated by
`a ^ (Nat.card A / d)` for a generator `a` of the ambient group. -/
theorem subgroup_eq_of_isCyclic_card_eq {A : Type*} [Group A] [Finite A] [IsCyclic A]
    (S T : Subgroup A) {d : ℕ} (hd : 0 < d) (hS : Nat.card S = d)
    (hT : Nat.card T = d) : S = T := by
  obtain ⟨a, ha⟩ := IsCyclic.exists_monoid_generator (α := A)
  have hza : ∀ x : A, x ∈ Subgroup.zpowers a := by
    intro x
    rw [← (isOfFinOrder_of_finite a).mem_powers_iff_mem_zpowers]
    exact ha x
  have hoa : orderOf a = Nat.card A := orderOf_eq_card_of_forall_mem_zpowers hza
  have hddvd : d ∣ Nat.card A := hS ▸ S.card_subgroup_dvd_card
  let c := a ^ (Nat.card A / d)
  have hoc : orderOf c = d := by
    rw [orderOf_pow, hoa]
    have hdiv : Nat.card A / d ∣ Nat.card A := Nat.div_dvd_of_dvd hddvd
    rw [Nat.gcd_eq_right_iff_dvd.mpr hdiv]
    exact Nat.div_div_self hddvd Nat.card_pos.ne'
  have hcardc : Nat.card (Subgroup.zpowers c) = d := by
    rw [Nat.card_zpowers, hoc]
  have hle : ∀ U : Subgroup A, Nat.card U = d → U ≤ Subgroup.zpowers c := by
    intro U hU
    obtain ⟨u, hu⟩ := IsCyclic.exists_generator (α := U)
    obtain ⟨k, hk⟩ := (Submonoid.mem_powers_iff u.1 a).mp (ha u.1)
    have hou : orderOf u.1 = d := by
      rw [Subgroup.orderOf_coe, orderOf_eq_card_of_forall_mem_zpowers hu, hU]
    have hgcd : (Nat.card A).gcd k = Nat.card A / d := by
      have heq : Nat.card A / (Nat.card A).gcd k = d := by
        rw [← hoa, ← orderOf_pow, hk, hou]
      have hgcd_dvd : (Nat.card A).gcd k ∣ Nat.card A := Nat.gcd_dvd_left _ _
      have hgcd_pos : 0 < (Nat.card A).gcd k :=
        Nat.gcd_pos_of_pos_left k Nat.card_pos
      have hmul : Nat.card A = d * (Nat.card A).gcd k :=
        (Nat.div_eq_iff_eq_mul_left hgcd_pos hgcd_dvd).mp heq
      exact ((Nat.div_eq_iff_eq_mul_left hd hddvd).mpr
        (by simpa [Nat.mul_comm] using hmul)).symm
    have hdk : Nat.card A / d ∣ k := by
      rw [← hgcd]
      exact Nat.gcd_dvd_right _ _
    have huc : u.1 ∈ Subgroup.zpowers c := by
      obtain ⟨j, rfl⟩ := hdk
      rw [← hk, pow_mul]
      change c ^ j ∈ Subgroup.zpowers c
      exact (Subgroup.zpowers c).pow_mem (Subgroup.mem_zpowers c) j
    intro x hx
    obtain ⟨z, hz⟩ := hu ⟨x, hx⟩
    have hzx : (u ^ z).1 = x := congrArg Subtype.val hz
    rw [← hzx]
    exact (Subgroup.zpowers c).zpow_mem huc z
  have hSc : S = Subgroup.zpowers c :=
    Subgroup.eq_of_le_of_card_ge (hle S hS) (by rw [hcardc, hS])
  have hTc : T = Subgroup.zpowers c :=
    Subgroup.eq_of_le_of_card_ge (hle T hT) (by rw [hcardc, hT])
  exact hSc.trans hTc.symm

/-- Two injective homomorphisms from a group of prime order into a finite cyclic group
differ by an automorphism of their common source. -/
theorem injective_hom_eq_comp_mulEquiv {K A : Type*} [Group K] [Group A]
    [Finite K] [Finite A] [IsCyclic A] {p : ℕ} (hp : p.Prime)
    (hK : Nat.card K = p) (f g : K →* A) (hf : Function.Injective f)
    (hg : Function.Injective g) : ∃ e : K ≃* K, ∀ x, f x = g (e x) := by
  have hfcard : Nat.card f.range = p := by
    rw [← hK]
    exact (Nat.card_congr (MonoidHom.ofInjective hf).toEquiv).symm
  have hgcard : Nat.card g.range = p := by
    rw [← hK]
    exact (Nat.card_congr (MonoidHom.ofInjective hg).toEquiv).symm
  have hrange : f.range = g.range :=
    subgroup_eq_of_isCyclic_card_eq f.range g.range hp.pos hfcard hgcard
  let e := (MonoidHom.ofInjective hf).trans
    ((MulEquiv.subgroupCongr hrange).trans (MonoidHom.ofInjective hg).symm)
  refine ⟨e, fun x => ?_⟩
  change f x = g ((MonoidHom.ofInjective hg).symm
    (MulEquiv.subgroupCongr hrange ((MonoidHom.ofInjective hf) x)))
  rw [MonoidHom.apply_ofInjective_symm]
  rfl

section GroundTruth

example : (2 * 3).factorization 3 = 1 :=
  factorization_mul_primes_right Nat.prime_two Nat.prime_three (by omega)

example (Q : Sylow 3 (Multiplicative (ZMod 6))) : Q.Normal :=
  sylow_larger_prime_normal Nat.prime_two Nat.prime_three (by omega) (by simp) Q

example : (⊤ : Subgroup (Multiplicative (ZMod 5))) = ⊤ :=
  subgroup_eq_of_isCyclic_card_eq ⊤ ⊤ (d := 5) (by omega) (by simp) (by simp)

example : ∃ e : Multiplicative (ZMod 2) ≃* Multiplicative (ZMod 2),
    ∀ x, MonoidHom.id _ x = MonoidHom.id _ (e x) :=
  injective_hom_eq_comp_mulEquiv Nat.prime_two (by simp) (MonoidHom.id _)
    (MonoidHom.id _) Function.injective_id Function.injective_id

end GroundTruth

#check @factorization_mul_primes_right
#check @sylow_card_eq_larger_prime
#check @sylow_larger_prime_normal
#check @subgroup_eq_of_isCyclic_card_eq
#check @injective_hom_eq_comp_mulEquiv

#print axioms factorization_mul_primes_right
#print axioms sylow_card_eq_larger_prime
#print axioms sylow_larger_prime_normal
#print axioms subgroup_eq_of_isCyclic_card_eq
#print axioms injective_hom_eq_comp_mulEquiv

/-- If a finite group is a noncyclic internal semidirect product with a cyclic
normal factor and a cyclic prime-order complement, then its conjugation action is
injective. -/
theorem semidirect_action_injective_of_not_isCyclic {G : Type*} [Group G] [Finite G]
    {N H : Subgroup G} [N.Normal] (hcomp : N.IsComplement' H)
    [IsCyclic N] [IsCyclic H] {p : ℕ} (hp : p.Prime) (hH : Nat.card H = p)
    (hcop : (Nat.card N).Coprime (Nat.card H)) (hncyc : ¬ IsCyclic G) :
    Function.Injective (N.normalizerMonoidHom.comp
      (Subgroup.inclusion (N.normalizer_eq_top ▸ le_top : H ≤ Subgroup.normalizer N))) := by
  let hHN : H ≤ Subgroup.normalizer N := N.normalizer_eq_top ▸ le_top
  let φ := N.normalizerMonoidHom.comp (Subgroup.inclusion hHN)
  have hker : φ.ker = ⊥ := by
    letI : Fact (Nat.card H).Prime := ⟨hH.symm ▸ hp⟩
    rcases @Subgroup.eq_bot_or_eq_top_of_prime_card H _ φ.ker _ with hbot | htop
    · exact hbot
    · exfalso
      have hφ : φ = 1 := by
        apply MonoidHom.ext
        intro x
        have hx : x ∈ φ.ker := by rw [htop]; exact Subgroup.mem_top x
        exact MonoidHom.mem_ker.mp hx
      have hcyc : IsCyclic (N ⋊[φ] H) := by
        rw [hφ]
        haveI : IsCyclic (N × H) :=
          Group.isCyclic_prod_iff.mpr ⟨inferInstance, inferInstance, hcop⟩
        exact isCyclic_of_surjective SemidirectProduct.mulEquivProd.symm
          SemidirectProduct.mulEquivProd.symm.surjective
      haveI : IsCyclic (N ⋊[φ] H) := hcyc
      exact hncyc (isCyclic_of_surjective (SemidirectProduct.mulEquivSubgroup hcomp)
        (SemidirectProduct.mulEquivSubgroup hcomp).surjective)
  exact φ.ker_eq_bot_iff.mp hker

/-- Every finite group of order `p * q`, for primes `p < q`, admits cyclic
subgroups `N` and `H` of respective orders `q` and `p`, and an action `φ` for which
the external semidirect product `N ⋊[φ] H` is isomorphic to the group. -/
theorem exists_pq_semidirect_decomposition {G : Type*} [Group G] [Finite G]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q)
    (hcard : Nat.card G = p * q) :
    ∃ (N H : Subgroup G) (φ : H →* MulAut N),
      Nat.card N = q ∧ Nat.card H = p ∧ IsCyclic N ∧ IsCyclic H ∧
      (Nat.card N).Coprime (Nat.card H) ∧ Nonempty (N ⋊[φ] H ≃* G) := by
  letI : Fact p.Prime := ⟨hp⟩
  letI : Fact q.Prime := ⟨hq⟩
  let N : Sylow q G := Classical.choice inferInstance
  have hNcard : Nat.card N = q := sylow_card_eq_larger_prime hp hq hpq hcard N
  letI : (N : Subgroup G).Normal := sylow_larger_prime_normal hp hq hpq hcard N
  have hindex : (N : Subgroup G).index = p := by
    have hmul := (N : Subgroup G).card_mul_index
    rw [hNcard, hcard] at hmul
    apply Nat.eq_of_mul_eq_mul_left hq.pos
    simpa [Nat.mul_comm] using hmul
  have hcop : (Nat.card N).Coprime (N : Subgroup G).index := by
    rw [hNcard, hindex]
    exact Nat.Coprime.symm (hp.coprime_iff_not_dvd.mpr fun hdvd => by
      rcases (Nat.dvd_prime hq).mp hdvd with hone | heq
      · exact hp.ne_one hone
      · exact hpq.ne heq)
  obtain ⟨H, hHN⟩ := Subgroup.exists_left_complement'_of_coprime hcop
  have hHcard : Nat.card H = p := by rw [← hindex, hHN.index_eq_card]
  have hcycN : IsCyclic N := isCyclic_of_prime_card hNcard
  have hcycH : IsCyclic H := isCyclic_of_prime_card hHcard
  let φ := (N : Subgroup G).normalizerMonoidHom.comp
    (Subgroup.inclusion ((N : Subgroup G).normalizer_eq_top ▸ le_top :
      H ≤ Subgroup.normalizer N))
  exact ⟨N, H, φ, hNcard, hHcard, hcycN, hcycH,
    by
      rw [hNcard, hHcard]
      rw [hNcard, hindex] at hcop
      exact hcop,
    ⟨SemidirectProduct.mulEquivSubgroup hHN.symm⟩⟩

/-- Semidirect products of cyclic groups of respective prime orders `q` and `p`
with injective actions are isomorphic.  This is the uniqueness of the nonabelian
isomorphism class in Hölder's order-`p*q` classification. -/
theorem semidirect_products_mulEquiv_of_injective
    {N₁ H₁ N₂ H₂ : Type*} [Group N₁] [Group H₁] [Group N₂] [Group H₂]
    [Finite N₁] [Finite H₁] [Finite N₂] [Finite H₂]
    [IsCyclic N₁] [IsCyclic H₁] [IsCyclic N₂] [IsCyclic H₂]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hN₁ : Nat.card N₁ = q) (hH₁ : Nat.card H₁ = p)
    (hN₂ : Nat.card N₂ = q) (hH₂ : Nat.card H₂ = p)
    (φ₁ : H₁ →* MulAut N₁) (φ₂ : H₂ →* MulAut N₂)
    (hφ₁ : Function.Injective φ₁) (hφ₂ : Function.Injective φ₂) :
    Nonempty (N₁ ⋊[φ₁] H₁ ≃* N₂ ⋊[φ₂] H₂) := by
  letI : Fact (Nat.card N₂).Prime := ⟨hN₂.symm ▸ hq⟩
  haveI : IsCyclic (MulAut N₂) := isCyclic_of_injective
    (IsCyclic.mulAutMulEquiv N₂).toMonoidHom (IsCyclic.mulAutMulEquiv N₂).injective
  let fn : N₁ ≃* N₂ := mulEquivOfCyclicCardEq (hN₁.trans hN₂.symm)
  let fh : H₁ ≃* H₂ := mulEquivOfCyclicCardEq (hH₁.trans hH₂.symm)
  let α : H₁ →* MulAut N₂ := (MulAut.congr fn).toMonoidHom.comp φ₁
  let β : H₁ →* MulAut N₂ := φ₂.comp fh.toMonoidHom
  have hα : Function.Injective α := (MulAut.congr fn).injective.comp hφ₁
  have hβ : Function.Injective β := hφ₂.comp fh.injective
  obtain ⟨e, he⟩ := injective_hom_eq_comp_mulEquiv hp hH₁ α β hα hβ
  let fg : H₁ ≃* H₂ := e.trans fh
  refine ⟨SemidirectProduct.congr fn fg ?_⟩
  intro g
  ext n
  have heval := DFunLike.congr_fun (he g) (fn n)
  simpa [α, β, fg, MulAut.congr_apply] using heval

/-- A noncyclic group isomorphic to a semidirect product with a prime-order
cyclic acting factor has injective action, provided the two factor orders are coprime. -/
theorem semidirect_action_injective_of_noncyclic_target
    {G N H : Type*} [Group G] [Group N] [Group H]
    [Finite G] [Finite N] [Finite H] [IsCyclic N] [IsCyclic H]
    {φ : H →* MulAut N} {p : ℕ} (hp : p.Prime) (hH : Nat.card H = p)
    (hcop : (Nat.card N).Coprime (Nat.card H)) (e : N ⋊[φ] H ≃* G)
    (hncyc : ¬ IsCyclic G) : Function.Injective φ := by
  have hker : φ.ker = ⊥ := by
    letI : Fact (Nat.card H).Prime := ⟨hH.symm ▸ hp⟩
    rcases @Subgroup.eq_bot_or_eq_top_of_prime_card H _ φ.ker _ with hbot | htop
    · exact hbot
    · exfalso
      have hφ : φ = 1 := by
        apply MonoidHom.ext
        intro x
        have hx : x ∈ φ.ker := by rw [htop]; exact Subgroup.mem_top x
        exact MonoidHom.mem_ker.mp hx
      have hcyc : IsCyclic (N ⋊[φ] H) := by
        rw [hφ]
        haveI : IsCyclic (N × H) :=
          Group.isCyclic_prod_iff.mpr ⟨inferInstance, inferInstance, hcop⟩
        exact isCyclic_of_surjective SemidirectProduct.mulEquivProd.symm
          SemidirectProduct.mulEquivProd.symm.surjective
      haveI : IsCyclic (N ⋊[φ] H) := hcyc
      exact hncyc (isCyclic_of_surjective e e.surjective)
  exact φ.ker_eq_bot_iff.mp hker

/-- Any two noncyclic finite groups of order `p * q`, for primes `p < q`, are
isomorphic.  Thus Hölder's classification has at most one nonabelian class. -/
theorem nonempty_mulEquiv_of_card_eq_mul_primes_of_not_isCyclic
    {G₁ G₂ : Type*} [Group G₁] [Group G₂] [Finite G₁] [Finite G₂]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q)
    (hG₁ : Nat.card G₁ = p * q) (hG₂ : Nat.card G₂ = p * q)
    (hncyc₁ : ¬ IsCyclic G₁) (hncyc₂ : ¬ IsCyclic G₂) :
    Nonempty (G₁ ≃* G₂) := by
  obtain ⟨N₁, H₁, φ₁, hN₁, hH₁, hcycN₁, hcycH₁, hcop₁, ⟨e₁⟩⟩ :=
    exists_pq_semidirect_decomposition hp hq hpq hG₁
  obtain ⟨N₂, H₂, φ₂, hN₂, hH₂, hcycN₂, hcycH₂, hcop₂, ⟨e₂⟩⟩ :=
    exists_pq_semidirect_decomposition hp hq hpq hG₂
  letI : IsCyclic N₁ := hcycN₁
  letI : IsCyclic H₁ := hcycH₁
  letI : IsCyclic N₂ := hcycN₂
  letI : IsCyclic H₂ := hcycH₂
  have hinj₁ : Function.Injective φ₁ :=
    semidirect_action_injective_of_noncyclic_target hp hH₁ hcop₁ e₁ hncyc₁
  have hinj₂ : Function.Injective φ₂ :=
    semidirect_action_injective_of_noncyclic_target hp hH₂ hcop₂ e₂ hncyc₂
  obtain ⟨e⟩ := semidirect_products_mulEquiv_of_injective hp hq hN₁ hH₁ hN₂ hH₂
    φ₁ φ₂ hinj₁ hinj₂
  exact ⟨e₁.symm.trans (e.trans e₂)⟩

/-- A noncyclic finite group of order `p * q`, with primes `p < q`, forces
`p ∣ q - 1`.  The injective complement action embeds a group of order `p` in the
cyclic automorphism group of the normal subgroup of order `q`. -/
theorem dvd_pred_of_card_eq_mul_primes_of_not_isCyclic
    {G : Type*} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p < q)
    (hcard : Nat.card G = p * q) (hncyc : ¬ IsCyclic G) : p ∣ q - 1 := by
  obtain ⟨N, H, φ, hN, hH, hcycN, hcycH, hcop, ⟨e⟩⟩ :=
    exists_pq_semidirect_decomposition hp hq hpq hcard
  letI : IsCyclic N := hcycN
  letI : IsCyclic H := hcycH
  have hinj : Function.Injective φ :=
    semidirect_action_injective_of_noncyclic_target hp hH hcop e hncyc
  have hrange : Nat.card φ.range = p := by
    rw [← hH]
    exact (Nat.card_congr (MonoidHom.ofInjective hinj).toEquiv).symm
  have hdvd : Nat.card φ.range ∣ Nat.card (MulAut N) := φ.range.card_subgroup_dvd_card
  rw [hrange, IsCyclic.card_mulAut, hN, Nat.totient_prime hq] at hdvd
  exact hdvd

/-- If `p < q` are prime and `p` does not divide `q - 1`, every group of order
`p * q` is cyclic, so there is exactly one isomorphism class. -/
theorem gnu_mul_primes_of_not_dvd {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p < q) (hndvd : ¬ p ∣ q - 1) : gnu (p * q) = 1 := by
  apply gnu_eq_one_iff.mpr
  refine ⟨by nlinarith [hp.one_lt, hq.one_lt], fun S T => ?_⟩
  have hcycS : IsCyclic S.Carrier := by
    by_contra hncyc
    exact hndvd (dvd_pred_of_card_eq_mul_primes_of_not_isCyclic hp hq hpq
      S.natCard_carrier hncyc)
  have hcycT : IsCyclic T.Carrier := by
    by_contra hncyc
    exact hndvd (dvd_pred_of_card_eq_mul_primes_of_not_isCyclic hp hq hpq
      T.natCard_carrier hncyc)
  letI : IsCyclic S.Carrier := hcycS
  letI : IsCyclic T.Carrier := hcycT
  exact (GroupStructure.iso_iff_nonempty_mulEquiv S T).mpr
    ⟨mulEquivOfCyclicCardEq (by simp)⟩

/-- If primes `p < q` satisfy `p ∣ q - 1`, there are exactly two isomorphism classes
of groups of order `p * q`: the cyclic group and one noncyclic semidirect product. -/
theorem gnu_mul_primes_of_dvd {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p < q) (hdvd : p ∣ q - 1) : gnu (p * q) = 2 := by
  obtain ⟨σ, hσ, hrest⟩ :=
    exists_semidirectProduct_card_mul_primes_noncommutative hp hq hpq hdvd
  let H := Subgroup.zpowers σ
  let φ : H →* MulAut (Multiplicative (ZMod q)) := H.subtype
  let G := Multiplicative (ZMod q) ⋊[φ] H
  change Nonempty (Fintype G) ∧ Nat.card G = p * q ∧
    ∃ x y : G, x * y ≠ y * x at hrest
  obtain ⟨hfin, hGcard, x, y, hxy⟩ := hrest
  letI : Fintype G := Classical.choice hfin
  have hGcardF : Fintype.card G = p * q := by
    simpa only [Nat.card_eq_fintype_card] using hGcard
  have hGnotcyclic : ¬ IsCyclic G := by
    intro hcyc
    letI : IsCyclic G := hcyc
    exact hxy (Std.Commutative.comm x y)
  letI : NeZero (p * q) := ⟨Nat.mul_ne_zero hp.ne_zero hq.ne_zero⟩
  obtain ⟨T, ⟨eG⟩⟩ := GroupStructure.exists_carrier_mulEquiv hGcardF
  have hcyclic_not_iso : ¬ (GroupStructure.cyclic (p * q)).Iso T := by
    intro hiso
    obtain ⟨eCT⟩ := (GroupStructure.iso_iff_nonempty_mulEquiv _ _).mp hiso
    have hcycT : IsCyclic T.Carrier :=
      isCyclic_of_surjective eCT eCT.surjective
    letI : IsCyclic T.Carrier := hcycT
    exact hGnotcyclic (isCyclic_of_surjective eG.symm eG.symm.surjective)
  have key : Fintype.card Bool = gnu (p * q) := by
    refine card_eq_gnu_of_classification
      (fun b => cond b T (GroupStructure.cyclic (p * q))) ?_ ?_
    · intro S
      by_cases hcycS : IsCyclic S.Carrier
      · refine ⟨false, ?_⟩
        show (GroupStructure.cyclic (p * q)).Iso S
        letI : IsCyclic S.Carrier := hcycS
        exact (GroupStructure.iso_iff_nonempty_mulEquiv _ S).mpr
          ⟨mulEquivOfCyclicCardEq (by simp)⟩
      · refine ⟨true, ?_⟩
        show T.Iso S
        obtain ⟨eS⟩ := nonempty_mulEquiv_of_card_eq_mul_primes_of_not_isCyclic
          hp hq hpq hGcard S.natCard_carrier hGnotcyclic hcycS
        exact (GroupStructure.iso_iff_nonempty_mulEquiv T S).mpr
          ⟨eG.symm.trans eS⟩
    · intro i j hij
      cases i <;> cases j
      · rfl
      · exact absurd hij hcyclic_not_iso
      · exact absurd hij.symm hcyclic_not_iso
      · rfl
  rw [← key]
  exact Fintype.card_bool

/-- Hölder's formula: for primes `p < q`, the number of groups of order `p * q` is
two exactly when `p ∣ q - 1`, and one otherwise. -/
theorem gnu_mul_primes {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p < q) : gnu (p * q) = if p ∣ q - 1 then 2 else 1 := by
  by_cases hdvd : p ∣ q - 1
  · rw [if_pos hdvd]
    exact gnu_mul_primes_of_dvd hp hq hpq hdvd
  · rw [if_neg hdvd]
    exact gnu_mul_primes_of_not_dvd hp hq hpq hdvd

section GroundTruth

example : Nat.Prime 2 ∧ Nat.Prime 3 ∧ 2 < 3 ∧ 2 ∣ 3 - 1 := by norm_num

example : gnu (2 * 3) = if 2 ∣ 3 - 1 then 2 else 1 :=
  gnu_mul_primes Nat.prime_two Nat.prime_three (by omega)

end GroundTruth

#check @exists_semidirectProduct_card_mul_primes_noncommutative
#check @gnu_mul_primes_of_dvd
#check @gnu_mul_primes
#print axioms exists_semidirectProduct_card_mul_primes_noncommutative
#print axioms gnu_mul_primes_of_dvd
#print axioms gnu_mul_primes

#check @dvd_pred_of_card_eq_mul_primes_of_not_isCyclic
#check @gnu_mul_primes_of_not_dvd
#print axioms dvd_pred_of_card_eq_mul_primes_of_not_isCyclic
#print axioms gnu_mul_primes_of_not_dvd

#check @semidirect_action_injective_of_noncyclic_target
#check @nonempty_mulEquiv_of_card_eq_mul_primes_of_not_isCyclic
#print axioms semidirect_action_injective_of_noncyclic_target
#print axioms nonempty_mulEquiv_of_card_eq_mul_primes_of_not_isCyclic

#check @semidirect_products_mulEquiv_of_injective
#print axioms semidirect_products_mulEquiv_of_injective

#check @semidirect_action_injective_of_not_isCyclic
#check @exists_pq_semidirect_decomposition

#print axioms semidirect_action_injective_of_not_isCyclic
#print axioms exists_pq_semidirect_decomposition

end GroupCount
