import BilinearComplexity.FiveCircuit
import BilinearComplexity.PairTripleSpan

set_option autoImplicit false

open scoped BigOperators

namespace BilinearComplexity.ProfileInequalityExperiment

local instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- Coordinate K1: a vanishing finite sum of outer products bounds the sum of
the two factor-span dimensions by the number of summands. -/
theorem twoModeCancellation_finrank_le
    {ι : Type*} [Fintype ι] {b c : ℕ}
    (u : ι → Fin b → ZMod 2) (v : ι → Fin c → ZMod 2)
    (hzero : ∀ j k, ∑ i, u i j * v i k = 0) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) ≤
      Fintype.card ι := by
  classical
  let U : Matrix (Fin b) ι (ZMod 2) := fun j i => u i j
  let V : Matrix ι (Fin c) (ZMod 2) := fun i k => v i k
  have hUV : U * V = 0 := by
    ext j k
    change (∑ i, u i j * v i k) = 0
    exact hzero j k
  have hUcol : U.col = u := by
    funext i j
    rfl
  have hUrank : U.rank =
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) := by
    rw [Matrix.rank_eq_finrank_span_cols, hUcol]
  have hVcol : V.transpose.col = v := by
    funext i k
    rfl
  have hVrank : V.rank =
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) := by
    rw [← Matrix.rank_transpose V, Matrix.rank_eq_finrank_span_cols, hVcol]
  rw [← hUrank, ← hVrank]
  exact Matrix.rank_add_rank_le_card_of_mul_eq_zero hUV

/-- Finset form of K1: a zero outer-product sum over a selected support bounds
the dimensions of the spans of the selected factor values by its cardinality. -/
theorem twoModeCancellation_finset_finrank_le
    {ι : Type*} [Fintype ι] [DecidableEq ι] {b c : ℕ}
    (S : Finset ι) (u : ι → Fin b → ZMod 2) (v : ι → Fin c → ZMod 2)
    (hzero : ∀ j k, ∑ i ∈ S, u i j * v i k = 0) :
    Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (u '' (S : Set ι))) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (v '' (S : Set ι))) ≤ S.card := by
  let uS : S → Fin b → ZMod 2 := fun i => u i
  let vS : S → Fin c → ZMod 2 := fun i => v i
  have hzeroS : ∀ j k, ∑ i : S, uS i j * vS i k = 0 := by
    intro j k
    change (∑ i ∈ S.attach, u i j * v i k) = 0
    exact (Finset.sum_attach S (fun i => u i j * v i k)).trans (hzero j k)
  have huRange : Set.range uS = u '' (S : Set ι) := by
    ext z
    simp [uS]
  have hvRange : Set.range vS = v '' (S : Set ι) := by
    ext z
    simp [vS]
  have hbound := twoModeCancellation_finrank_le uS vS hzeroS
  rw [huRange, hvRange, Fintype.card_coe] at hbound
  exact hbound

/-- Equal complementary matrix sums on disjoint fibers give a K1 bound on
their union; converting equality to a zero sum is the characteristic-two step. -/
theorem twoModeEqualDisjointSums_finrank_le
    {ι : Type*} [Fintype ι] [DecidableEq ι] {b c : ℕ}
    (S T : Finset ι) (u : ι → Fin b → ZMod 2) (v : ι → Fin c → ZMod 2)
    (hDisjoint : Disjoint S T)
    (heq : ∀ j k, (∑ i ∈ S, u i j * v i k) = ∑ i ∈ T, u i j * v i k) :
    Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (u '' ((S ∪ T : Finset ι) : Set ι))) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (v '' ((S ∪ T : Finset ι) : Set ι))) ≤
      S.card + T.card := by
  have hzero : ∀ j k, ∑ i ∈ S ∪ T, u i j * v i k = 0 := by
    intro j k
    rw [Finset.sum_union hDisjoint]
    rw [heq j k]
    exact PairTripleSpan.add_self_eq_zero_f2 _
  have hbound := twoModeCancellation_finset_finrank_le (S ∪ T) u v hzero
  rw [Finset.card_union_of_disjoint hDisjoint] at hbound
  exact hbound

/-- If two finite-dimensional subspaces contain the same nonzero vector, their
sup loses at least one dimension compared with the sum of their dimensions. -/
theorem finrank_sup_add_one_le_of_common_nonzero
    {K V : Type*} [Field K] [AddCommGroup V] [Module K V]
    (P Q : Submodule K V) [FiniteDimensional K P] [FiniteDimensional K Q]
    {x : V} (hxP : x ∈ P) (hxQ : x ∈ Q) (hx : x ≠ 0) :
    Module.finrank K (P ⊔ Q : Submodule K V) + 1 ≤
      Module.finrank K P + Module.finrank K Q := by
  have hxInf : x ∈ (P ⊓ Q : Submodule K V) := ⟨hxP, hxQ⟩
  have hInf : (P ⊓ Q : Submodule K V) ≠ ⊥ := by
    intro hbot
    apply hx
    have hxBot : x ∈ (⊥ : Submodule K V) := by
      rw [← hbot]
      exact hxInf
    simpa using hxBot
  have hOne : 1 ≤ Module.finrank K (P ⊓ Q : Submodule K V) :=
    Submodule.one_le_finrank_iff.mpr hInf
  rw [← Submodule.finrank_sup_add_finrank_inf_eq P Q]
  exact Nat.add_le_add_left hOne _

/-- If a finite outer-product sum cancels one additional outer product, K1
bounds the spans generated by the family together with the additional factors. -/
theorem cancellationWithSingleton_finrank_le
    {ι : Type*} [Fintype ι] {b c : ℕ}
    (u : ι → Fin b → ZMod 2) (v : ι → Fin c → ZMod 2)
    (u₀ : Fin b → ZMod 2) (v₀ : Fin c → ZMod 2)
    (hzero : ∀ j k, (∑ i, u i j * v i k) + u₀ j * v₀ k = 0) :
    Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range u ∪ {u₀})) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range v ∪ {v₀})) ≤
      Fintype.card ι + 1 := by
  classical
  let u' : ι ⊕ Unit → Fin b → ZMod 2 := Sum.elim u (fun _ => u₀)
  let v' : ι ⊕ Unit → Fin c → ZMod 2 := Sum.elim v (fun _ => v₀)
  have hzero' : ∀ j k, ∑ i, u' i j * v' i k = 0 := by
    intro j k
    rw [Fintype.sum_sum_type]
    simpa only [u', v', Sum.elim_inl, Sum.elim_inr, Fintype.sum_unique] using
      hzero j k
  have huRange : Set.range u' = Set.range u ∪ {u₀} := by
    ext z
    simp [u']
  have hvRange : Set.range v' = Set.range v ∪ {v₀} := by
    ext z
    simp [v']
  have hbound := twoModeCancellation_finrank_le u' v' hzero'
  rw [huRange, hvRange] at hbound
  simpa only [Fintype.card_sum, Fintype.card_unit] using hbound

/-- A nonzero family whose span has binary finrank two has two occurring
independent values, and every family value is one of their three nonzero
binary combinations. -/
theorem f2_finrank_two_range_profile
    {ι : Type*} [Fintype ι] {a : ℕ} (u : ι → Fin a → ZMod 2)
    (hu : ∀ i, u i ≠ 0)
    (hdim : Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) = 2) :
    ∃ i₀ i₁ : ι, i₀ ≠ i₁ ∧
      LinearIndependent (ZMod 2) ![u i₀, u i₁] ∧
      ∀ i, u i = u i₀ ∨ u i = u i₁ ∨ u i = u i₀ + u i₁ := by
  classical
  have hbasis := Submodule.exists_fun_fin_finrank_span_eq
    (K := ZMod 2) (s := Set.range u)
  rw [hdim] at hbasis
  obtain ⟨f, hfRange, hfSpan, hfLI⟩ := hbasis
  obtain ⟨i₀, hi₀⟩ := hfRange 0
  obtain ⟨i₁, hi₁⟩ := hfRange 1
  have hfamily : (![u i₀, u i₁] : Fin 2 → Fin a → ZMod 2) = f := by
    funext q
    fin_cases q
    · exact hi₀
    · exact hi₁
  have hpair : LinearIndependent (ZMod 2) ![u i₀, u i₁] := by
    rw [hfamily]
    exact hfLI
  have hne : i₀ ≠ i₁ := by
    intro heq
    subst i₁
    have hzero : (1 : ZMod 2) • u i₀ + (1 : ZMod 2) • u i₀ = 0 := by
      simpa only [one_smul] using PairTripleSpan.add_self_eq_zero_f2 (u i₀)
    have hone := (hpair.eq_zero_of_pair hzero).1
    exact one_ne_zero hone
  refine ⟨i₀, i₁, hne, hpair, ?_⟩
  intro i
  have hui : u i ∈ Submodule.span (ZMod 2) (Set.range u) :=
    Submodule.subset_span (Set.mem_range_self i)
  rw [← hfSpan, Submodule.mem_span_range_iff_exists_fun] at hui
  obtain ⟨coeff, hcoeff⟩ := hui
  rw [Fin.sum_univ_two, ← hi₀, ← hi₁] at hcoeff
  rcases PairTripleSpan.scalar_eq_zero_or_one (coeff 0) with hzero | hone <;>
    rcases PairTripleSpan.scalar_eq_zero_or_one (coeff 1) with hzero' | hone'
  · have huiZero : u i = 0 := by
      simpa only [hzero, hzero', zero_smul, zero_add] using hcoeff.symm
    exact (hu i huiZero).elim
  · exact Or.inr (Or.inl (by
      simpa only [hzero, hone', zero_smul, one_smul, zero_add] using hcoeff.symm))
  · exact Or.inl (by
      simpa only [hone, hzero', one_smul, zero_smul, add_zero] using hcoeff.symm)
  · exact Or.inr (Or.inr (by
      simpa only [hone, hone', one_smul] using hcoeff.symm))

/-- Independence of two binary first-mode vectors makes the three collected
complementary fiber sums equal. -/
theorem threeFiberSums_eq
    {a b c : ℕ} (x y : Fin a → ZMod 2)
    (A B C : Fin b → Fin c → ZMod 2)
    (hxy : LinearIndependent (ZMod 2) ![x, y])
    (hrel : ∀ p j k,
      x p * A j k + y p * B j k + (x p + y p) * C j k = 0) :
    A = C ∧ B = C := by
  have hentry : ∀ j k, A j k = C j k ∧ B j k = C j k := by
    intro j k
    have hcoeff :
        (A j k + C j k) • x + (B j k + C j k) • y = 0 := by
      funext p
      change (A j k + C j k) * x p + (B j k + C j k) * y p = 0
      calc
        (A j k + C j k) * x p + (B j k + C j k) * y p =
            x p * A j k + y p * B j k + (x p + y p) * C j k := by ring
        _ = 0 := hrel p j k
    obtain ⟨hAC, hBC⟩ := hxy.eq_zero_of_pair hcoeff
    exact ⟨(PairTripleSpan.add_eq_zero_iff_eq_f2 _ _).mp hAC,
      (PairTripleSpan.add_eq_zero_iff_eq_f2 _ _).mp hBC⟩
  constructor <;> funext j k
  · exact (hentry j k).1
  · exact (hentry j k).2

/-- In a subset-minimal coordinate relation, a nonempty proper fiber on which
the first factor is constant has a nonzero complementary matrix sum. -/
theorem matrixSum_ne_zero_of_minimal_constant_fiber
    {ι : Type*} [Fintype ι] [DecidableEq ι] {a b c : ℕ}
    (u : ι → Fin a → ZMod 2) (v : ι → Fin b → ZMod 2)
    (w : ι → Fin c → ZMod 2) (S : Finset ι) (x : Fin a → ZMod 2)
    (hMinimal : ∀ T : Finset ι,
      (∀ p j k, ∑ i ∈ T, u i p * v i j * w i k = 0) →
        T = ∅ ∨ T = Finset.univ)
    (hS : S.Nonempty) (hProper : S ≠ Finset.univ)
    (hConstant : ∀ i ∈ S, u i = x) :
    (fun j k => ∑ i ∈ S, v i j * w i k) ≠ 0 := by
  intro hMatrix
  have hzero : ∀ p j k, ∑ i ∈ S, u i p * v i j * w i k = 0 := by
    intro p j k
    calc
      (∑ i ∈ S, u i p * v i j * w i k) =
          ∑ i ∈ S, x p * (v i j * w i k) := by
            apply Finset.sum_congr rfl
            intro i hi
            rw [hConstant i hi]
            ring
      _ = x p * ∑ i ∈ S, v i j * w i k := by
        rw [Finset.mul_sum]
      _ = 0 := by
        have hentry : (∑ i ∈ S, v i j * w i k) = 0 := by
          simpa using congrFun (congrFun hMatrix j) k
        rw [hentry, mul_zero]
  rcases hMinimal S hzero with hEmpty | hUniv
  · exact (hS.ne_empty hEmpty).elim
  · exact hProper hUniv

/-- A nonzero complementary matrix sum can only come from a nonempty fiber. -/
theorem fiber_nonempty_of_matrixSum_ne_zero
    {ι : Type*} [DecidableEq ι] {b c : ℕ}
    (v : ι → Fin b → ZMod 2) (w : ι → Fin c → ZMod 2) (S : Finset ι)
    (h : (fun j k => ∑ i ∈ S, v i j * w i k) ≠ 0) :
    S.Nonempty := by
  rw [Finset.nonempty_iff_ne_empty]
  intro hEmpty
  apply h
  rw [hEmpty]
  funext j k
  simp

/-- The `(3,1,1)` fiber shape gives complementary profile sum at most four:
the second singleton is span-redundant by binary outer-product rigidity. -/
theorem three_one_one_finrank_le_four
    {b c : ℕ} (u : Fin 3 → Fin b → ZMod 2) (v : Fin 3 → Fin c → ZMod 2)
    (u₀ u₁ : Fin b → ZMod 2) (v₀ v₁ : Fin c → ZMod 2)
    (hu₀ : u₀ ≠ 0) (hu₁ : u₁ ≠ 0) (hv₀ : v₀ ≠ 0) (hv₁ : v₁ ≠ 0)
    (hzero : ∀ j k, (∑ i, u i j * v i k) + u₀ j * v₀ k = 0)
    (hSingletons : ∀ j k, u₀ j * v₀ k = u₁ j * v₁ k) :
    Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range u ∪ {u₀, u₁})) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range v ∪ {v₀, v₁})) ≤ 4 := by
  have hOuter : Matrix.vecMulVec u₀ v₀ = Matrix.vecMulVec u₁ v₁ := by
    ext j k
    exact hSingletons j k
  obtain ⟨hu, hv⟩ := PairTripleSpan.vecMulVec_eq_vecMulVec
    hu₀ hv₀ hu₁ hv₁ hOuter
  subst u₁
  subst v₁
  have huSet : Set.range u ∪ {u₀, u₀} = Set.range u ∪ {u₀} := by
    rw [Set.pair_eq_singleton]
  have hvSet : Set.range v ∪ {v₀, v₀} = Set.range v ∪ {v₀} := by
    rw [Set.pair_eq_singleton]
  rw [huSet, hvSet]
  simpa only [Fintype.card_fin] using
    cancellationWithSingleton_finrank_le u v u₀ v₀ hzero

/-- The `(2,2,1)` fiber shape gives complementary profile sum at most four:
two K1 bounds lose two dimensions through the common singleton factors. -/
theorem two_two_one_finrank_le_four
    {b c : ℕ}
    (uA uB : Fin 2 → Fin b → ZMod 2)
    (vA vB : Fin 2 → Fin c → ZMod 2)
    (u₀ : Fin b → ZMod 2) (v₀ : Fin c → ZMod 2)
    (hu₀ : u₀ ≠ 0) (hv₀ : v₀ ≠ 0)
    (hA : ∀ j k, (∑ i, uA i j * vA i k) + u₀ j * v₀ k = 0)
    (hB : ∀ j k, (∑ i, uB i j * vB i k) + u₀ j * v₀ k = 0) :
    Module.finrank (ZMod 2)
          ((Submodule.span (ZMod 2) (Set.range uA ∪ {u₀})) ⊔
            Submodule.span (ZMod 2) (Set.range uB ∪ {u₀}) :
            Submodule (ZMod 2) (Fin b → ZMod 2)) +
        Module.finrank (ZMod 2)
          ((Submodule.span (ZMod 2) (Set.range vA ∪ {v₀})) ⊔
            Submodule.span (ZMod 2) (Set.range vB ∪ {v₀}) :
            Submodule (ZMod 2) (Fin c → ZMod 2)) ≤ 4 := by
  let Pu := Submodule.span (ZMod 2) (Set.range uA ∪ {u₀})
  let Qu := Submodule.span (ZMod 2) (Set.range uB ∪ {u₀})
  let Pv := Submodule.span (ZMod 2) (Set.range vA ∪ {v₀})
  let Qv := Submodule.span (ZMod 2) (Set.range vB ∪ {v₀})
  have hLocalA : Module.finrank (ZMod 2) Pu + Module.finrank (ZMod 2) Pv ≤ 3 := by
    simpa only [Pu, Pv, Fintype.card_fin] using
      cancellationWithSingleton_finrank_le uA vA u₀ v₀ hA
  have hLocalB : Module.finrank (ZMod 2) Qu + Module.finrank (ZMod 2) Qv ≤ 3 := by
    simpa only [Qu, Qv, Fintype.card_fin] using
      cancellationWithSingleton_finrank_le uB vB u₀ v₀ hB
  have huPu : u₀ ∈ Pu := by
    apply Submodule.subset_span
    exact Set.mem_union_right _ (Set.mem_singleton u₀)
  have huQu : u₀ ∈ Qu := by
    apply Submodule.subset_span
    exact Set.mem_union_right _ (Set.mem_singleton u₀)
  have hvPv : v₀ ∈ Pv := by
    apply Submodule.subset_span
    exact Set.mem_union_right _ (Set.mem_singleton v₀)
  have hvQv : v₀ ∈ Qv := by
    apply Submodule.subset_span
    exact Set.mem_union_right _ (Set.mem_singleton v₀)
  have hOverlapU : Module.finrank (ZMod 2)
        (Pu ⊔ Qu : Submodule (ZMod 2) (Fin b → ZMod 2)) + 1 ≤
      Module.finrank (ZMod 2) Pu + Module.finrank (ZMod 2) Qu :=
    finrank_sup_add_one_le_of_common_nonzero Pu Qu huPu huQu hu₀
  have hOverlapV : Module.finrank (ZMod 2)
        (Pv ⊔ Qv : Submodule (ZMod 2) (Fin c → ZMod 2)) + 1 ≤
      Module.finrank (ZMod 2) Pv + Module.finrank (ZMod 2) Qv :=
    finrank_sup_add_one_le_of_common_nonzero Pv Qv hvPv hvQv hv₀
  change Module.finrank (ZMod 2)
        (Pu ⊔ Qu : Submodule (ZMod 2) (Fin b → ZMod 2)) +
      Module.finrank (ZMod 2)
        (Pv ⊔ Qv : Submodule (ZMod 2) (Fin c → ZMod 2)) ≤ 4
  omega

/-- The only ordered positive triples summing to five are the three
permutations of `(3,1,1)` and the three permutations of `(2,2,1)`. -/
theorem three_positive_sum_five
    {p q r : ℕ} (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (hsum : p + q + r = 5) :
    (p = 3 ∧ q = 1 ∧ r = 1) ∨
    (p = 1 ∧ q = 3 ∧ r = 1) ∨
    (p = 1 ∧ q = 1 ∧ r = 3) ∨
    (p = 2 ∧ q = 2 ∧ r = 1) ∨
    (p = 2 ∧ q = 1 ∧ r = 2) ∨
    (p = 1 ∧ q = 2 ∧ r = 2) := by
  omega

/-- A five-value family contained in the span of its first pair has rank at most two. -/
theorem finrank_span_range_le_two_of_tail_mem_pair_span
    {a : ℕ} (u : Fin 5 → Fin a → ZMod 2)
    (h : ∀ i : Fin 3, u i.succ.succ ∈
      Submodule.span (ZMod 2) ({u 0, u 1} : Set (Fin a → ZMod 2))) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) ≤ 2 := by
  classical
  let P := Submodule.span (ZMod 2) ({u 0, u 1} : Set (Fin a → ZMod 2))
  have hrange : Set.range u ⊆ P := by
    rintro z ⟨i, rfl⟩
    fin_cases i
    · exact Submodule.subset_span (by simp)
    · exact Submodule.subset_span (by simp)
    · simpa [P] using h 0
    · simpa [P] using h 1
    · simpa [P] using h 2
  calc
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) ≤
        Module.finrank (ZMod 2) P :=
      Submodule.finrank_mono (Submodule.span_le.mpr hrange)
    _ ≤ 2 := by
      dsimp only [P]
      calc
        Module.finrank (ZMod 2)
            (Submodule.span (ZMod 2) ({u 0, u 1} : Set (Fin a → ZMod 2))) ≤
            ({u 0, u 1} : Set (Fin a → ZMod 2)).toFinset.card :=
          finrank_span_le_card _
        _ ≤ 2 := by
          simpa only [Set.toFinset_insert, Set.toFinset_singleton] using
            (Finset.card_le_two : ({u 0, u 1} :
              Finset (Fin a → ZMod 2)).card ≤ 2)

/-- The rank-one selected-mode branch of the five-term profile inequality. -/
theorem selectedMode_finrank_one_profile_le_six
    {a b c : ℕ}
    (u : Fin 5 → Fin a → ZMod 2)
    (v : Fin 5 → Fin b → ZMod 2)
    (w : Fin 5 → Fin c → ZMod 2)
    (hu : ∀ i, u i ≠ 0)
    (hzero : ∀ p j k, ∑ i, u i p * v i j * w i k = 0)
    (hdim : Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) = 1) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) ≤ 6 := by
  classical
  let P := Submodule.span (ZMod 2) (Set.range u)
  have hu0P : u 0 ∈ P := Submodule.subset_span (Set.mem_range_self 0)
  have hP : P = Submodule.span (ZMod 2) ({u 0} : Set (Fin a → ZMod 2)) :=
    eq_span_singleton_of_mem_of_finrank_eq_one hdim hu0P (hu 0)
  have hconst : ∀ i, u i = u 0 := by
    intro i
    have huiP : u i ∈ P := Submodule.subset_span (Set.mem_range_self i)
    rw [hP, Submodule.mem_span_singleton] at huiP
    obtain ⟨r, hr⟩ := huiP
    rcases PairTripleSpan.scalar_eq_zero_or_one r with rfl | rfl
    · simp only [zero_smul] at hr
      exact (hu i hr.symm).elim
    · simpa only [one_smul] using hr.symm
  obtain ⟨p, hp⟩ := PairTripleSpan.exists_apply_ne_zero (hu 0)
  have hpone : u 0 p = 1 := PairTripleSpan.eq_one_of_ne_zero hp
  have hmatrix : ∀ j k, ∑ i, v i j * w i k = 0 := by
    intro j k
    simpa only [hconst, hpone, one_mul] using hzero p j k
  have hvw := twoModeCancellation_finrank_le v w hmatrix
  have hvw' : Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range v)) +
      Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range w)) ≤ 5 := by
    simpa only [Fintype.card_fin] using hvw
  rw [hdim]
  omega

/-- A `(3,1,1)` partition with equal complementary matrix sums has total
complementary factor rank at most four. -/
theorem three_one_one_finset_finrank_le_four
    {b c : ℕ} (v : Fin 5 → Fin b → ZMod 2)
    (w : Fin 5 → Fin c → ZMod 2)
    (S T R : Finset (Fin 5))
    (hcover : (S ∪ T) ∪ R = Finset.univ)
    (hScard : S.card = 3) (hTcard : T.card = 1) (hRcard : R.card = 1)
    (hv : ∀ i, v i ≠ 0) (hw : ∀ i, w i ≠ 0)
    (heqST : ∀ j k, (∑ i ∈ S, v i j * w i k) =
      ∑ i ∈ T, v i j * w i k)
    (heqSR : ∀ j k, (∑ i ∈ S, v i j * w i k) =
      ∑ i ∈ R, v i j * w i k) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) +
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) ≤ 4 := by
  classical
  obtain ⟨t, ht⟩ := Finset.card_eq_one.mp hTcard
  obtain ⟨r, hr⟩ := Finset.card_eq_one.mp hRcard
  subst T
  subst R
  let eS : Fin 3 ≃ S :=
    (Equiv.cast (congrArg Fin hScard.symm)).trans S.equivFin.symm
  let vS : Fin 3 → Fin b → ZMod 2 := fun q => v (eS q)
  let wS : Fin 3 → Fin c → ZMod 2 := fun q => w (eS q)
  have hsumS : ∀ j k, (∑ q, vS q j * wS q k) =
      ∑ i ∈ S, v i j * w i k := by
    intro j k
    calc
      (∑ q, vS q j * wS q k) =
          ∑ q : S, v q j * w q k := eS.sum_comp (fun q : S => v q j * w q k)
      _ = ∑ i ∈ S, v i j * w i k := by
        change (∑ i ∈ S.attach, v i j * w i k) = _
        exact Finset.sum_attach S (fun i => v i j * w i k)
  have hRangeVS : Set.range vS = v '' (S : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eS q, (eS q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eS.symm ⟨i, hi⟩, ?_⟩
      simp only [vS, eS.apply_symm_apply]
  have hRangeWS : Set.range wS = w '' (S : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eS q, (eS q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eS.symm ⟨i, hi⟩, ?_⟩
      simp only [wS, eS.apply_symm_apply]
  have hRangeV : Set.range v = Set.range vS ∪ {v t, v r} := by
    rw [hRangeVS]
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      have hi : i ∈ (S ∪ {t}) ∪ {r} := by rw [hcover]; simp
      simp only [Finset.mem_union, Finset.mem_singleton] at hi
      rcases hi with (hiS | rfl) | rfl
      · exact Or.inl ⟨i, hiS, rfl⟩
      · exact Or.inr (Or.inl rfl)
      · exact Or.inr (Or.inr rfl)
    · rintro (⟨i, -, rfl⟩ | rfl | rfl)
      all_goals exact ⟨_, rfl⟩
  have hRangeW : Set.range w = Set.range wS ∪ {w t, w r} := by
    rw [hRangeWS]
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      have hi : i ∈ (S ∪ {t}) ∪ {r} := by rw [hcover]; simp
      simp only [Finset.mem_union, Finset.mem_singleton] at hi
      rcases hi with (hiS | rfl) | rfl
      · exact Or.inl ⟨i, hiS, rfl⟩
      · exact Or.inr (Or.inl rfl)
      · exact Or.inr (Or.inr rfl)
    · rintro (⟨i, -, rfl⟩ | rfl | rfl)
      all_goals exact ⟨_, rfl⟩
  have hzeroLocal : ∀ j k,
      (∑ q, vS q j * wS q k) + v t j * w t k = 0 := by
    intro j k
    apply (PairTripleSpan.add_eq_zero_iff_eq_f2 _ _).mpr
    rw [hsumS]
    simpa only [Finset.sum_singleton] using heqST j k
  have hSingletons : ∀ j k, v t j * w t k = v r j * w r k := by
    intro j k
    have heq := (heqST j k).symm.trans (heqSR j k)
    simpa only [Finset.sum_singleton] using heq
  have hlocal := three_one_one_finrank_le_four vS wS
    (v t) (v r) (w t) (w r) (hv t) (hv r) (hw t) (hw r)
    hzeroLocal hSingletons
  rw [← hRangeV, ← hRangeW] at hlocal
  exact hlocal

/-- A `(2,2,1)` partition with equal complementary matrix sums has total
complementary factor rank at most four. -/
theorem two_two_one_finset_finrank_le_four
    {b c : ℕ} (v : Fin 5 → Fin b → ZMod 2)
    (w : Fin 5 → Fin c → ZMod 2)
    (S T R : Finset (Fin 5))
    (hcover : (S ∪ T) ∪ R = Finset.univ)
    (hScard : S.card = 2) (hTcard : T.card = 2) (hRcard : R.card = 1)
    (hv : ∀ i, v i ≠ 0) (hw : ∀ i, w i ≠ 0)
    (heqSR : ∀ j k, (∑ i ∈ S, v i j * w i k) =
      ∑ i ∈ R, v i j * w i k)
    (heqTR : ∀ j k, (∑ i ∈ T, v i j * w i k) =
      ∑ i ∈ R, v i j * w i k) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) +
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) ≤ 4 := by
  classical
  obtain ⟨r, hr⟩ := Finset.card_eq_one.mp hRcard
  subst R
  let eS : Fin 2 ≃ S :=
    (Equiv.cast (congrArg Fin hScard.symm)).trans S.equivFin.symm
  let eT : Fin 2 ≃ T :=
    (Equiv.cast (congrArg Fin hTcard.symm)).trans T.equivFin.symm
  let vS : Fin 2 → Fin b → ZMod 2 := fun q => v (eS q)
  let wS : Fin 2 → Fin c → ZMod 2 := fun q => w (eS q)
  let vT : Fin 2 → Fin b → ZMod 2 := fun q => v (eT q)
  let wT : Fin 2 → Fin c → ZMod 2 := fun q => w (eT q)
  have hsumS : ∀ j k, (∑ q, vS q j * wS q k) =
      ∑ i ∈ S, v i j * w i k := by
    intro j k
    calc
      (∑ q, vS q j * wS q k) =
          ∑ q : S, v q j * w q k := eS.sum_comp (fun q : S => v q j * w q k)
      _ = ∑ i ∈ S, v i j * w i k := by
        change (∑ i ∈ S.attach, v i j * w i k) = _
        exact Finset.sum_attach S (fun i => v i j * w i k)
  have hsumT : ∀ j k, (∑ q, vT q j * wT q k) =
      ∑ i ∈ T, v i j * w i k := by
    intro j k
    calc
      (∑ q, vT q j * wT q k) =
          ∑ q : T, v q j * w q k := eT.sum_comp (fun q : T => v q j * w q k)
      _ = ∑ i ∈ T, v i j * w i k := by
        change (∑ i ∈ T.attach, v i j * w i k) = _
        exact Finset.sum_attach T (fun i => v i j * w i k)
  have hRangeVS : Set.range vS = v '' (S : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eS q, (eS q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eS.symm ⟨i, hi⟩, ?_⟩
      simp only [vS, eS.apply_symm_apply]
  have hRangeWS : Set.range wS = w '' (S : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eS q, (eS q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eS.symm ⟨i, hi⟩, ?_⟩
      simp only [wS, eS.apply_symm_apply]
  have hRangeVT : Set.range vT = v '' (T : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eT q, (eT q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eT.symm ⟨i, hi⟩, ?_⟩
      simp only [vT, eT.apply_symm_apply]
  have hRangeWT : Set.range wT = w '' (T : Set (Fin 5)) := by
    ext z
    constructor
    · rintro ⟨q, rfl⟩
      exact ⟨eT q, (eT q).property, rfl⟩
    · rintro ⟨i, hi, rfl⟩
      refine ⟨eT.symm ⟨i, hi⟩, ?_⟩
      simp only [wT, eT.apply_symm_apply]
  have hRangeV : Set.range v =
      (Set.range vS ∪ {v r}) ∪ (Set.range vT ∪ {v r}) := by
    rw [hRangeVS, hRangeVT]
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      have hi : i ∈ (S ∪ T) ∪ {r} := by rw [hcover]; simp
      simp only [Finset.mem_union, Finset.mem_singleton] at hi
      rcases hi with (hiS | hiT) | rfl
      · exact Or.inl (Or.inl ⟨i, hiS, rfl⟩)
      · exact Or.inr (Or.inl ⟨i, hiT, rfl⟩)
      · exact Or.inl (Or.inr rfl)
    · rintro ((⟨i, -, rfl⟩ | rfl) | ⟨i, -, rfl⟩ | rfl)
      all_goals exact ⟨_, rfl⟩
  have hRangeW : Set.range w =
      (Set.range wS ∪ {w r}) ∪ (Set.range wT ∪ {w r}) := by
    rw [hRangeWS, hRangeWT]
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      have hi : i ∈ (S ∪ T) ∪ {r} := by rw [hcover]; simp
      simp only [Finset.mem_union, Finset.mem_singleton] at hi
      rcases hi with (hiS | hiT) | rfl
      · exact Or.inl (Or.inl ⟨i, hiS, rfl⟩)
      · exact Or.inr (Or.inl ⟨i, hiT, rfl⟩)
      · exact Or.inl (Or.inr rfl)
    · rintro ((⟨i, -, rfl⟩ | rfl) | ⟨i, -, rfl⟩ | rfl)
      all_goals exact ⟨_, rfl⟩
  have hzeroS : ∀ j k,
      (∑ q, vS q j * wS q k) + v r j * w r k = 0 := by
    intro j k
    apply (PairTripleSpan.add_eq_zero_iff_eq_f2 _ _).mpr
    rw [hsumS]
    simpa only [Finset.sum_singleton] using heqSR j k
  have hzeroT : ∀ j k,
      (∑ q, vT q j * wT q k) + v r j * w r k = 0 := by
    intro j k
    apply (PairTripleSpan.add_eq_zero_iff_eq_f2 _ _).mpr
    rw [hsumT]
    simpa only [Finset.sum_singleton] using heqTR j k
  have hlocal := two_two_one_finrank_le_four vS vT wS wT
    (v r) (w r) (hv r) (hw r) hzeroS hzeroT
  rw [← Submodule.span_union, ← Submodule.span_union,
    ← hRangeV, ← hRangeW] at hlocal
  exact hlocal

/-- In the selected-mode rank-two branch, the three binary fibers force the
sum of the two complementary factor ranks to be at most four. -/
theorem selectedMode_finrank_two_complementary_le_four
    {a b c : ℕ}
    (u : Fin 5 → Fin a → ZMod 2)
    (v : Fin 5 → Fin b → ZMod 2)
    (w : Fin 5 → Fin c → ZMod 2)
    (hu : ∀ i, u i ≠ 0) (hv : ∀ i, v i ≠ 0) (hw : ∀ i, w i ≠ 0)
    (hzero : ∀ p j k, ∑ i, u i p * v i j * w i k = 0)
    (hMinimal : ∀ T : Finset (Fin 5),
      (∀ p j k, ∑ i ∈ T, u i p * v i j * w i k = 0) →
        T = ∅ ∨ T = Finset.univ)
    (hdim : Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) = 2) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) +
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) ≤ 4 := by
  classical
  obtain ⟨i₀, i₁, hi₀₁, hLI, hprofile⟩ :=
    f2_finrank_two_range_profile u hu hdim
  let x := u i₀
  let y := u i₁
  have hx : x ≠ 0 := hu i₀
  have hy : y ≠ 0 := hu i₁
  have hxy : x ≠ y := by
    intro h
    have hsum : (1 : ZMod 2) • x + (1 : ZMod 2) • y = 0 := by
      simpa only [one_smul, h] using PairTripleSpan.add_self_eq_zero_f2 y
    exact one_ne_zero (hLI.eq_zero_of_pair hsum).1
  have hxxy : x ≠ x + y := by
    intro h
    have hcancel : x + 0 = x + y := by simpa only [add_zero] using h
    exact hy (add_left_cancel hcancel).symm
  have hyxy : y ≠ x + y := by
    intro h
    have hcancel : y + 0 = y + x := by
      simpa only [add_zero, add_comm] using h
    exact hx (add_left_cancel hcancel).symm
  let A : Finset (Fin 5) := Finset.univ.filter fun i => u i = x
  let B : Finset (Fin 5) := Finset.univ.filter fun i => u i = y
  let C : Finset (Fin 5) := Finset.univ.filter fun i => u i = x + y
  have hmemA {i : Fin 5} : i ∈ A ↔ u i = x := by simp [A]
  have hmemB {i : Fin 5} : i ∈ B ↔ u i = y := by simp [B]
  have hmemC {i : Fin 5} : i ∈ C ↔ u i = x + y := by simp [C]
  have hAB : Disjoint A B := by
    rw [Finset.disjoint_left]
    intro i hiA hiB
    exact hxy ((hmemA.mp hiA).symm.trans (hmemB.mp hiB))
  have hAC : Disjoint A C := by
    rw [Finset.disjoint_left]
    intro i hiA hiC
    exact hxxy ((hmemA.mp hiA).symm.trans (hmemC.mp hiC))
  have hBC : Disjoint B C := by
    rw [Finset.disjoint_left]
    intro i hiB hiC
    exact hyxy ((hmemB.mp hiB).symm.trans (hmemC.mp hiC))
  have hABC : Disjoint (A ∪ B) C := by
    rw [Finset.disjoint_left]
    intro i hiAB hiC
    rcases Finset.mem_union.mp hiAB with hiA | hiB
    · exact (Finset.disjoint_left.mp hAC) hiA hiC
    · exact (Finset.disjoint_left.mp hBC) hiB hiC
  have hcover : (A ∪ B) ∪ C = Finset.univ := by
    ext i
    simp only [Finset.mem_union, Finset.mem_univ, iff_true]
    rcases hprofile i with hi | hi | hi
    · exact Or.inl (Or.inl (hmemA.mpr hi))
    · exact Or.inl (Or.inr (hmemB.mpr hi))
    · exact Or.inr (hmemC.mpr hi)
  have hAne : A.Nonempty := ⟨i₀, hmemA.mpr rfl⟩
  have hBne : B.Nonempty := ⟨i₁, hmemB.mpr rfl⟩
  have hAproper : A ≠ Finset.univ := by
    intro hA
    have hi₁A : i₁ ∈ A := by rw [hA]; simp
    exact hxy (hmemA.mp hi₁A).symm
  let MA : Fin b → Fin c → ZMod 2 := fun j k => ∑ i ∈ A, v i j * w i k
  let MB : Fin b → Fin c → ZMod 2 := fun j k => ∑ i ∈ B, v i j * w i k
  let MC : Fin b → Fin c → ZMod 2 := fun j k => ∑ i ∈ C, v i j * w i k
  have hgrouped : ∀ p j k,
      x p * MA j k + y p * MB j k + (x p + y p) * MC j k = 0 := by
    intro p j k
    have hsumA : x p * MA j k = ∑ i ∈ A, u i p * v i j * w i k := by
      dsimp only [MA]
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i hi
      rw [hmemA.mp hi]
      ring
    have hsumB : y p * MB j k = ∑ i ∈ B, u i p * v i j * w i k := by
      dsimp only [MB]
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i hi
      rw [hmemB.mp hi]
      ring
    have hsumC : (x p + y p) * MC j k =
        ∑ i ∈ C, u i p * v i j * w i k := by
      dsimp only [MC]
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i hi
      rw [hmemC.mp hi]
      simp only [Pi.add_apply]
      ring
    calc
      x p * MA j k + y p * MB j k + (x p + y p) * MC j k =
          (∑ i ∈ A, u i p * v i j * w i k) +
            (∑ i ∈ B, u i p * v i j * w i k) +
              ∑ i ∈ C, u i p * v i j * w i k := by
        rw [hsumA, hsumB, hsumC]
      _ = ∑ i ∈ (A ∪ B) ∪ C, u i p * v i j * w i k := by
        rw [Finset.sum_union hABC, Finset.sum_union hAB]
      _ = 0 := by
        rw [hcover]
        exact hzero p j k
  obtain ⟨hMAC, hMBC⟩ := threeFiberSums_eq x y MA MB MC hLI hgrouped
  have hMAne : MA ≠ 0 := by
    apply matrixSum_ne_zero_of_minimal_constant_fiber u v w A x
      hMinimal hAne hAproper
    intro i hi
    exact hmemA.mp hi
  have hMCne : MC ≠ 0 := by
    intro hMC
    exact hMAne (hMAC.trans hMC)
  have hMBne : MB ≠ 0 := by
    intro hMB
    exact hMCne (hMBC.symm.trans hMB)
  have hCne : C.Nonempty :=
    fiber_nonempty_of_matrixSum_ne_zero v w C hMCne
  have hBne' : B.Nonempty :=
    fiber_nonempty_of_matrixSum_ne_zero v w B hMBne
  have hcards : A.card + B.card + C.card = 5 := by
    calc
      A.card + B.card + C.card = (A ∪ B).card + C.card := by
        rw [Finset.card_union_of_disjoint hAB]
      _ = ((A ∪ B) ∪ C).card := by
        rw [Finset.card_union_of_disjoint hABC]
      _ = 5 := by rw [hcover]; simp
  have hshapes := three_positive_sum_five
    (Finset.card_pos.mpr hAne) (Finset.card_pos.mpr hBne')
      (Finset.card_pos.mpr hCne) hcards
  have heqAC : ∀ j k, (∑ i ∈ A, v i j * w i k) =
      ∑ i ∈ C, v i j * w i k := by
    intro j k
    exact congrFun (congrFun hMAC j) k
  have heqBC : ∀ j k, (∑ i ∈ B, v i j * w i k) =
      ∑ i ∈ C, v i j * w i k := by
    intro j k
    exact congrFun (congrFun hMBC j) k
  have heqAB : ∀ j k, (∑ i ∈ A, v i j * w i k) =
      ∑ i ∈ B, v i j * w i k := by
    intro j k
    exact (heqAC j k).trans (heqBC j k).symm
  have hcoverBAC : (B ∪ A) ∪ C = Finset.univ := by
    simpa only [Finset.union_assoc, Finset.union_left_comm, Finset.union_comm] using hcover
  have hcoverCAB : (C ∪ A) ∪ B = Finset.univ := by
    simpa only [Finset.union_assoc, Finset.union_left_comm, Finset.union_comm] using hcover
  have hcoverACB : (A ∪ C) ∪ B = Finset.univ := by
    simpa only [Finset.union_assoc, Finset.union_left_comm, Finset.union_comm] using hcover
  have hcoverBCA : (B ∪ C) ∪ A = Finset.univ := by
    simpa only [Finset.union_assoc, Finset.union_left_comm, Finset.union_comm] using hcover
  rcases hshapes with h311 | h131 | h113 | h221 | h212 | h122
  · exact three_one_one_finset_finrank_le_four v w A B C hcover
      h311.1 h311.2.1 h311.2.2 hv hw heqAB heqAC
  · exact three_one_one_finset_finrank_le_four v w B A C hcoverBAC
      h131.2.1 h131.1 h131.2.2 hv hw (fun j k => (heqAB j k).symm) heqBC
  · exact three_one_one_finset_finrank_le_four v w C A B hcoverCAB
      h113.2.2 h113.1 h113.2.1 hv hw
      (fun j k => (heqAC j k).symm) (fun j k => (heqBC j k).symm)
  · exact two_two_one_finset_finrank_le_four v w A B C hcover
      h221.1 h221.2.1 h221.2.2 hv hw heqAC heqBC
  · exact two_two_one_finset_finrank_le_four v w A C B hcoverACB
      h212.1 h212.2.2 h212.2.1 hv hw heqAB (fun j k => (heqBC j k).symm)
  · exact two_two_one_finset_finrank_le_four v w B C A hcoverBCA
      h122.2.1 h122.2.2 h122.1 hv hw (fun j k => (heqAB j k).symm)
      (fun j k => (heqAC j k).symm)

/-- If one selected factor mode has rank at most two in a subset-minimal
five-term binary pure-tensor relation, the total factor profile is at most six. -/
theorem selectedMode_profile_finrank_le_six
    {a b c : ℕ}
    (u : Fin 5 → Fin a → ZMod 2)
    (v : Fin 5 → Fin b → ZMod 2)
    (w : Fin 5 → Fin c → ZMod 2)
    (hu : ∀ i, u i ≠ 0) (hv : ∀ i, v i ≠ 0) (hw : ∀ i, w i ≠ 0)
    (hzero : ∀ p j k, ∑ i, u i p * v i j * w i k = 0)
    (hMinimal : ∀ T : Finset (Fin 5),
      (∀ p j k, ∑ i ∈ T, u i p * v i j * w i k = 0) →
        T = ∅ ∨ T = Finset.univ)
    (hdim : Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) ≤ 2) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range w)) ≤ 6 := by
  classical
  have hspanNe : Submodule.span (ZMod 2) (Set.range u) ≠ ⊥ := by
    intro hbot
    have hu0mem : u 0 ∈ Submodule.span (ZMod 2) (Set.range u) :=
      Submodule.subset_span (Set.mem_range_self 0)
    rw [hbot] at hu0mem
    exact hu 0 (by simpa using hu0mem)
  have hpos : 1 ≤ Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) :=
    Submodule.one_le_finrank_iff.mpr hspanNe
  have hrank : Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range u)) = 1 ∨
      Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range u)) = 2 := by
    omega
  rcases hrank with hrankOne | hrankTwo
  · exact selectedMode_finrank_one_profile_le_six u v w hu hzero hrankOne
  · have hcomp := selectedMode_finrank_two_complementary_le_four
      u v w hu hv hw hzero hMinimal hrankTwo
    rw [hrankTwo]
    omega

/-- A collision-free binary pure-tensor `2 = 3` relation on `Fin 5` has
factor-profile sum at most six. -/
theorem pair_triple_profile_finrank_le_six
    {a b c : ℕ}
    (U : Fin 5 → Fin a → ZMod 2)
    (V : Fin 5 → Fin b → ZMod 2)
    (W : Fin 5 → Fin c → ZMod 2)
    (hnz : ∀ i, BilinearComplexity.triad (U i) (V i) (W i) ≠ 0)
    (hinj : Function.Injective fun i =>
      BilinearComplexity.triad (U i) (V i) (W i))
    (hsum : BilinearComplexity.triad (U 0) (V 0) (W 0) +
        BilinearComplexity.triad (U 1) (V 1) (W 1) =
      BilinearComplexity.triad (U 2) (V 2) (W 2) +
        BilinearComplexity.triad (U 3) (V 3) (W 3) +
          BilinearComplexity.triad (U 4) (V 4) (W 4)) :
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range U)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range V)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range W)) ≤ 6 := by
  classical
  let value : Fin 5 → BilinearComplexity.Tensor (ZMod 2) a b c :=
    fun i => BilinearComplexity.triad (U i) (V i) (W i)
  have htotal : ∑ i, value i = 0 := by
    calc
      (∑ i, value i) = (value 0 + value 1) + (value 2 + value 3 + value 4) := by
        simp only [Fin.sum_univ_succ]
        abel
      _ = (value 2 + value 3 + value 4) + (value 2 + value 3 + value 4) := by
        rw [show value 0 + value 1 = value 2 + value 3 + value 4 by
          simpa only [value] using hsum]
      _ = 0 := PairTripleSpan.add_self_eq_zero_f2 _
  have hzero : ∀ p j k, ∑ i, U i p * V i j * W i k = 0 := by
    intro p j k
    have hentry := congrFun (congrFun (congrFun htotal p) j) k
    simpa only [Finset.sum_apply, value, BilinearComplexity.triad,
      Pi.zero_apply] using hentry
  have hCycle : BilinearComplexity.BinaryCircuit.BinaryCycle
      value Finset.univ := by
    simpa [BilinearComplexity.BinaryCircuit.BinaryCycle,
      BilinearComplexity.BinaryCircuit.evaluation] using htotal
  have hCircuit : BilinearComplexity.BinaryCircuit.Circuit value Finset.univ :=
    BilinearComplexity.BinaryCircuit.circuit_of_binaryCycle_card_five
      hCycle (by simp) (fun i _ => hnz i)
        (fun _ _ _ _ heq => hinj (by simpa only [value] using heq))
  have hMinimal : ∀ T : Finset (Fin 5),
      (∀ p j k, ∑ i ∈ T, U i p * V i j * W i k = 0) →
        T = ∅ ∨ T = Finset.univ := by
    intro T hTzero
    by_cases hTempty : T = ∅
    · exact Or.inl hTempty
    · right
      by_contra hTuniv
      have hTproper : T ⊂ (Finset.univ : Finset (Fin 5)) :=
        Finset.ssubset_iff_subset_ne.mpr ⟨Finset.subset_univ T, hTuniv⟩
      have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hTempty
      have hTCycle : BilinearComplexity.BinaryCircuit.BinaryCycle value T := by
        rw [BilinearComplexity.BinaryCircuit.BinaryCycle,
          BilinearComplexity.BinaryCircuit.evaluation]
        ext p j k
        simpa only [Finset.sum_apply, value, BilinearComplexity.triad,
          Pi.zero_apply] using hTzero p j k
      exact hCircuit.2.2 T hTproper hTne hTCycle
  have hfac : ∀ i, U i ≠ 0 ∧ V i ≠ 0 ∧ W i ≠ 0 :=
    fun i => PairTripleSpan.factors_ne_zero_of_triad_ne_zero (hnz i)
  rcases PairTripleSpan.pair_triple_span_drop U V W hnz hinj hsum with
    hU | hV | hW
  · have hUdim := finrank_span_range_le_two_of_tail_mem_pair_span U hU
    exact selectedMode_profile_finrank_le_six U V W
      (fun i => (hfac i).1) (fun i => (hfac i).2.1) (fun i => (hfac i).2.2)
      hzero hMinimal hUdim
  · have hVdim := finrank_span_range_le_two_of_tail_mem_pair_span V hV
    have hzeroV : ∀ j p k, ∑ i, V i j * U i p * W i k = 0 := by
      intro j p k
      simpa only [mul_assoc, mul_left_comm, mul_comm] using hzero p j k
    have hMinimalV : ∀ T : Finset (Fin 5),
        (∀ j p k, ∑ i ∈ T, V i j * U i p * W i k = 0) →
          T = ∅ ∨ T = Finset.univ := by
      intro T hT
      apply hMinimal T
      intro p j k
      simpa only [mul_assoc, mul_left_comm, mul_comm] using hT j p k
    have hbound := selectedMode_profile_finrank_le_six V U W
      (fun i => (hfac i).2.1) (fun i => (hfac i).1) (fun i => (hfac i).2.2)
      hzeroV hMinimalV hVdim
    omega
  · have hWdim := finrank_span_range_le_two_of_tail_mem_pair_span W hW
    have hzeroW : ∀ k p j, ∑ i, W i k * U i p * V i j = 0 := by
      intro k p j
      simpa only [mul_assoc, mul_left_comm, mul_comm] using hzero p j k
    have hMinimalW : ∀ T : Finset (Fin 5),
        (∀ k p j, ∑ i ∈ T, W i k * U i p * V i j = 0) →
          T = ∅ ∨ T = Finset.univ := by
      intro T hT
      apply hMinimal T
      intro p j k
      simpa only [mul_assoc, mul_left_comm, mul_comm] using hT k p j
    have hbound := selectedMode_profile_finrank_le_six W U V
      (fun i => (hfac i).2.2) (fun i => (hfac i).1) (fun i => (hfac i).2.1)
      hzeroW hMinimalW hWdim
    omega

/-- The endpoint hypotheses are jointly satisfiable on the standard five-term
binary relation. -/
example :
    let U : Fin 5 → Fin 2 → ZMod 2 :=
      ![![1, 0], ![0, 1], ![1, 1], ![1, 0], ![0, 1]]
    let V : Fin 5 → Fin 1 → ZMod 2 :=
      ![![1], ![1], ![1], ![1], ![1]]
    let W : Fin 5 → Fin 2 → ZMod 2 :=
      ![![1, 0], ![0, 1], ![1, 1], ![0, 1], ![1, 0]]
    Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range U)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range V)) +
        Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range W)) ≤ 6 := by
  dsimp only
  apply pair_triple_profile_finrank_le_six
  · decide
  · decide
  · decide

/-- K1 is jointly satisfiable nontrivially: two identical binary outer products
cancel, while both factor spans are nonzero. -/
example :
    let u : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let v : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    (∀ j k, ∑ i, u i j * v i k = 0) ∧
      Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range u)) +
          Module.finrank (ZMod 2) (Submodule.span (ZMod 2) (Set.range v)) ≤ 2 := by
  dsimp only
  have hzero : ∀ (_j _k : Fin 1), ∑ _i : Fin 2, (1 : ZMod 2) * 1 = 0 := by
    decide
  exact ⟨hzero, twoModeCancellation_finrank_le _ _ hzero⟩

/-- The disjoint-fiber K1 wrapper is jointly satisfiable on two equal singleton
outer products. -/
example :
    let u : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let v : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let S : Finset (Fin 2) := {0}
    let T : Finset (Fin 2) := {1}
    Disjoint S T ∧
      (∀ j k, (∑ i ∈ S, u i j * v i k) = ∑ i ∈ T, u i j * v i k) ∧
      Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (u '' ((S ∪ T : Finset (Fin 2)) : Set (Fin 2)))) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (v '' ((S ∪ T : Finset (Fin 2)) : Set (Fin 2)))) ≤
        S.card + T.card := by
  dsimp only
  have hDisjoint : Disjoint ({0} : Finset (Fin 2)) {1} := by decide
  have heq : ∀ (_j _k : Fin 1),
      (∑ _i ∈ ({0} : Finset (Fin 2)), (1 : ZMod 2) * 1) =
        ∑ _i ∈ ({1} : Finset (Fin 2)), (1 : ZMod 2) * 1 := by decide
  exact ⟨hDisjoint, heq,
    twoModeEqualDisjointSums_finrank_le {0} {1}
      (fun _ _ => 1) (fun _ _ => 1) hDisjoint heq⟩

/-- The overlap lemma is jointly satisfiable with two equal nonzero lines. -/
example :
    let P : Submodule (ZMod 2) (Fin 1 → ZMod 2) := ⊤
    let Q : Submodule (ZMod 2) (Fin 1 → ZMod 2) := ⊤
    let x : Fin 1 → ZMod 2 := fun _ => 1
    x ∈ P ∧ x ∈ Q ∧ x ≠ 0 ∧
      Module.finrank (ZMod 2) (P ⊔ Q : Submodule (ZMod 2) (Fin 1 → ZMod 2)) + 1 ≤
        Module.finrank (ZMod 2) P + Module.finrank (ZMod 2) Q := by
  dsimp only
  have hx : (fun _ : Fin 1 => (1 : ZMod 2)) ≠ 0 := by
    intro h
    have h0 := congrFun h 0
    simp at h0
  refine ⟨by simp, by simp, hx, ?_⟩
  exact finrank_sup_add_one_le_of_common_nonzero ⊤ ⊤ (by simp) (by simp) hx

/-- The binary finrank-two profile hypotheses are jointly satisfiable by the
standard basis of the two-coordinate function space. -/
example :
    ∃ u : Fin 2 → Fin 2 → ZMod 2,
      (∀ i, u i ≠ 0) ∧
      Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range u)) = 2 ∧
      ∃ i₀ i₁, i₀ ≠ i₁ ∧ LinearIndependent (ZMod 2) ![u i₀, u i₁] ∧
        ∀ i, u i = u i₀ ∨ u i = u i₁ ∨ u i = u i₀ + u i₁ := by
  let u : Fin 2 → Fin 2 → ZMod 2 := ![![1, 0], ![0, 1]]
  have hu₀ : u 0 ≠ 0 := by decide
  have hu₁ : u 1 ≠ 0 := by decide
  have hu : ∀ i, u i ≠ 0 := by
    intro i
    fin_cases i
    · exact hu₀
    · exact hu₁
  have hune : u 0 ≠ u 1 := by decide
  have hLI : LinearIndependent (ZMod 2) u :=
    PairTripleSpan.pair_linearIndependent_of_ne hu₀ hu₁ hune
  have hdim : Module.finrank (ZMod 2)
      (Submodule.span (ZMod 2) (Set.range u)) = 2 := by
    simpa only [Fintype.card_fin] using finrank_span_eq_card hLI
  exact ⟨u, hu, hdim, f2_finrank_two_range_profile u hu hdim⟩

/-- The three-fiber collection identity is jointly satisfiable for the standard
binary basis and a common nonzero one-by-one complementary matrix. -/
example :
    let x : Fin 2 → ZMod 2 := ![1, 0]
    let y : Fin 2 → ZMod 2 := ![0, 1]
    let A : Fin 1 → Fin 1 → ZMod 2 := fun _ _ => 1
    let B : Fin 1 → Fin 1 → ZMod 2 := fun _ _ => 1
    let C : Fin 1 → Fin 1 → ZMod 2 := fun _ _ => 1
    LinearIndependent (ZMod 2) ![x, y] ∧
      (∀ p j k, x p * A j k + y p * B j k + (x p + y p) * C j k = 0) ∧
      A = C ∧ B = C := by
  dsimp only
  have hLI : LinearIndependent (ZMod 2)
      ![(![1, 0] : Fin 2 → ZMod 2), ![0, 1]] :=
    PairTripleSpan.pair_linearIndependent_of_ne (by decide) (by decide) (by decide)
  have hrel : ∀ (p : Fin 2) (j k : Fin 1),
      (![1, 0] p : ZMod 2) * 1 + ![0, 1] p * 1 +
        (![1, 0] p + ![0, 1] p) * 1 = 0 := by decide
  exact ⟨hLI, hrel, threeFiberSums_eq _ _ _ _ _ hLI hrel⟩

/-- The minimal-fiber hypotheses are jointly satisfiable for the two-term
minimal binary relation consisting of two equal nonzero pure coordinates. -/
example :
    let u : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let v : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let w : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let S : Finset (Fin 2) := {0}
    let x : Fin 1 → ZMod 2 := fun _ => 1
    (∀ T : Finset (Fin 2),
      (∀ p j k, ∑ i ∈ T, u i p * v i j * w i k = 0) →
        T = ∅ ∨ T = Finset.univ) ∧
      S.Nonempty ∧ S ≠ Finset.univ ∧ (∀ i ∈ S, u i = x) ∧
      (fun j k => ∑ i ∈ S, v i j * w i k) ≠ 0 ∧ S.Nonempty := by
  dsimp only
  have hMinimal : ∀ T : Finset (Fin 2),
      (∀ (_p _j _k : Fin 1), ∑ _i ∈ T, (1 : ZMod 2) * 1 * 1 = 0) →
        T = ∅ ∨ T = Finset.univ := by decide
  have hS : ({0} : Finset (Fin 2)).Nonempty := by decide
  have hProper : ({0} : Finset (Fin 2)) ≠ Finset.univ := by decide
  have hConstant : ∀ i ∈ ({0} : Finset (Fin 2)),
      (fun _ : Fin 1 => (1 : ZMod 2)) = fun _ => 1 := by simp
  have hMatrix := matrixSum_ne_zero_of_minimal_constant_fiber
    (fun _ _ => 1) (fun _ _ => 1) (fun _ _ => 1) {0} (fun _ => 1)
    hMinimal hS hProper hConstant
  exact ⟨hMinimal, hS, hProper, hConstant, hMatrix,
    fiber_nonempty_of_matrixSum_ne_zero (fun _ _ => 1) (fun _ _ => 1) {0} hMatrix⟩

/-- The `(3,1,1)` rank-bound hypotheses are jointly satisfiable by five equal
one-by-one factors; distinctness is intentionally not needed by this helper. -/
example :
    let u : Fin 3 → Fin 1 → ZMod 2 := fun _ _ => 1
    let v : Fin 3 → Fin 1 → ZMod 2 := fun _ _ => 1
    let u₀ : Fin 1 → ZMod 2 := fun _ => 1
    let u₁ : Fin 1 → ZMod 2 := fun _ => 1
    let v₀ : Fin 1 → ZMod 2 := fun _ => 1
    let v₁ : Fin 1 → ZMod 2 := fun _ => 1
    (∀ j k, (∑ i, u i j * v i k) + u₀ j * v₀ k = 0) ∧
      (∀ j k, u₀ j * v₀ k = u₁ j * v₁ k) ∧
      Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range u ∪ {u₀, u₁})) +
        Module.finrank (ZMod 2)
          (Submodule.span (ZMod 2) (Set.range v ∪ {v₀, v₁})) ≤ 4 := by
  dsimp only
  have hn : (fun _ : Fin 1 => (1 : ZMod 2)) ≠ 0 := by decide
  have hzero : ∀ (_j _k : Fin 1),
      (∑ _i : Fin 3, (1 : ZMod 2) * 1) + 1 * 1 = 0 := by decide
  have heq : ∀ (_j _k : Fin 1), (1 : ZMod 2) * 1 = 1 * 1 := by decide
  exact ⟨hzero, heq,
    three_one_one_finrank_le_four _ _ _ _ _ _ hn hn hn hn hzero heq⟩

/-- The `(2,2,1)` rank-bound hypotheses are jointly satisfiable when one term
in each two-element fiber equals the singleton outer product and one is zero. -/
example :
    let uA : Fin 2 → Fin 1 → ZMod 2 := ![fun _ => 1, fun _ => 0]
    let uB : Fin 2 → Fin 1 → ZMod 2 := ![fun _ => 1, fun _ => 0]
    let vA : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let vB : Fin 2 → Fin 1 → ZMod 2 := fun _ _ => 1
    let u₀ : Fin 1 → ZMod 2 := fun _ => 1
    let v₀ : Fin 1 → ZMod 2 := fun _ => 1
    (∀ j k, (∑ i, uA i j * vA i k) + u₀ j * v₀ k = 0) ∧
      (∀ j k, (∑ i, uB i j * vB i k) + u₀ j * v₀ k = 0) ∧
      Module.finrank (ZMod 2)
          ((Submodule.span (ZMod 2) (Set.range uA ∪ {u₀})) ⊔
            Submodule.span (ZMod 2) (Set.range uB ∪ {u₀}) :
            Submodule (ZMod 2) (Fin 1 → ZMod 2)) +
        Module.finrank (ZMod 2)
          ((Submodule.span (ZMod 2) (Set.range vA ∪ {v₀})) ⊔
            Submodule.span (ZMod 2) (Set.range vB ∪ {v₀}) :
            Submodule (ZMod 2) (Fin 1 → ZMod 2)) ≤ 4 := by
  dsimp only
  have hn : (fun _ : Fin 1 => (1 : ZMod 2)) ≠ 0 := by decide
  have hzero : ∀ (_j _k : Fin 1),
      (∑ i : Fin 2, (![fun _ : Fin 1 => (1 : ZMod 2), fun _ => 0] i) _j * 1) +
        1 * 1 = 0 := by decide
  exact ⟨hzero, hzero,
    two_two_one_finrank_le_four _ _ _ _ _ _ hn hn hzero hzero⟩

/-- The positive-cardinality arithmetic case split is jointly satisfiable. -/
example :
    (0 < 3) ∧ (0 < 1) ∧ (0 < 1) ∧ 3 + 1 + 1 = 5 ∧
      ((3 = 3 ∧ 1 = 1 ∧ 1 = 1) ∨
       (3 = 1 ∧ 1 = 3 ∧ 1 = 1) ∨
       (3 = 1 ∧ 1 = 1 ∧ 1 = 3) ∨
       (3 = 2 ∧ 1 = 2 ∧ 1 = 1) ∨
       (3 = 2 ∧ 1 = 1 ∧ 1 = 2) ∨
       (3 = 1 ∧ 1 = 2 ∧ 1 = 2)) := by
  refine ⟨by omega, by omega, by omega, by omega, ?_⟩
  exact three_positive_sum_five (by omega) (by omega) (by omega) (by omega)

#check @twoModeCancellation_finrank_le
#check @twoModeCancellation_finset_finrank_le
#check @twoModeEqualDisjointSums_finrank_le
#check @finrank_sup_add_one_le_of_common_nonzero
#check @cancellationWithSingleton_finrank_le
#check @f2_finrank_two_range_profile
#check @threeFiberSums_eq
#check @matrixSum_ne_zero_of_minimal_constant_fiber
#check @fiber_nonempty_of_matrixSum_ne_zero
#check @three_one_one_finrank_le_four
#check @two_two_one_finrank_le_four
#check @three_positive_sum_five
#check @finrank_span_range_le_two_of_tail_mem_pair_span
#check @selectedMode_finrank_one_profile_le_six
#check @three_one_one_finset_finrank_le_four
#check @two_two_one_finset_finrank_le_four
#check @selectedMode_finrank_two_complementary_le_four
#check @selectedMode_profile_finrank_le_six
#check @pair_triple_profile_finrank_le_six

#print axioms twoModeCancellation_finrank_le
#print axioms twoModeCancellation_finset_finrank_le
#print axioms twoModeEqualDisjointSums_finrank_le
#print axioms finrank_sup_add_one_le_of_common_nonzero
#print axioms cancellationWithSingleton_finrank_le
#print axioms f2_finrank_two_range_profile
#print axioms threeFiberSums_eq
#print axioms matrixSum_ne_zero_of_minimal_constant_fiber
#print axioms fiber_nonempty_of_matrixSum_ne_zero
#print axioms three_one_one_finrank_le_four
#print axioms two_two_one_finrank_le_four
#print axioms three_positive_sum_five
#print axioms finrank_span_range_le_two_of_tail_mem_pair_span
#print axioms selectedMode_finrank_one_profile_le_six
#print axioms three_one_one_finset_finrank_le_four
#print axioms two_two_one_finset_finrank_le_four
#print axioms selectedMode_finrank_two_complementary_le_four
#print axioms selectedMode_profile_finrank_le_six
#print axioms pair_triple_profile_finrank_le_six

end BilinearComplexity.ProfileInequalityExperiment
